### ISSUE TITLE
List view breaks with circular structure json error

### ISSUE THREAD

**Issue by warmfusion** [argoproj/argo-cd#10153]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When viewing an application, when switching to the `List` view _after_ viewing the `Pods` view, the interface crashes.

```
Something went wrong!

Consider submitting an issue [here](https://github.com/argoproj/argo-cd/issues/new?labels=bug&template=bug_report.md).


Stacktrace:

TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    --- property 'root' closes the circle
    at JSON.stringify (<anonymous>)
    at t.getDerivedStateFromProps (https://argocd.futuretech.tools/main.f0611b1072a7dbee7fda.js:2:1116550)
    at _o (https://argocd.futuretech.tools/main.f0611b1072a7dbee7fda.js:2:783892)
    at Co (https://argocd.futuretech.tools/main.f0611b1072a7dbee7fda.js:2:785672)
    at js (https://argocd.futuretech.tools/main.f0611b1072a7dbee7fda.js:2:802313)
    at ya (https://argocd.futuretech.tools/main.f0611b1072a7dbee7fda.js:2:840345)
    at pl (https://argocd.futuretech.tools/main.f0611b1072a7dbee7fda.js:2:831820)
    at dl (https://argocd.futuretech.tools/main.f0611b1072a7dbee7fda.js:2:831745)
    at il (https://argocd.futuretech.tools/main.f0611b1072a7dbee7fda.js:2:828775)
    at https://argocd.futuretech.tools/main.f0611b1072a7dbee7fda.js:2:780554
```
**To Reproduce**

1. Open an app
2. View `Pods`
3. View `List`

**Expected behavior**

List view works, like it does when you _dont_ first view the Pods interface.

**Screenshots**

Attempted to capture the failure and show what might be the data floating around, but it doesn't look to be a problem?

![image](https://user-images.githubusercontent.com/2294568/182123855-ac2707d3-d3a7-42e5-a4f0-39b2d4e81034.png)

**Version**

```json
{
    "Version": "v2.4.8+844f79e",
    "BuildDate": "2022-07-29T17:01:39Z",
    "GitCommit": "844f79eb9d8f3ab96d4ce6f8df211c6093a660ba",
    "GitTreeState": "clean",
    "GoVersion": "go1.18.4",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v4.4.1 2021-11-11T23:36:27Z",
    "HelmVersion": "v3.8.1+g5cb9af4",
    "KubectlVersion": "v0.23.1",
    "JsonnetVersion": "v0.18.0"
}
```

**Logs**

N/A - Entierly client side.

**Comment by saumeya** [comment]
Not able to reproduce this bug @warmfusion, any further info that you can add?
