### ISSUE TITLE
Can not open ArgoCD UI after Helm Install using rancher

### ISSUE THREAD

**Issue by giz33** [argoproj/argo-cd#10413]
Checklist:

* [ x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x ] I've included steps to reproduce the bug.
* [ X] I've pasted the output of `argocd version`.

**Describe the bug**

I installed ArgoCD on my cluster using helm chart via Rancher and when I click on my https service[argocd-server](https://172.104.198.160/dashboard/c/c-m-v4rg789q/explorer/service/default/argocd-server), an error page appears

**To Reproduce**

Create a vanilla k8s cluster, add this cluster to Rancher.Add helm URL to rancher https://argoproj.github.io/argo-helm, install via helm and then go to ServiceDiscovery.
On ServiceDiscovery, locate argocd-server and click on https blue button.

**Expected behavior**

A page will appear with this errors:
Stacktrace:

TypeError: Cannot read properties of null (reading 'Version')
    at t.buildVersionTable (https://172.104.198.160/k8s/clusters/c-m-v4rg789q/api/v1/namespaces/default/services/https:argocd-server:443/proxy/main.4b6836f63d2e22a17da6.js:2:1702966)
    at Object.children (https://172.104.198.160/k8s/clusters/c-m-v4rg789q/api/v1/namespaces/default/services/https:argocd-server:443/proxy/main.4b6836f63d2e22a17da6.js:2:1702769)
    at t.render (https://172.104.198.160/k8s/clusters/c-m-v4rg789q/api/v1/namespaces/default/services/https:argocd-server:443/proxy/main.4b6836f63d2e22a17da6.js:2:1117093)
    at Hs (https://172.104.198.160/k8s/clusters/c-m-v4rg789q/api/v1/namespaces/default/services/https:argocd-server:443/proxy/main.4b6836f63d2e22a17da6.js:2:804799)
    at js (https://172.104.198.160/k8s/clusters/c-m-v4rg789q/api/v1/namespaces/default/services/https:argocd-server:443/proxy/main.4b6836f63d2e22a17da6.js:2:804594)
    at ya (https://172.104.198.160/k8s/clusters/c-m-v4rg789q/api/v1/namespaces/default/services/https:argocd-server:443/proxy/main.4b6836f63d2e22a17da6.js:2:840075)
    at pl (https://172.104.198.160/k8s/clusters/c-m-v4rg789q/api/v1/namespaces/default/services/https:argocd-server:443/proxy/main.4b6836f63d2e22a17da6.js:2:831550)
    at dl (https://172.104.198.160/k8s/clusters/c-m-v4rg789q/api/v1/namespaces/default/services/https:argocd-server:443/proxy/main.4b6836f63d2e22a17da6.js:2:831475)
    at il (https://172.104.198.160/k8s/clusters/c-m-v4rg789q/api/v1/namespaces/default/services/https:argocd-server:443/proxy/main.4b6836f63d2e22a17da6.js:2:828505)
    at https://172.104.198.160/k8s/clusters/c-m-v4rg789q/api/v1/namespaces/default/services/https:argocd-server:443/proxy/main.4b6836f63d2e22a17da6.js:2:780284

**Screenshots**

![image](https://user-images.githubusercontent.com/19286616/185777868-c9bb300f-d7aa-46d5-88ea-c4a70c84beec.png)

**Version**

```shell
argo-cd:4.10.1```

**Logs**

```
No logs
```

**Comment by kosksq** [comment]
Hi, I have the same issue. Did you find any solution?

**Comment by jonathon2nd** [comment]
Happens even when using yaml
```
kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/v2.4.12/manifests/ha/install.yaml
```
It would be nice to be able to just go though Rancher Proxy, instead setting up something else (nodeport, ingress, port-forward, etc.)

**Comment by jonathon2nd** [comment]
Exact same issue observed here: https://github.com/argoproj/argo-cd/issues/8281

**Comment by adolfomaltez** [comment]
Same issue here!
In a test environment on the same subnet, it works fine.
When I do it in different subnet it shows the error:
![argocd-issue](https://user-images.githubusercontent.com/1231699/217103884-adf508f9-5c52-4382-9e08-d9ed3c1db452.png)

**Comment by CyanCode** [comment]
Running into this same issue on my end

**Comment by kosksq** [comment]
I solved this problem a long time ago. Instead of using the default port to access Argo CD, you should open your own node port for accessing the portal. That’s the solution i came up with.

**Comment by CyanCode** [comment]
Hey @kosksq thanks for your reply. Unfortunately I'm still stuck on this a few days later-- was there anything you did beyond mapping the service port to an Ingress resource? I'm using nginx as an ingress controller.

The ingress controller logs reveal very little about what the hangup is:
`myip - - [10/Sep/2023:03:58:58 +0000] "GET / HTTP/1.1" 308 164 "-" "curl/7.55.1" 90 0.000 [argocd-argocd-server-https] [] - - - - 435cef5480c1530899993570ef1aecd4`

**Comment by bugyaru** [comment]
![image](https://github.com/user-attachments/assets/1adbad89-9af9-44ef-9095-e9fad3444793)
confuses one slash in Url after the protocol
