### ISSUE TITLE
Controller deadlock during CRD install + app refresh

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#1044]
I am eventually to reproduce a controller deadlock using some combination of:
* syncing an application containing a CRD
* deleting the CRD object
* refreshing an app which contains the CRD simultaneous

This is timing related, and takes a few tries to deadlock, but it is repeatable. Once the controller is deadlocked, I captured the following partial stacktrace:

```
goroutine 58 [semacquire]:
sync.runtime_SemacquireMutex(0xc000c85434, 0xc0007ad800)
    /usr/local/Cellar/go/1.11.4/libexec/src/runtime/sema.go:71 +0x3d
sync.(*Mutex).Lock(0xc000c85430)
    /usr/local/Cellar/go/1.11.4/libexec/src/sync/mutex.go:134 +0xff
github.com/argoproj/argo-cd/controller/cache.(*clusterInfo).processEvent(0xc000530b60, 0xc000c311e8, 0x8, 0xc000724508, 0x0, 0x0)
    /Users/jsuen/go/src/github.com/argoproj/argo-cd/controller/cache/cluster.go:266 +0x8c
github.com/argoproj/argo-cd/controller/cache.(*liveStateCache).processEvent(0xc000430d20, 0xc000c311e8, 0x8, 0xc000724508, 0x23e839c, 0x1e, 0x0, 0x0)
    /Users/jsuen/go/src/github.com/argoproj/argo-cd/controller/cache/cache.go:76 +0x92
github.com/argoproj/argo-cd/controller/cache.(*liveStateCache).watchClusterResources.func1(0x0, 0x0)
    /Users/jsuen/go/src/github.com/argoproj/argo-cd/controller/cache/cache.go:285 +0x339
github.com/argoproj/argo-cd/util.RetryUntilSucceed(0xc0009bbeb0, 0xc0000423c0, 0x35, 0x25c9100, 0xc00044a140, 0x2540be400)
    /Users/jsuen/go/src/github.com/argoproj/argo-cd/util/util.go:94 +0x205
github.com/argoproj/argo-cd/controller/cache.(*liveStateCache).watchClusterResources(0xc000430d20, 0x25c9100, 0xc00044a140, 0x23e839c, 0x1e, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    /Users/jsuen/go/src/github.com/argoproj/argo-cd/controller/cache/cache.go:251 +0x15f
created by github.com/argoproj/argo-cd/controller/cache.(*liveStateCache).Run.func1.1
    /Users/jsuen/go/src/github.com/argoproj/argo-cd/controller/cache/cache.go:207 +0x2e6


goroutine 98 [sync.Cond.Wait]:
sync.runtime_notifyListWait(0xc0004520d8, 0xc00000000b)
    /usr/local/Cellar/go/1.11.4/libexec/src/runtime/sema.go:510 +0xeb
sync.(*Cond).Wait(0xc0004520c8)
    /usr/local/Cellar/go/1.11.4/libexec/src/sync/cond.go:56 +0x92
github.com/argoproj/argo-cd/vendor/k8s.io/client-go/tools/cache.(*DeltaFIFO).Pop(0xc0004520b0, 0xc00065c920, 0x0, 0x0, 0x0, 0x0)
    /Users/jsuen/go/src/github.com/argoproj/argo-cd/vendor/k8s.io/client-go/tools/cache/delta_fifo.go:431 +0x99
github.com/argoproj/argo-cd/vendor/k8s.io/client-go/tools/cache.(*controller).processLoop(0xc000644d00)
    /Users/jsuen/go/src/github.com/argoproj/argo-cd/vendor/k8s.io/client-go/tools/cache/controller.go:150 +0x40
github.com/argoproj/argo-cd/vendor/k8s.io/client-go/tools/cache.(*controller).processLoop-fm()
    /Users/jsuen/go/src/github.com/argoproj/argo-cd/vendor/k8s.io/client-go/tools/cache/controller.go:124 +0x2a
github.com/argoproj/argo-cd/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc0005a2ef0)
    /Users/jsuen/go/src/github.com/argoproj/argo-cd/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x54
github.com/argoproj/argo-cd/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0005a2ef0, 0x3b9aca00, 0x0, 0xc00073ed01, 0xc0000b2600)
    /Users/jsuen/go/src/github.com/argoproj/argo-cd/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0xbe
github.com/argoproj/argo-cd/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc0005a2ef0, 0x3b9aca00, 0xc0000b2600)
    /Users/jsuen/go/src/github.com/argoproj/argo-cd/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
github.com/argoproj/argo-cd/vendor/k8s.io/client-go/tools/cache.(*controller).Run(0xc000644d00, 0xc0000b2600)
    /Users/jsuen/go/src/github.com/argoproj/argo-cd/vendor/k8s.io/client-go/tools/cache/controller.go:124 +0x299
github.com/argoproj/argo-cd/vendor/k8s.io/client-go/tools/cache.(*sharedIndexInformer).Run(0xc00016e480, 0xc0000b2600)
    /Users/jsuen/go/src/github.com/argoproj/argo-cd/vendor/k8s.io/client-go/tools/cache/shared_informer.go:227 +0x40d
created by github.com/argoproj/argo-cd/controller.(*ApplicationController).Run
    /Users/jsuen/go/src/github.com/argoproj/argo-cd/controller/appcontroller.go:330 +0xe4

goroutine 105 [semacquire]:
sync.runtime_Semacquire(0xc0005db998)
    /usr/local/Cellar/go/1.11.4/libexec/src/runtime/sema.go:56 +0x39
sync.(*WaitGroup).Wait(0xc0005db990)
    /usr/local/Cellar/go/1.11.4/libexec/src/sync/waitgroup.go:130 +0x64
github.com/argoproj/argo-cd/util.RunAllAsync(0x5, 0xc0009dcc00, 0xc0010051b8, 0xc0003ee498)
    /Users/jsuen/go/src/github.com/argoproj/argo-cd/util/util.go:139 +0x112
github.com/argoproj/argo-cd/controller/cache.(*clusterInfo).getManagedLiveObjs(0xc000530b60, 0xc00098d880, 0xc0009dcb80, 0x5, 0x8, 0x0, 0x0, 0x0)
    /Users/jsuen/go/src/github.com/argoproj/argo-cd/controller/cache/cluster.go:200 +0x2dc
github.com/argoproj/argo-cd/controller/cache.(*liveStateCache).GetManagedLiveObjs(0xc000430d20, 0xc00098d880, 0xc0009dcb80, 0x5, 0x8, 0x0, 0x0, 0x0)
    /Users/jsuen/go/src/github.com/argoproj/argo-cd/controller/cache/cache.go:167 +0xb4
github.com/argoproj/argo-cd/controller.(*appStateManager).CompareAppState(0xc000536500, 0xc00098d880, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc0005966c0, 0x0, ...)
    /Users/jsuen/go/src/github.com/argoproj/argo-cd/controller/state.go:161 +0x3ec
github.com/argoproj/argo-cd/controller.(*ApplicationController).processAppRefreshQueueItem(0xc0004e0400, 0x1)
    /Users/jsuen/go/src/github.com/argoproj/argo-cd/controller/appcontroller.go:704 +0x46d
github.com/argoproj/argo-cd/controller.(*ApplicationController).Run.func1()
    /Users/jsuen/go/src/github.com/argoproj/argo-cd/controller/appcontroller.go:343 +0x36
github.com/argoproj/argo-cd/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc0007fe000)
    /Users/jsuen/go/src/github.com/argoproj/argo-cd/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x54
github.com/argoproj/argo-cd/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0007fe000, 0x3b9aca00, 0x0, 0x1, 0xc0000b2600)
    /Users/jsuen/go/src/github.com/argoproj/argo-cd/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0xbe
github.com/argoproj/argo-cd/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc0007fe000, 0x3b9aca00, 0xc0000b2600)
    /Users/jsuen/go/src/github.com/argoproj/argo-cd/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by github.com/argoproj/argo-cd/controller.(*ApplicationController).Run
    /Users/jsuen/go/src/github.com/argoproj/argo-cd/controller/appcontroller.go:342 +0x2cd

goroutine 106 [sync.Cond.Wait]:
sync.runtime_notifyListWait(0xc00072add0, 0xc000000006)
    /usr/local/Cellar/go/1.11.4/libexec/src/runtime/sema.go:510 +0xeb
sync.(*Cond).Wait(0xc00072adc0)
    /usr/local/Cellar/go/1.11.4/libexec/src/sync/cond.go:56 +0x92
github.com/argoproj/argo-cd/vendor/k8s.io/client-go/util/workqueue.(*Type).Get(0xc000430be0, 0x0, 0x0, 0x2471700)
    /Users/jsuen/go/src/github.com/argoproj/argo-cd/vendor/k8s.io/client-go/util/workqueue/queue.go:124 +0x90
github.com/argoproj/argo-cd/controller.(*ApplicationController).processAppOperationQueueItem(0xc0004e0400, 0x0)
    /Users/jsuen/go/src/github.com/argoproj/argo-cd/controller/appcontroller.go:411 +0x51
github.com/argoproj/argo-cd/controller.(*ApplicationController).Run.func2()
    /Users/jsuen/go/src/github.com/argoproj/argo-cd/controller/appcontroller.go:350 +0x36
github.com/argoproj/argo-cd/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc0007fe010)
    /Users/jsuen/go/src/github.com/argoproj/argo-cd/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x54
github.com/argoproj/argo-cd/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0007fe010, 0x3b9aca00, 0x0, 0x1, 0xc0000b2600)
    /Users/jsuen/go/src/github.com/argoproj/argo-cd/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0xbe
github.com/argoproj/argo-cd/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc0007fe010, 0x3b9aca00, 0xc0000b2600)
    /Users/jsuen/go/src/github.com/argoproj/argo-cd/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by github.com/argoproj/argo-cd/controller.(*ApplicationController).Run
    /Users/jsuen/go/src/github.com/argoproj/argo-cd/controller/appcontroller.go:349 +0x394


goroutine 121 [chan receive]:
github.com/argoproj/argo-cd/vendor/k8s.io/client-go/tools/cache.(*processorListener).run.func1.1(0x102c0f3, 0xc00058cdc8, 0xc00058cdd8)
    /Users/jsuen/go/src/github.com/argoproj/argo-cd/vendor/k8s.io/client-go/tools/cache/shared_informer.go:549 +0x54
github.com/argoproj/argo-cd/vendor/k8s.io/apimachinery/pkg/util/wait.ExponentialBackoff(0x989680, 0x3ff0000000000000, 0x3fb999999999999a, 0x5, 0xc0007aae18, 0x102bc02, 0xc0000e8620)
    /Users/jsuen/go/src/github.com/argoproj/argo-cd/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:203 +0x9c
github.com/argoproj/argo-cd/vendor/k8s.io/client-go/tools/cache.(*processorListener).run.func1()
    /Users/jsuen/go/src/github.com/argoproj/argo-cd/vendor/k8s.io/client-go/tools/cache/shared_informer.go:548 +0x89
github.com/argoproj/argo-cd/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc00058cf68)
    /Users/jsuen/go/src/github.com/argoproj/argo-cd/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x54
github.com/argoproj/argo-cd/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0007aaf68, 0xdf8475800, 0x0, 0x21aee01, 0xc0004ec0c0)
    /Users/jsuen/go/src/github.com/argoproj/argo-cd/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0xbe
github.com/argoproj/argo-cd/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc00058cf68, 0xdf8475800, 0xc0004ec0c0)
    /Users/jsuen/go/src/github.com/argoproj/argo-cd/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
github.com/argoproj/argo-cd/vendor/k8s.io/client-go/tools/cache.(*processorListener).run(0xc0006aa000)
    /Users/jsuen/go/src/github.com/argoproj/argo-cd/vendor/k8s.io/client-go/tools/cache/shared_informer.go:546 +0x8d
github.com/argoproj/argo-cd/vendor/k8s.io/client-go/tools/cache.(*processorListener).run-fm()
    /Users/jsuen/go/src/github.com/argoproj/argo-cd/vendor/k8s.io/client-go/tools/cache/shared_informer.go:390 +0x2a
github.com/argoproj/argo-cd/vendor/k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc0004f0610, 0xc0007300b0)
    /Users/jsuen/go/src/github.com/argoproj/argo-cd/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x4f
created by github.com/argoproj/argo-cd/vendor/k8s.io/apimachinery/pkg/util/wait.(*Group).Start
    /Users/jsuen/go/src/github.com/argoproj/argo-cd/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:69 +0x62
```

**Comment by jessesuen** [comment]
Found the source of the deadlock. It happens during error situations when the call to getManagedLiveObjs() -> handleError() makes a re-entrant lock call.

cluster.go
```golang
func (c *clusterInfo) getManagedLiveObjs(a *appv1.Application, targetObjs []*unstructured.Unstructured) (map[kube.ResourceKey]*unstructured.Unstructured, error) {
	c.lock.Lock() // <<<<< acquired
	defer c.lock.Unlock()

	managedObjs := make(map[kube.ResourceKey]*unstructured.Unstructured)
	for key, o := range c.nodes {
		if o.appName == a.Name && o.resource != nil && len(o.ownerRefs) == 0 {
			managedObjs[key] = o.resource
		}
	}
	lock := &sync.Mutex{}
	err := util.RunAllAsync(len(targetObjs), func(i int) error {
		targetObj := targetObjs[i]
		key := GetTargetObjKey(a, targetObj, c.isNamespaced(targetObj.GroupVersionKind()))
		lock.Lock()
		managedObj := managedObjs[key]
		lock.Unlock()

		if managedObj == nil {
			if existingObj, exists := c.nodes[key]; exists {
				if existingObj.resource != nil {
					managedObj = existingObj.resource
				} else {
					var err error
					managedObj, err = c.kubectl.GetResource(c.cluster.RESTConfig(), targetObj.GroupVersionKind(), existingObj.ref.Name, existingObj.ref.Namespace)
					err = c.handleError(targetObj.GroupVersionKind(), existingObj.ref.Namespace, existingObj.ref.Name, err) // <<<<<< called

```

```golang
func (c *clusterInfo) handleError(gvk schema.GroupVersionKind, namespace string, name string, err error) error {
	if err != nil && errors.IsNotFound(err) {
		c.lock.Lock() /// <<< deadlock
		defer c.lock.Unlock()
```
