### ISSUE TITLE
Repo server crashing (segmentation violation) on null values

### ISSUE THREAD

**Issue by waza-ari** [argoproj/argo-cd#10614]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

We're using Jsonnet to generate the code that is being applied by ArgoCD. When having a conditional entry in a list (see the conditional generation of `templates.private_repo`) below:

```
{
  resources(projects)::

    std.flattenArrays(
      [
        (
          [
            templates.namespace(project.name),
            if project.create_app then templates.private_repo(
              secret_name=project.repo_token
            ),
          ]
        )
        for project in projects
      ]
    ),
}
```

this generates (invalid) yaml code:

```
---
[removed for clarity]
  sourceRepos:
    - '*'
---
null
---
apiVersion: v1
kind: Namespace
metadata:
[removed for clarity]
---
```

Instead of giving an error, the argocd repository server crashes with segmentation violation (see logs below)

**To Reproduce**

Run some libsonnet code or simply yaml file with null entries

**Expected behavior**

ArgoCD should show an error, showing the sync to fail instead of crashing

**Version**

```shell
argocd: v2.4.3+471685f
  BuildDate: 2022-06-27T21:02:55Z
  GitCommit: 471685feae063c1c2e36a5ff268c4da87c697b85
  GitTreeState: clean
  GoVersion: go1.18.3
  Compiler: gc
  Platform: linux/amd64
```

**Logs**

```
time="2022-09-16T12:44:39Z" level=info msg="manifest cache miss: [...]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x265581b]
goroutine 137 [running]:
k8s.io/apimachinery/pkg/apis/meta/v1/unstructured.(*Unstructured).IsList(...)
/go/pkg/mod/k8s.io/apimachinery@v0.23.1/pkg/apis/meta/v1/unstructured/unstructured.go:55
github.com/argoproj/argo-cd/v2/reposerver/repository.GenerateManifests({0x449eb48, 0xc000b5ee10}, {0xc000b33a00, 0x3a}, {0xc0007722c0, 0x36}, {0xc000e6cd20, 0x28}, 0xc000393e60, 0x0, ...)
/go/src/github.com/argoproj/argo-cd/reposerver/repository/repository.go:933 +0x99b
github.com/argoproj/argo-cd/v2/reposerver/repository.(*Service).runManifestGenAsync(0xc00020c540, {0x449eb48, 0xc000b5ee10}, {0xc0007722c0, 0x36}, {0xc000e6cd20, 0x28}, {0xc000c63800, 0x28}, 0xc000e58240, ...)
/go/src/github.com/argoproj/argo-cd/reposerver/repository/repository.go:468 +0x2a5
created by github.com/argoproj/argo-cd/v2/reposerver/repository.(*Service).runManifestGen
/go/src/github.com/argoproj/argo-cd/reposerver/repository/repository.go:451 +0x2aa
```

**Workaround**

The issue can be worked around by stripping null values in the jsonnet code using `std.prune`:

```
{
  resources(projects)::

    std.flattenArrays(
      [
        (
          std.prune([
            templates.namespace(project.name),
            if project.create_app then templates.private_repo(
              secret_name=project.repo_token
            ),
          ]
        )
        for project in projects
      ])
    ),
}
```

**Comment by cleverhu** [comment]
I'd like to add null pointer judgment for this.
