### ISSUE TITLE
can't access applications pages

### ISSUE THREAD

**Issue by PengLingJun** [argoproj/argo-cd#11887]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

we are use latest image,version is v2.6.0+35fdd38,/applications path can't access,but,/applications/xxx,can access .

error log like that

**Version**

```shell
argocd-server: v2.6.0+35fdd38
  BuildDate: 2023-01-04T19:57:40Z
  GitCommit: 35fdd38d10937297f50db730b7ea362f12da6a48
  GitTreeState: clean
  GoVersion: go1.18.9
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v4.5.7 2022-08-02T16:35:54Z
  Helm Version: v3.10.3+g835b733
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.19.1
```

**Logs**

```
Something went wrong!

Consider submitting an issue [here](https://github.com/argoproj/argo-cd/issues/new?labels=bug&template=bug_report.md).


Stacktrace:

TypeError: i.getExternalUrls is not a function
    at https://xxxx/main.95a4ed526b4463a4ca6f.js:2:1927011
    at Array.map (<anonymous>)
    at Object.children (https://xxxx/main.95a4ed526b4463a4ca6f.js:2:1926336)
    at So.render (https://xxxxx/main.95a4ed526b4463a4ca6f.js:2:1503648)
    at Hs (https://xxxxx/main.95a4ed526b4463a4ca6f.js:2:819397)
    at js (https://xxxx/main.95a4ed526b4463a4ca6f.js:2:819192)
    at ya (https://xxxx/main.95a4ed526b4463a4ca6f.js:2:854673)
    at pl (https://xxxx/main.95a4ed526b4463a4ca6f.js:2:846148)
    at dl (https://xxxx/main.95a4ed526b4463a4ca6f.js:2:846073)
    at il (https://xxxx/main.95a4ed526b4463a4ca6f.js:2:843103)
```

**Comment by alexef** [comment]
Looks like a bad merge, I'll make a follow up PR to: https://github.com/argoproj/argo-cd/pull/11124
