### ISSUE TITLE
CompareAppState(): runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#1233]
v0.12.0-rc1 hit the following in CompareAppState(). I believe this is happening it is unable to get repository objects:

```
runtime error: invalid memory address or nil pointer dereference
goroutine 125 [running]:
runtime/debug.Stack(0xc002365080, 0x179b760, 0x2bc04f0)
    /usr/local/go/src/runtime/debug/stack.go:24 +0xa7
github.com/argoproj/argo-cd/controller.(*ApplicationController).processAppRefreshQueueItem.func1(0xc000642b40, 0x170e7a0, 0xc0059cbc20)
    /go/src/github.com/argoproj/argo-cd/controller/appcontroller.go:550 +0x8e
panic(0x179b760, 0x2bc04f0)
    /usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/argoproj/argo-cd/controller.(*appStateManager).CompareAppState(0xc000569d00, 0xc014c6a380, 0x0, 0x0, 0xc00e3dadc0, 0x39, 0x2be050e, 0x1, 0xc01708a86c, 0x4, ...)
    /go/src/github.com/argoproj/argo-cd/controller/state.go:281 +0x1c54
github.com/argoproj/argo-cd/controller.(*ApplicationController).processAppRefreshQueueItem(0xc000642b40, 0x1)
    /go/src/github.com/argoproj/argo-cd/controller/appcontroller.go:592 +0x4b1
github.com/argoproj/argo-cd/controller.(*ApplicationController).Run.func2()
    /go/src/github.com/argoproj/argo-cd/controller/appcontroller.go:257 +0x36
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc000457ed0)
    /go/src/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x54
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000457ed0, 0x3b9aca00, 0x0, 0x1, 0xc0000a0480)
    /go/src/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0xbe
k8s.io/apimachinery/pkg/util/wait.Until(0xc000457ed0, 0x3b9aca00, 0xc0000a0480)
    /go/src/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by github.com/argoproj/argo-cd/controller.(*ApplicationController).Run
    /go/src/github.com/argoproj/argo-cd/controller/appcontroller.go:256 +0x2f8
```

```golang
	compRes := comparisonResult{
		observedAt:       observedAt,
		syncStatus:       &syncStatus,
		healthStatus:     healthStatus,
		resources:        resourceSummaries,
		managedResources: managedResources,
		conditions:       conditions,
		hooks:            hooks,
		diffNormalizer:   diffNormalizer,
		appSourceType:    v1alpha1.ApplicationSourceType(manifestInfo.SourceType), // <<< panic
	}
```

**Comment by jessesuen** [comment]
Fixed
