### ISSUE TITLE
signal SIGSEGV: segmentation violation

### ISSUE THREAD

**Issue by 524c** [argoproj/argo-cd#12880]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**
After update argocd-server to version 2.6.5 I see this error when using the command line to sync an app, where the client is in a MacOS environment.

**To Reproduce**
// Request to sync an app using a 2.6.5 argocd-server
❯ argocd app sync app-nodejs --grpc-web --insecure

**Expected behavior**

**Screenshots**

**Version**

```shell
❯ argocd version
argocd: v2.6.0+acc554f
  BuildDate: 2023-02-06T21:36:52Z
  GitCommit: acc554f3d99010e0353b498a595844b30090556f
  GitTreeState: clean
  GoVersion: go1.18.10
  Compiler: gc
  Platform: darwin/amd64
WARN[0000] Failed to invoke grpc call. Use flag --grpc-web in grpc calls. To avoid this warning message, use flag --grpc-web.
argocd-server: v2.6.5+60104ac
  BuildDate: 2023-03-14T14:19:46Z
  GitCommit: 60104aca6faec73d10d57cb38245d47f4fb3146b
  GitTreeState: clean
  GoVersion: go1.18.10
  Compiler: gc
  Platform: linux/arm64
  Kustomize Version: v4.5.7 2022-08-02T16:35:54Z
  Helm Version: v3.10.3+g835b733
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.19.1
```

**Logs**
```
TIMESTAMP                  GROUP                            KIND   NAMESPACE                  NAME    STATUS   HEALTH        HOOK  MESSAGE
2023-03-15T17:01:04-03:00                              Namespace                             stage    Synced
2023-03-15T17:01:04-03:00                                Service       stage            app-nodejs    Synced  Healthy
2023-03-15T17:01:04-03:00   apps                      Deployment       stage            app-nodejs    Synced  Healthy
2023-03-15T17:01:04-03:00  gateway.networking.k8s.io   HTTPRoute       stage            app-nodejs    Synced
2023-03-15T17:01:08-03:00   apps                      Deployment       stage            app-nodejs    Synced  Healthy              deployment.apps/app-nodejs configured
2023-03-15T17:01:08-03:00  gateway.networking.k8s.io   HTTPRoute       stage            app-nodejs    Synced                       httproute.gateway.networking.k8s.io/app-nodejs configured
2023-03-15T17:01:08-03:00                              Namespace       stage                 stage   Running   Synced              namespace/stage unchanged
2023-03-15T17:01:08-03:00                                Service       stage            app-nodejs    Synced  Healthy              service/app-nodejs unchanged
2023-03-15T17:01:08-03:00   apps  Deployment       stage            app-nodejs  OutOfSync  Progressing              deployment.apps/app-nodejs configured
2023-03-15T17:01:10-03:00   apps  Deployment       stage            app-nodejs    Synced  Progressing              deployment.apps/app-nodejs configured

Name:               argocd/app-nodejs
Project:            default
Server:             https://kubernetes.default.svc
Namespace:          stage
URL:                https://argocd.test/applications/app-nodejs
Repo:               https://git.test/roger/tekton-argocd-infra
Target:             main
Path:               envs/stage/kustomize
SyncWindow:         Sync Allowed
Sync Policy:        Automated
Sync Status:        OutOfSync from main (1b9d2fd)
Health Status:      Healthy


2023-03-15T17:01:04-03:00  gateway.networking.k8s.io   HTTPRoute       stage            app-nodejs    Synced
2023-03-15T17:01:08-03:00   apps                      Deployment       stage            app-nodejs    Synced  Healthy              deployment.apps/app-nodejs configured
2023-03-15T17:01:08-03:00  gateway.networking.k8s.io   HTTPRoute       stage            app-nodejs    Synced                       httproute.gateway.networking.k8s.io/app-nodejs configured
2023-03-15T17:01:08-03:00                              Namespace       stage                 stage   Running   Synced              namespace/stage unchanged
2023-03-15T17:01:08-03:00                                Service       stage            app-nodejs    Synced  Healthy              service/app-nodejs unchanged
2023-03-15T17:01:08-03:00   apps  Deployment       stage            app-nodejs  OutOfSync  Progressing              deployment.apps/app-nodejs configured
2023-03-15T17:01:10-03:00   apps  Deployment       stage            app-nodejs    Synced  Progressing              deployment.apps/app-nodejs configured

Name:               argocd/app-nodejs
Project:            default
Server:             https://kubernetes.default.svc
Namespace:          stage
URL:                https://argocd.test/applications/app-nodejs
Repo:               https://git.test/roger/tekton-argocd-infra
Target:             main
Path:               envs/stage/kustomize
SyncWindow:         Sync Allowed
Sync Policy:        Automated
Sync Status:        OutOfSync from main (1b9d2fd)
Health Status:      Healthy


GROUP                      KIND        NAMESPACE  NAME        STATUS     HEALTH   HOOK  MESSAGE
                           Namespace              stage       Synced
                           Service     stage      app-nodejs  Synced     Healthy
apps                       Deployment  stage      app-nodejs  OutOfSync  Healthy
gateway.networking.k8s.io  HTTPRoute   stage      app-nodejs  Synced
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x38589b3]

goroutine 1 [running]:
github.com/argoproj/argo-cd/v2/cmd/argocd/commands.NewApplicationSyncCommand.func1(0xc000035500, {0xc0009c8870, 0x1, 0x3})
        /home/runner/work/argo-cd/argo-cd/cmd/argocd/commands/app.go:1717 +0x1c93
github.com/spf13/cobra.(*Command).execute(0xc000035500, {0xc0009c8810, 0x3, 0x3})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0xc000491b00)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
main.main()
        /home/runner/work/argo-cd/argo-cd/cmd/main.go:57 +0x2c5
```

My application
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-nodejs
  namespace: argocd
spec:
  destination:
    namespace: stage
    server: https://kubernetes.default.svc
  project: default
  revisionHistoryLimit: 3
  source:
    path: envs/stage/kustomize
    repoURL: https://git.test/roger/tekton-argocd-infra
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

```

**Comment by jannfis** [comment]
I see that you are using CLI v2.6.0 while using server version v2.6.5 - could you please verify if this panic also occurs when using CLI v2.6.5?

**Comment by 524c** [comment]
Hey @jannfis 

This is the worst case. The problem no longer occurs with the 2.6.0 client. I can no longer reproduce the error. If I find the pattern I'll report back here. Thanks!!

Result now without error: 
```sh
❯ argocd app sync app-nodejs --grpc-web --insecure

TIMESTAMP                  GROUP                            KIND   NAMESPACE                  NAME    STATUS   HEALTH        HOOK  MESSAGE
2023-03-15T21:16:55-03:00                              Namespace                             stage    Synced
2023-03-15T21:16:55-03:00                                Service       stage            app-nodejs    Synced  Healthy
2023-03-15T21:16:55-03:00   apps                      Deployment       stage            app-nodejs    Synced  Healthy
2023-03-15T21:16:55-03:00  gateway.networking.k8s.io   HTTPRoute       stage            app-nodejs    Synced
2023-03-15T21:16:57-03:00                              Namespace       stage                 stage   Running   Synced              namespace/stage unchanged
2023-03-15T21:16:57-03:00                                Service       stage            app-nodejs    Synced  Healthy              service/app-nodejs unchanged
2023-03-15T21:16:57-03:00   apps                      Deployment       stage            app-nodejs    Synced  Healthy              deployment.apps/app-nodejs configured
2023-03-15T21:16:57-03:00  gateway.networking.k8s.io   HTTPRoute       stage            app-nodejs    Synced                       httproute.gateway.networking.k8s.io/app-nodejs
configured

Name:               argocd/app-nodejs
Project:            default
Server:             https://kubernetes.default.svc
Namespace:          stage
URL:                https://argocd.test/applications/app-nodejs
Repo:               https://git.test/roger/tekton-argocd-infra
Target:             HEAD
Path:               envs/stage/kustomize
SyncWindow:         Sync Allowed
Sync Policy:        Automated (Prune)
Sync Status:        Synced to HEAD (1dd671f)
Health Status:      Healthy

Operation:          Sync
Sync Revision:      1dd671fc0145d0709f28fd00996c2cdbefd9cc21
Phase:              Succeeded
Start:              2023-03-15 21:16:57 -0300 -03
Finished:           2023-03-15 21:16:58 -0300 -03
Duration:           1s
Message:            successfully synced (all tasks run)

GROUP                      KIND        NAMESPACE  NAME        STATUS   HEALTH   HOOK  MESSAGE
                           Namespace   stage      stage       Running  Synced         namespace/stage unchanged
                           Service     stage      app-nodejs  Synced   Healthy        service/app-nodejs unchanged
apps                       Deployment  stage      app-nodejs  Synced   Healthy        deployment.apps/app-nodejs configured
gateway.networking.k8s.io  HTTPRoute   stage      app-nodejs  Synced                  httproute.gateway.networking.k8s.io/app-nodejs configured
                           Namespace              stage       Synced
```

**Comment by 524c** [comment]
Perhaps the only thing different is the `stage   Running`.
I will try more and get back to you soon.

**Comment by fredleger** [comment]
versions affected seems to be 2.6.0+

**Comment by VladDubrovskis** [comment]
We have encountered same issue with versions 2.6.2 (server + client) running on Linux in CI

**Comment by jgwest** [comment]
Closing as the original issue related to `argocd app sync` appears resolved. For any other commands, please open a separate issue, as these are likely to have entirely separate causes.
