### ISSUE TITLE
UI: TypeError: Cannot read properties of undefined (reading 'podGroup')

### ISSUE THREAD

**Issue by duizabojul** [argoproj/argo-cd#13416]
**Describe the bug**

When I try to group nodes on argo UI I got this error

**To Reproduce**

It is not clear how to reproduce given this bug happens only on one of our application.

**Version**

```json
{
    "Version": "v2.7.0+c592219.dirty",
    "BuildDate": "2023-05-02T00:14:18Z",
    "GitCommit": "c592219140e5f48b6849f3f9a8f7aed6047d54fa",
    "GitTreeState": "dirty",
    "GoVersion": "go1.19.6",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v5.0.1 2023-03-14T01:32:48Z",
    "HelmVersion": "v3.11.2+g912ebc1",
    "KubectlVersion": "v0.24.2",
    "JsonnetVersion": "v0.19.1"
}
```

**Logs**

```shell
Stacktrace:

TypeError: Cannot read properties of undefined (reading 'podGroup')
    at https://xxx.yyyy/main.a726808c41da12ea7cc9.js:2:1746007
    at Array.forEach (<anonymous>)
    at https:/xxx.yyyy/main.a726808c41da12ea7cc9.js:2:1745937
    at Array.forEach (<anonymous>)
    at https://xxx.yyyy/main.a726808c41da12ea7cc9.js:2:1745874
    at $m (https://xxx.yyyy/main.a726808c41da12ea7cc9.js:2:1746336)
    at Jr (https://xxx.yyyy/main.a726808c41da12ea7cc9.js:2:808335)
    at Bs (https://xxx.yyyy/main.a726808c41da12ea7cc9.js:2:817184)
    at ya (https://xxx.yyyy/main.a726808c41da12ea7cc9.js:2:855459)
    at pl (https://xxx.yyyy/main.a726808c41da12ea7cc9.js:2:847016)
```

This leads to this line https://github.com/argoproj/argo-cd/blob/064c8da942c56bf45745d7bc1b9af8ded979aa61/ui/src/app/applications/components/application-resource-tree/application-resource-tree.tsx#L182

**Comment by ashutosh16** [comment]
I tested in my local against v2.7.0  however I don't see the error in the console log. I have 15 pods which I was able to group successfully on the UI. Would you mind provide the  screenshot/clip?
![Screenshot 2023-05-02 at 11 57 53 AM](https://user-images.githubusercontent.com/11219262/235759983-28447f8b-33e9-47e3-9201-2c565ca4c49a.png)

**Comment by duizabojul** [comment]
https://user-images.githubusercontent.com/7392946/235885373-49e774c1-f77a-48b9-a2a2-3d513f387f4e.mov

**Comment by vet4ka** [comment]
I also have this issue.
I have app with 341 resources

Version

```
{
    "Version": "v2.7.2+cbee7e6.dirty",
    "BuildDate": "2023-05-12T13:43:26Z",
    "GitCommit": "cbee7e6011407ed2d1066c482db74e97e0cc6bdb",
    "GitTreeState": "dirty",
    "GoVersion": "go1.19.6",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v5.0.1 2023-03-14T01:32:48Z",
    "HelmVersion": "v3.11.2+g912ebc1",
    "KubectlVersion": "v0.24.2",
    "JsonnetVersion": "v0.19.1"
}
```

Error in Chrome Console:

```
TypeError: Cannot read properties of undefined (reading 'podGroup')
    at main.6d68d77ebcfffd06ce4d.js:2:1746007
    at Array.forEach (<anonymous>)
    at main.6d68d77ebcfffd06ce4d.js:2:1745937
    at Array.forEach (<anonymous>)
    at main.6d68d77ebcfffd06ce4d.js:2:1745874
    at $m (main.6d68d77ebcfffd06ce4d.js:2:1746336)
    at Jr (main.6d68d77ebcfffd06ce4d.js:2:808335)
    at Bs (main.6d68d77ebcfffd06ce4d.js:2:817184)
    at ya (main.6d68d77ebcfffd06ce4d.js:2:855459)
    at pl (main.6d68d77ebcfffd06ce4d.js:2:847016)
```

**Comment by brsolomon-deloitte** [comment]
This is popping up all over the place on ArgoCD 2.6.7. It seems to happen randomly when clicking on different application resources without rhyme or reason.

```
Stacktrace:

TypeError: Cannot read properties of undefined (reading 'name')
    at vd (https://argocd.<redacted>/main.c87b5e37f99fc2a30256.js:2:1630354)
    at p (https://argocd.<redacted>/main.c87b5e37f99fc2a30256.js:2:1855881)
    at Object.children (https://argocd.<redacted>/main.c87b5e37f99fc2a30256.js:2:1859873)
    at Co.render (https://argocd.<redacted>/main.c87b5e37f99fc2a30256.js:2:1503200)
    at Hs (https://argocd.<redacted>/main.c87b5e37f99fc2a30256.js:2:819397)
    at js (https://argocd.<redacted>/main.c87b5e37f99fc2a30256.js:2:819192)
    at ya (https://argocd.<redacted>/main.c87b5e37f99fc2a30256.js:2:854673)
    at pl (https://argocd.<redacted>/main.c87b5e37f99fc2a30256.js:2:846148)
    at dl (https://argocd.<redacted>/main.c87b5e37f99fc2a30256.js:2:846073)
    at il (https://argocd.<redacted>/main.c87b5e37f99fc2a30256.js:2:843103)
```

**Comment by duizabojul** [comment]
> This is popping up all over the place on ArgoCD 2.6.7. It seems to happen randomly when clicking on different application resources without rhyme or reason.
> 
> 
> 
> ```
> 
> Stacktrace:
> 
> 
> 
> TypeError: Cannot read properties of undefined (reading 'name')
> 
>     at vd (https://argocd.<redacted>/main.c87b5e37f99fc2a30256.js:2:1630354)
> 
>     at p (https://argocd.<redacted>/main.c87b5e37f99fc2a30256.js:2:1855881)
> 
>     at Object.children (https://argocd.<redacted>/main.c87b5e37f99fc2a30256.js:2:1859873)
> 
>     at Co.render (https://argocd.<redacted>/main.c87b5e37f99fc2a30256.js:2:1503200)
> 
>     at Hs (https://argocd.<redacted>/main.c87b5e37f99fc2a30256.js:2:819397)
> 
>     at js (https://argocd.<redacted>/main.c87b5e37f99fc2a30256.js:2:819192)
> 
>     at ya (https://argocd.<redacted>/main.c87b5e37f99fc2a30256.js:2:854673)
> 
>     at pl (https://argocd.<redacted>/main.c87b5e37f99fc2a30256.js:2:846148)
> 
>     at dl (https://argocd.<redacted>/main.c87b5e37f99fc2a30256.js:2:846073)
> 
>     at il (https://argocd.<redacted>/main.c87b5e37f99fc2a30256.js:2:843103)
> 
> ```

This is not related to this issue I think.

**Comment by thealgirdas** [comment]
Same here on `2.7.3`:
```
Stacktrace:

TypeError: Cannot read properties of undefined (reading 'podGroup')
    at https://<redacted-domain>/main.4c7fc665b39044302151.js:2:1746007
    at Array.forEach (<anonymous>)
    at https://<redacted-domain>/main.4c7fc665b39044302151.js:2:1745937
    at Array.forEach (<anonymous>)
    at https://<redacted-domain>/main.4c7fc665b39044302151.js:2:1745874
    at $m (https://<redacted-domain>/main.4c7fc665b39044302151.js:2:1746336)
    at Jr (https://<redacted-domain>/main.4c7fc665b39044302151.js:2:808335)
    at Bs (https://<redacted-domain>/main.4c7fc665b39044302151.js:2:817184)
    at ya (https://<redacted-domain>/main.4c7fc665b39044302151.js:2:855459)
    at pl (https://<redacted-domain>/main.4c7fc665b39044302151.js:2:847016)
```

**Comment by alex-dixon** [comment]
I think it just needs an extra null check. Trying to find where in the code this is.

Switching out of "group nodes" fixes it for me also but group nodes is such a nice feature :)
