### ISSUE TITLE
Unable to read logs from multi-container Pods (2.7.1)

### ISSUE THREAD

**Issue by rgdev** [argoproj/argo-cd#13524]
Checklist:

* [ X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X ] I've included steps to reproduce the bug.
* [ X] I've pasted the output of `argocd version`.

**Describe the bug**

In the UI, when accessing the logs tab of a Pod containing multiple containers (here Linkerd sidecar) I can't switch to another container in the list. Only the first container can display logs. This affects every single Pod with multiple containers, no issue with single container Pods. It seems to be a JS issue in the frontend as no call is made to backend and a JS error is logged in the console.

I updated my instance to the latest version (2.7.1) and this issue started to appear. It didn't occur on the previous installed version (2.6.1).

**To Reproduce**

Nothing special, just try to display logs of a multi-container Pod in the web UI.

**Expected behavior**

The UI should call the logs endpoint and display the logs everytime the selected container changes in the UI's dropdown.

**Screenshots**

https://github.com/argoproj/argo-cd/assets/2675421/9aca77d9-710f-4a62-b29e-76e3049f0513

**Version**

```json
{
    "Version": "v2.7.1+5e54351.dirty",
    "BuildDate": "2023-05-02T16:35:40Z",
    "GitCommit": "5e543518dbdb5384fa61c938ce3e045b4c5be325",
    "GitTreeState": "dirty",
    "GoVersion": "go1.19.6",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v5.0.1 2023-03-14T01:32:48Z",
    "HelmVersion": "v3.11.2+g912ebc1",
    "KubectlVersion": "v0.24.2",
    "JsonnetVersion": "v0.19.1"
}
```

**Logs**

Error logged in the chrome console :

```
main.a726808c41da12ea7cc9.js:2 Uncaught TypeError: Cannot read properties of undefined (reading 'containers')
    at onChange (main.a726808c41da12ea7cc9.js:2:1878655)
    at Object.a (main.a726808c41da12ea7cc9.js:2:750751)
    at p (main.a726808c41da12ea7cc9.js:2:750894)
    at main.a726808c41da12ea7cc9.js:2:751040
    at _ (main.a726808c41da12ea7cc9.js:2:751126)
    at rt (main.a726808c41da12ea7cc9.js:2:766594)
    at it (main.a726808c41da12ea7cc9.js:2:766404)
    at st (main.a726808c41da12ea7cc9.js:2:766760)
    at ht (main.a726808c41da12ea7cc9.js:2:767967)
    at F (main.a726808c41da12ea7cc9.js:2:864554)
```

**Comment by rgdev** [comment]
It seems to be a duplicate of https://github.com/argoproj/argo-cd/issues/13410
Sorry about that.
