### ISSUE TITLE
Can't open logs

### ISSUE THREAD

**Issue by nicl-dev** [argoproj/argo-cd#13684]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I want to open a log for a `ReplicaSet` or `Pod` from a Prometheus-Stack Helm-Chart deployment, and it crashes (see screenshot). It is only happening on a couple of resources, not every `Pod` or `ReplicaSet`.

**To Reproduce**

Open Resource, click on `Logs`.

**Expected behavior**

I would like to see the resource logs.

**Screenshots**

![image](https://github.com/argoproj/argo-cd/assets/75254846/854ac1b8-b0f8-4240-851b-a91ecfb2dacb)

**Version**

```shell
argocd: v2.6.7+5bcd846.dirty
  BuildDate: 2023-03-23T17:23:10Z
  GitCommit: 5bcd846fa16e4b19d8f477de7da50ec0aef320e5
  GitTreeState: dirty
  GoVersion: go1.20.2
  Compiler: gc
  Platform: darwin/arm64
```

**Logs**

```
Something went wrong!

Consider submitting an issue [here](https://github.com/argoproj/argo-cd/issues/new?labels=bug&template=bug_report.md).


Stacktrace:

TypeError: Reduce of empty array with no initial value
    at Array.reduce (<anonymous>)
    at Object.children (https://localhost:8086/main.a726808c41da12ea7cc9.js:2:1885533)
    at Ji.render (https://localhost:8086/main.a726808c41da12ea7cc9.js:2:1550799)
    at Hs (https://localhost:8086/main.a726808c41da12ea7cc9.js:2:820265)
    at js (https://localhost:8086/main.a726808c41da12ea7cc9.js:2:820060)
    at ya (https://localhost:8086/main.a726808c41da12ea7cc9.js:2:855541)
    at pl (https://localhost:8086/main.a726808c41da12ea7cc9.js:2:847016)
    at ul (https://localhost:8086/main.a726808c41da12ea7cc9.js:2:846941)
    at il (https://localhost:8086/main.a726808c41da12ea7cc9.js:2:843971)
    at https://localhost:8086/main.a726808c41da12ea7cc9.js:2:795750
```

**Comment by alexmt** [comment]
Thanks for reporting ! Issue was fixed by https://github.com/argoproj/argo-cd/pull/13620 and will be available in next patch release in a day or two
