### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by rembun** [argoproj/argo-cd#13713]
Stacktrace:

TypeError: Reduce of empty array with no initial value
    at Array.reduce (<anonymous>)
    at Object.children (https://172.20.0.10:30900/main.6d68d77ebcfffd06ce4d.js:2:1885613)
    at Ji.render (https://172.20.0.10:30900/main.6d68d77ebcfffd06ce4d.js:2:1550799)
    at Hs (https://172.20.0.10:30900/main.6d68d77ebcfffd06ce4d.js:2:820265)
    at js (https://172.20.0.10:30900/main.6d68d77ebcfffd06ce4d.js:2:820060)
    at ya (https://172.20.0.10:30900/main.6d68d77ebcfffd06ce4d.js:2:855541)
    at pl (https://172.20.0.10:30900/main.6d68d77ebcfffd06ce4d.js:2:847016)
    at ul (https://172.20.0.10:30900/main.6d68d77ebcfffd06ce4d.js:2:846941)
    at il (https://172.20.0.10:30900/main.6d68d77ebcfffd06ce4d.js:2:843971)
    at https://172.20.0.10:30900/main.6d68d77ebcfffd06ce4d.js:2:795750

**Comment by alexmt** [comment]
Thanks for reporting :) Issue is fixed by https://github.com/argoproj/argo-cd/pull/13620 . Patch release is supposed to be pushed in ~ 30 mins
