### ISSUE TITLE
FE crashed with "Something went wrong!"

### ISSUE THREAD

**Issue by n9** [argoproj/argo-cd#13856]
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

Printed on the web page:

```
Something went wrong!

Consider submitting an issue here.


Stacktrace:

TypeError: Cannot read properties of undefined (reading 'name')
    at jc (https://argocd/main.09d057f3ca5d57f02d1e.js:2:1664363)
    at u (https://argocd/main.09d057f3ca5d57f02d1e.js:2:1899209)
    at Object.children (https://argocd/main.09d057f3ca5d57f02d1e.js:2:1903046)
    at Vi.render (https://argocd/main.09d057f3ca5d57f02d1e.js:2:1550677)
    at Ws (https://argocd/main.09d057f3ca5d57f02d1e.js:2:820278)
    at zs (https://argocd/main.09d057f3ca5d57f02d1e.js:2:820073)
    at Sa (https://argocd/main.09d057f3ca5d57f02d1e.js:2:855697)
    at xl (https://argocd/main.09d057f3ca5d57f02d1e.js:2:847156)
    at Cl (https://argocd/main.09d057f3ca5d57f02d1e.js:2:847081)
    at fl (https://argocd/main.09d057f3ca5d57f02d1e.js:2:844104)
```

URL: https://argocd/applications/argocd/some-app?view=tree&orphaned=false&resource=&node=%2FPod%2Fsome-app%2Fsome-pod%2F0

**To Reproduce**

I cannot reproduce. But regular usage.

**Expected behavior**

No such output.

**Version**

```shell
~master
```

**Logs**

N/A

**Comment by corneliusroemer** [comment]
Getting this in argo 2.11.3:

```
Something went wrong!

Consider submitting an issue [here](https://github.com/argoproj/argo-cd/issues/new?labels=bug&template=bug_report.md).


Stacktrace:

TypeError: Cannot read properties of undefined (reading 'name')
    at Xc (https://argocd.loculus.org/main.b57fa04f99a7b0f77b89.js:2:1578371)
    at d (https://argocd.loculus.org/main.b57fa04f99a7b0f77b89.js:2:1816099)
    at Object.children (https://argocd.loculus.org/main.b57fa04f99a7b0f77b89.js:2:1819941)
    at Br.render (https://argocd.loculus.org/main.b57fa04f99a7b0f77b89.js:2:1461095)
    at zi (https://argocd.loculus.org/main.b57fa04f99a7b0f77b89.js:2:768767)
    at Hi (https://argocd.loculus.org/main.b57fa04f99a7b0f77b89.js:2:768562)
    at Es (https://argocd.loculus.org/main.b57fa04f99a7b0f77b89.js:2:804186)
    at kl (https://argocd.loculus.org/main.b57fa04f99a7b0f77b89.js:2:795645)
    at xl (https://argocd.loculus.org/main.b57fa04f99a7b0f77b89.js:2:795570)
    at hl (https://argocd.loculus.org/main.b57fa04f99a7b0f77b89.js:2:792593)
```
