### ISSUE TITLE
argocd cli segfault if ignoreDifferences is set

### ISSUE THREAD

**Issue by stevendborrelli** [argoproj/argo-cd#1389]
If you omit the `Group:` in an ignoreDifferences setting, the argocd cli will segfault. 

```
  ignoreDifferences:
  - kind: Secret
    jsonPointers:
    - /data/token
```

```
$ argocd app diff control-vault-crd
panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 1 [running]:
github.com/argoproj/argo-cd/util/diff.NormalizeSecret(0xc000158210)
	/go/src/github.com/argoproj/argo-cd/util/diff/diff.go:308 +0x637
github.com/argoproj/argo-cd/util/diff.Normalize(0xc000158210, 0x2719680, 0xc00063c4c0)
	/go/src/github.com/argoproj/argo-cd/util/diff/diff.go:266 +0x1b7
github.com/argoproj/argo-cd/util/diff.Diff(0xc000158210, 0xc0003d22a0, 0x2719680, 0xc00063c4c0, 0x2719680)
	/go/src/github.com/argoproj/argo-cd/util/diff/diff.go:40 +0x1c6
github.com/argoproj/argo-cd/cmd/argocd/commands.NewApplicationDiffCommand.func1(0xc000016900, 0xc000453520, 0x1, 0x1)
	/go/src/github.com/argoproj/argo-cd/cmd/argocd/commands/app.go:759 +0xadc
github.com/spf13/cobra.(*Command).execute(0xc000016900, 0xc0004534e0, 0x1, 0x1, 0xc000016900, 0xc0004534e0)
	/go/src/github.com/spf13/cobra/command.go:702 +0x2d3
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001efd40, 0xc0004ec000, 0xc0000b7b30, 0xc0003e5a40)
	/go/src/github.com/spf13/cobra/command.go:783 +0x2dc
github.com/spf13/cobra.(*Command).Execute(0xc0001efd40, 0xc000539f88, 0xc0000460b8)
	/go/src/github.com/spf13/cobra/command.go:736 +0x2b
main.main()
	/go/src/github.com/argoproj/argo-cd/cmd/argocd/main.go:14 +0x27
```

```
argocd: v0.12.0+cd4bb25
  BuildDate: 2019-03-22T19:59:10Z
  GitCommit: cd4bb2553d4d3b9a8ba808adbd65c15ce11d9cfa
  GitTreeState: clean
  GoVersion: go1.11.4
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v0.12.0+cd4bb25
  BuildDate: 2019-03-22T19:58:47Z
  GitCommit: cd4bb2553d4d3b9a8ba808adbd65c15ce11d9cfa
  GitTreeState: clean
  GoVersion: go1.11.4
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: 0.13.1
```

**Comment by stevendborrelli** [comment]
On further testing, if I omit the secret key it will not segfault:
```
  ignoreDifferences:
  - kind: Secret
    jsonPointers:
    - /data
```

**Comment by alexec** [comment]
```go
		err = unstructured.SetNestedMap(un.Object, newObj["data"].(map[string]interface{}), "data")
		if err != nil {
			log.Warnf("failed to set secret.data: %v", err)
			return
		}
	}
```

**Comment by alexec** [comment]
@stevendborrelli I've not been able to repo this. Are you able to provide a complete example of the application manifests you are diffing so I can load them into my system?

**Comment by alexmt** [comment]
Found how to reproduce it. The error happens if all secret fields are ignored. Here is the fix https://github.com/argoproj/argo-cd/pull/1443
