### ISSUE TITLE
Something went wrong!  Consider submitting an issue here.   Stacktrace:  TypeError: Reduce of empty array with no initial value     at Array.reduce (<anonymous>)     at Object.children (https://192.168.10.81/main.6d68d77ebcfffd06ce4d.js:2:1885613)     at Ji.render (https://192.168.10.81/main.6d68d77ebcfffd06ce4d.js:2:1550799)     at Hs (https://192.168.10.81/main.6d68d77ebcfffd06ce4d.js:2:820265)     at js (https://192.168.10.81/main.6d68d77ebcfffd06ce4d.js:2:820060)     at ya (https://192.168.10.81/main.6d68d77ebcfffd06ce4d.js:2:855541)     at pl (https://192.168.10.81/main.6d68d77ebcfffd06ce4d.js:2:847016)     at ul (https://192.168.10.81/main.6d68d77ebcfffd06ce4d.js:2:846941)     at il (https://192.168.10.81/main.6d68d77ebcfffd06ce4d.js:2:843971)     at https://192.168.10.81/main.6d68d77ebcfffd06ce4d.js:2:795750

### ISSUE THREAD

**Issue by elhakoyan** [argoproj/argo-cd#14075]
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version**

```shell
Paste the output from `argocd version` here.
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by alexmt** [comment]
Issue was fixed and available in v2.7.4. Please let us know if you still see issue in v2.7.4
