### ISSUE TITLE
javascript crash on loading specific app

### ISSUE THREAD

**Issue by jalavoy** [argoproj/argo-cd#14293]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When opening a specific app on my cluster, I get the following error:
```
Something went wrong!

Consider submitting an issue here.


Stacktrace:

TypeError: Cannot read properties of undefined (reading 'podGroup')
    at https://argocd.aws.REDACTED.com/main.fed2c14970cfe1cab3d4.js:2:1771275
    at Array.forEach (<anonymous>)
    at https://argocd.aws.REDACTED.com/main.fed2c14970cfe1cab3d4.js:2:1771205
    at Array.forEach (<anonymous>)
    at https://argocd.aws.REDACTED.com/main.fed2c14970cfe1cab3d4.js:2:1771142
    at Ym (https://argocd.aws.REDACTED.com/main.fed2c14970cfe1cab3d4.js:2:1771604)
    at Za (https://argocd.aws.REDACTED.com/main.fed2c14970cfe1cab3d4.js:2:808354)
    at Bi (https://argocd.aws.REDACTED.com/main.fed2c14970cfe1cab3d4.js:2:817201)
    at Es (https://argocd.aws.REDACTED.com/main.fed2c14970cfe1cab3d4.js:2:855619)
    at Sl (https://argocd.aws.REDACTED.com/main.fed2c14970cfe1cab3d4.js:2:847160)
```

**To Reproduce**

Login to the GUI, scroll to the app in question, click on it.

**Expected behavior**

The page loads, as all the other apps do.

**Screenshots**

![image](https://github.com/argoproj/argo-cd/assets/2285876/c512a32b-42c6-444d-a408-9da6c65c3f02)

**Version**

```shell
argocd: v2.8.0+40e26fc
  BuildDate: 2023-06-27T16:25:38Z
  GitCommit: 40e26fcfd1a8a8581eb1029b1f112a53443d6f94
  GitTreeState: clean
  GoVersion: go1.20.5
  Compiler: gc
  Platform: linux/amd64
```

**Logs**

```
time="2023-06-30T16:04:05Z" level=info msg="received unary call /version.VersionService/Version" grpc.method=Version grpc.request.content= grpc.service=version.VersionService grpc.start_time="2023-06-30T16:04:05Z" span.kind=server system=grpc
time="2023-06-30T16:04:05Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=Version grpc.service=version.VersionService grpc.start_time="2023-06-30T16:04:05Z" grpc.time_ms=10.127 span.kind=server system=grpc
time="2023-06-30T16:04:05Z" level=info msg="received unary call /version.VersionService/Version" grpc.method=Version grpc.request.content= grpc.service=version.VersionService grpc.start_time="2023-06-30T16:04:05Z" span.kind=server system=grpc
time="2023-06-30T16:04:05Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=Version grpc.service=version.VersionService grpc.start_time="2023-06-30T16:04:05Z" grpc.time_ms=9.885 span.kind=server system=grpc
time="2023-06-30T16:04:05Z" level=info msg="received unary call /application.ApplicationService/Get" grpc.method=Get grpc.request.content="name:\"gitlab\" appNamespace:\"argocd\" " grpc.service=application.ApplicationService grpc.start_time="2023-06-30T16:04:05Z" span.kind=server system=grpc
time="2023-06-30T16:04:05Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=Get grpc.service=application.ApplicationService grpc.start_time="2023-06-30T16:04:05Z" grpc.time_ms=17.837 span.kind=server system=grpc
time="2023-06-30T16:04:05Z" level=info msg="received unary call /session.SessionService/GetUserInfo" grpc.method=GetUserInfo grpc.request.content= grpc.service=session.SessionService grpc.start_time="2023-06-30T16:04:05Z" span.kind=server system=grpc
time="2023-06-30T16:04:05Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=GetUserInfo grpc.service=session.SessionService grpc.start_time="2023-06-30T16:04:05Z" grpc.time_ms=5.285 span.kind=server system=grpc
time="2023-06-30T16:04:05Z" level=info msg="received unary call /application.ApplicationService/GetApplicationSyncWindows" grpc.method=GetApplicationSyncWindows grpc.request.content="name:\"gitlab\" appNamespace:\"argocd\" " grpc.service=application.ApplicationService grpc.start_time="2023-06-30T16:04:05Z" span.kind=server system=grpc
time="2023-06-30T16:04:05Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=GetApplicationSyncWindows grpc.service=application.ApplicationService grpc.start_time="2023-06-30T16:04:05Z" grpc.time_ms=18.623 span.kind=server system=grpc
time="2023-06-30T16:04:06Z" level=info msg="received streaming call /application.ApplicationService/WatchResourceTree" grpc.method=WatchResourceTree grpc.request.content="applicationName:\"gitlab\" appNamespace:\"argocd\" " grpc.service=application.ApplicationService grpc.start_time="2023-06-30T16:04:06Z" span.kind=server system=grpc
time="2023-06-30T16:04:06Z" level=info msg="finished streaming call with code OK" grpc.code=OK grpc.method=WatchResourceTree grpc.service=application.ApplicationService grpc.start_time="2023-06-30T16:04:06Z" grpc.time_ms=91.357 span.kind=server system=grpc
```

I did a little bit of debugging on the loop in question and found that it crashes when `n = 91c2d3ac-a95a-4be0-9ecb-83ecdbd55eb1`, which is the ID of one of the PVC's related to this deployment.

```
$ k get pvc -n gitlab |grep 91c2
repo-data-gitlab-gitaly-praefect-0   Bound    pvc-91c2d3ac-a95a-4be0-9ecb-83ecdbd55eb1   50Gi       RWO            ebs            30h
```

That said, I don't understand the error beyond that. 

Here is the definition of the pvc in question:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: ebs.csi.aws.com
    volume.kubernetes.io/storage-provisioner: ebs.csi.aws.com
  creationTimestamp: "2023-06-26T15:55:56Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: gitaly
    release: gitlab
    storage: praefect
  name: repo-data-gitlab-gitaly-praefect-0
  namespace: gitlab
  resourceVersion: "405764881"
  uid: 91c2d3ac-a95a-4be0-9ecb-83ecdbd55eb1
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: ebs
  volumeMode: Filesystem
  volumeName: pvc-91c2d3ac-a95a-4be0-9ecb-83ecdbd55eb1
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 50Gi
  phase: Bound
```

Since this is a praefect pvc, and I have two of them, would it be safe to nuke this PVC and let it get recreated without any dataloss? Is there something else I should try?

**Comment by Keegan-Bantom** [comment]
i'm getting the exact same message, have you by chance managed to find a fix for this?

**Comment by jalavoy** [comment]
> i'm getting the exact same message, have you by chance managed to find a fix for this?

Nope. I’ve exhausted my troubleshooting abilities on this one.

**Comment by Keegan-Bantom** [comment]
I eventually rolled back to v2.7.3 which works for me

**Comment by dlydiard** [comment]
i'm getting the same error in openshift gitops

**Comment by druchoo** [comment]
In my case, the error occurs for a Crossplane Application that has no pods. Viewing another Application and disabling **_Group Nodes_** allows viewing the Crossplane App without error.

<img width="425" alt="image" src="https://github.com/argoproj/argo-cd/assets/2237523/559ffe22-3ff7-4b7d-bb08-6a94460bf5e3">

**Comment by jalavoy** [comment]
> I eventually rolled back to v2.7.3 which works for me
confirmed rolling back to 2.7 fixes this.

**Comment by rodrigc** [comment]
Seems similar to https://github.com/argoproj/argo-cd/issues/14572

**Comment by jgwest** [comment]
Duping to https://github.com/argoproj/argo-cd/issues/13416
