### ISSUE TITLE
UI stopps working after installing an app with the official Harbor chart

### ISSUE THREAD

**Issue by vasiliy-grinko** [argoproj/argo-cd#15410]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Argocd UI stopes working after installing an application with [this chart](https://goharbor.io/docs/2.9.0/install-config/harbor-ha-helm/ ) and this error is shown. I've tried to to reinstall argocd but it didn't help. 
The interesting thing is that it was working for a several hours after installation of this app, but then just stopped.
I also have 11 installed applications and everything is working fine with them.

**To Reproduce**

Install [this chart](https://goharbor.io/docs/2.9.0/install-config/harbor-ha-helm/ ) via ArgoCD application without specifying any values.

**Expected behavior**

UI works correctly.

**Screenshots**
Just after installing Harbor app I'm getting this:
![image](https://github.com/argoproj/argo-cd/assets/65661924/34850252-a106-4342-b6a4-47a33feee50d)
after ~1min I get this:
![image](https://github.com/argoproj/argo-cd/assets/65661924/aa3fa380-07ce-4998-a9c6-c33e2f9e5b34)

**Version**

```shell
argocd: v2.8.2+dbdfc71
  BuildDate: 2023-08-24T20:05:39Z
  GitCommit: dbdfc712702ce2f781910a795d2e5385a4f5a0f9
  GitTreeState: clean
  GoVersion: go1.20.6
  Compiler: gc
  Platform: linux/amd64
```

**Logs**

```
Stacktrace:

TypeError: Cannot read properties of null (reading 'Version')
    at tA.buildVersionTable (https://argocd.bart.team/main.13ef585f1cf91287f8dc.js:2:2145283)
    at Object.children (https://argocd.bart.team/main.13ef585f1cf91287f8dc.js:2:2145101)
    at Fr.render (https://argocd.bart.team/main.13ef585f1cf91287f8dc.js:2:1565823)
    at zi (https://argocd.bart.team/main.13ef585f1cf91287f8dc.js:2:820282)
    at Hi (https://argocd.bart.team/main.13ef585f1cf91287f8dc.js:2:820077)
    at Es (https://argocd.bart.team/main.13ef585f1cf91287f8dc.js:2:855701)
    at Sl (https://argocd.bart.team/main.13ef585f1cf91287f8dc.js:2:847160)
    at xl (https://argocd.bart.team/main.13ef585f1cf91287f8dc.js:2:847085)
    at hl (https://argocd.bart.team/main.13ef585f1cf91287f8dc.js:2:844108)
    at https://argocd.bart.team/main.13ef585f1cf91287f8dc.js:2:795769
```

**Comment by vasiliy-grinko** [comment]
UPD: 
the error resolved by itself after another resintallation of an app with Harbor chart
