### ISSUE TITLE
notifications-controller 'runtime error: index out of range'

### ISSUE THREAD

**Issue by kforsthoevel** [argoproj/argo-cd#15484]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

I see a lot of these error messages in logs of the `notifications-controller`:

```
Recovered from panic: runtime error: index out of range [1] with length 1
goroutine 150 [running]:runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
github.com/argoproj/notifications-engine/pkg/controller.(*notificationController).processQueueItem.func1()
	/go/pkg/mod/github.com/argoproj/notifications-engine@v0.4.1-0.20230620204159-3446d4ae8520/pkg/controller/controller.go:258 +0x65
panic({0x3788a80, 0xc001a8dfb0})
	/usr/local/go/src/runtime/panic.go:890 +0x263
github.com/argoproj/notifications-engine/pkg/services.gitHubService.Send({{{0x32113a0, 0xc001bb4758}, {0x32113a0, 0xc001bb4768}, {0xc001c39100, 0x68a}, {0x0, 0x0}}, 0xc000b28000}, {{0xc001b63c18, ...}, ...}, ...)
	/go/pkg/mod/github.com/argoproj/notifications-engine@v0.4.1-0.20230620204159-3446d4ae8520/pkg/services/github.go:280 +0x6c9
github.com/argoproj/notifications-engine/pkg/api.(*api).Send(0xc002336880, 0x1f?, {0xc001507080, 0x1, 0x4}, {{0xc001eaca36?, 0x4?}, {0x0?, 0x0?}})
	/go/pkg/mod/github.com/argoproj/notifications-engine@v0.4.1-0.20230620204159-3446d4ae8520/pkg/api/api.go:71 +0x45e
github.com/argoproj/notifications-engine/pkg/controller.(*notificationController).processResource(0xc0004543f0, {0x4c37528, 0xc0000d47f8}, 0x326c9a0?, 0xc000041df8)
	/go/pkg/mod/github.com/argoproj/notifications-engine@v0.4.1-0.20230620204159-3446d4ae8520/pkg/controller/controller.go:217 +0x8d8
github.com/argoproj/notifications-engine/pkg/controller.(*notificationController).processQueueItem(0xc0004543f0)
	/go/pkg/mod/github.com/argoproj/notifications-engine@v0.4.1-0.20230620204159-3446d4ae8520/pkg/controller/controller.go:297 +0x575
github.com/argoproj/notifications-engine/pkg/controller.(*notificationController).Run.func1()
	/go/pkg/mod/github.com/argoproj/notifications-engine@v0.4.1-0.20230620204159-3446d4ae8520/pkg/controller/controller.go:164 +0x29
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x30?)
	/go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/wait/wait.go:155 +0x3e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000721080?, {0x4be7440, 0xc000f044b0}, 0x1, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/wait/wait.go:156 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0004543f0?, 0x3b9aca00, 0x0, 0x1?, 0xc0000b2fd0?)
	/go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/wait/wait.go:133 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(0x4c0ee80?, 0xc000138000?, 0xc0002f0180?)
	/go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/wait/wait.go:90 +0x25
created by github.com/argoproj/notifications-engine/pkg/controller.(*notificationController).Run
	/go/pkg/mod/github.com/argoproj/notifications-engine@v0.4.1-0.20230620204159-3446d4ae8520/pkg/controller/controller.go:163 +0xe5
```

**Expected behavior**

Not seeing errors in the logs.

**Version**

```shell
argocd: v2.8.3+77556d9.dirty
  BuildDate: 2023-09-07T19:45:50Z
  GitCommit: 77556d9e64304c27c718bb0794676713628e435e
  GitTreeState: dirty
  GoVersion: go1.21.1
  Compiler: gc
  Platform: darwin/arm64
argocd-server: v2.8.3+77556d9
  BuildDate: 2023-09-07T16:05:43Z
  GitCommit: 77556d9e64304c27c718bb0794676713628e435e
  GitTreeState: clean
  GoVersion: go1.20.6
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.1.0 2023-06-19T16:58:18Z
  Helm Version: v3.12.1+gf32a527
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.20.0
```

Please let me know if you need further info.

**Comment by jsoref** [comment]
https://github.com/argoproj/notifications-engine/blob/3446d4ae85203ae9d597692b5c44e7adac44f612/pkg/services/github.go#L280
```go
		u := strings.Split(fullNameByRepoURL(notification.GitHub.repoURL), "/")
		// maximum is 140 characters
		description := trunc(notification.Message, 140)
		_, _, err := g.client.Repositories.CreateStatus(
			context.Background(),
			u[0],
			u[1],
```

So the `notification.GitHub.repoURL` has 0 `/`s in it and `u[1]` doesn't exist.

**Comment by jsoref** [comment]
Here's the equivalent code in `master`: https://github.com/argoproj/notifications-engine/blob/9dcecdc3eebfd98b63f72bac5ae4a7331b269754/pkg/services/github.go#L302-L308

**Comment by CarlosLanderas** [comment]
Hello, we are having the same issue in the notifications controller.

`time="2023-09-20T22:17:03Z" level=info msg="Trigger on-sync-status result: [{[0].2n6CTndf0GLEjg2LnSF9i-lrHGs  [github-commit-status-pending] false} {[1].OTPTOC2RNm4R12nv9K9oeExI83c  [github-commit-status-success] false} {[2].GODjlI4IgAQDzHKx7KM_vpJWRKA  [github-commit-status-failed] false} {[3].zoG5zUjYGjimkwCGgIQGjx1hO5s  [github-commit-status-error] true}]" resource=argo-cd/app-name`

Do you know if there is any workaround to solve this while the fix is rolled out?

Thanks in advance

**Comment by CarlosLanderas** [comment]
To provide some more details, I had the notifications failing in multi source. When I moved them to single source they started working and then stopped again when moving to multi source once more.
