### ISSUE TITLE
`application-controller` Runtime Error in `2.9.0-rc1` 

### ISSUE THREAD

**Issue by harrywm** [argoproj/argo-cd#15785]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Upon upgrading our ArgoCD Helm deployment from 2.8.4 to the 2.9.0 release candidate, the `application-controller` pods CrashLoop with the below runtime error.

```
time="2023-10-03T08:06:27Z" level=info msg="ArgoCD Application Controller is starting" built="2023-09-27T00:07:20Z" commit=b3fabc23cd613ecd7e213f55060ce007154d3fa8 namespace=argo version=v2.9.0-rc1+b3fabc2
time="2023-10-03T08:06:28Z" level=info msg="Processing clusters from shard 0"
time="2023-10-03T08:06:28Z" level=info msg="Using filter function:  legacy"
time="2023-10-03T08:06:28Z" level=info msg="Using filter function:  legacy"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1f0c0bd]

goroutine 1 [running]:
github.com/argoproj/argo-cd/v2/util/db.(*db).GetApplicationControllerReplicas(0xc0009506f0)
        /go/src/github.com/argoproj/argo-cd/util/db/db.go:157 +0xbd
github.com/argoproj/argo-cd/v2/controller/sharding.LegacyDistributionFunction({0x4d720e0?, 0xc0009506f0?})
        /go/src/github.com/argoproj/argo-cd/controller/sharding/sharding.go:96 +0x22
github.com/argoproj/argo-cd/v2/controller/sharding.GetDistributionFunction({0x4d720e0, 0xc0009506f0}, {0x3aa53e6, 0x6})
        /go/src/github.com/argoproj/argo-cd/controller/sharding/sharding.go:78 +0x9a
github.com/argoproj/argo-cd/v2/cmd/argocd-application-controller/commands.getClusterFilter(0xc000915e00, 0xc000cd8240, {0x3aa53e6, 0x6})
        /go/src/github.com/argoproj/argo-cd/cmd/argocd-application-controller/commands/argocd_application_controller.go:260 +0x3dc
github.com/argoproj/argo-cd/v2/cmd/argocd-application-controller/commands.NewCommand.func1(0xc000c58f00?, {0x3aa2998?, 0x4?, 0x3aa299c?})
        /go/src/github.com/argoproj/argo-cd/cmd/argocd-application-controller/commands/argocd_application_controller.go:142 +0x7f9
github.com/spf13/cobra.(*Command).execute(0xc000bf2c00, {0xc000072050, 0x1, 0x1})
        /go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:940 +0x87c
github.com/spf13/cobra.(*Command).ExecuteC(0xc000bf2c00)
        /go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3a5
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
main.main()
        /go/src/github.com/argoproj/argo-cd/cmd/main.go:57 +0x33c
```

**To Reproduce**

Running ArgoCD using the latest [Helm chart](https://artifacthub.io/packages/helm/argo/argo-cd) version (`5.46.7`), we intended to upgrade the Argo server image to the latest release candidate like so:

`values.yaml`:

```
global:
  image:
    tag: v2.9.0-rc1
```

Then, running a `helm upgrade` on our deployment.

**Expected behavior**

The `application-controller` pods to rollover to the new image version.

**Version**

```shell                    
argocd: v2.6.7+5bcd846.dirty
  BuildDate: 2023-03-23T17:19:51Z
  GitCommit: 5bcd846fa16e4b19d8f477de7da50ec0aef320e5
  GitTreeState: dirty
  GoVersion: go1.20.2
  Compiler: gc
  Platform: darwin/arm64
WARN[0000] Failed to invoke grpc call. Use flag --grpc-web in grpc calls. To avoid this warning message, use flag --grpc-web. 
argocd-server: v2.9.0-rc1+b3fabc2
  BuildDate: 2023-09-27T00:07:20Z
  GitCommit: b3fabc23cd613ecd7e213f55060ce007154d3fa8
  GitTreeState: clean
  GoVersion: go1.21.1
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.1.0 2023-06-19T16:58:18Z
  Helm Version: v3.12.1+gf32a527
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.20.0

```

**Comment by crenshaw-dev** [comment]
Thanks for the report! Fixed by https://github.com/argoproj/argo-cd/pull/15770. Will cut rc2 today.
