### ISSUE TITLE
cannot get history and rollback

### ISSUE THREAD

**Issue by jynw** [argoproj/argo-cd#15954]
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version**
v2.8.0+804d4b8
```shell
Paste the output from `argocd version` here.
```

**Logs**

```
Paste any relevant application logs here.
```
Something went wrong!

Consider submitting an issue [here](https://github.com/argoproj/argo-cd/issues/new?labels=bug&template=bug_report.md).

Stacktrace:

TypeError: Cannot read properties of undefined (reading 'length')
    at Object.children (https://xxxx:30080/main.c59cb611154ee2061ab5.js:2:1732979)
    at Fr.render (https://xxxx:30080/main.c59cb611154ee2061ab5.js:2:1565823)
    at zi (https://xxxx:30080/main.c59cb611154ee2061ab5.js:2:820282)
    at Hi (https://xxxx:30080/main.c59cb611154ee2061ab5.js:2:820077)
    at Es (https://xxxx:30080/main.c59cb611154ee2061ab5.js:2:855701)
    at Sl (https://xxxx:30080/main.c59cb611154ee2061ab5.js:2:847160)
    at xl (https://xxxx:30080/main.c59cb611154ee2061ab5.js:2:847085)
    at hl (https://xxxx:30080/main.c59cb611154ee2061ab5.js:2:844108)
    at https://xxxx:30080/main.c59cb611154ee2061ab5.js:2:795769
    at t.unstable_runWithPriority (https://xxxx:30080/main.c59cb611154ee2061ab5.js:2:870971)

**Comment by crenshaw-dev** [comment]
@jynw can you post a redacted copy of the full Application manifest, including the `status` field?

**Comment by jynw** [comment]
> @jynw can you post a redacted copy of the full Application manifest, including the `status` field?

![image](https://github.com/argoproj/argo-cd/assets/31000620/2a3be383-80ea-412e-9694-b4f1b21c3672)
the status is synced.
![image](https://github.com/argoproj/argo-cd/assets/31000620/084655b6-29d6-4acc-8d3c-03417d222115)
we're using LoadBlancer for ArgoCD service. so any security rule should be updated form the cloud?

**Comment by cyphrsonic** [comment]
I'm experiencing error as well - for us, the error occurs in an Applcation deployed by an Appset, and I also managed to find a JS error in the console `t.maintainers is not defined`.

**Comment by cyphrsonic** [comment]
As an FYI, a comment in Issue #13043 says that this was fixed and should be expected to be part of the 2.8.4 release.

**Comment by jgwest** [comment]
Based on above comment, is it still reproducible?

**Comment by jgwest** [comment]
No response from reported, likely no longer reproducible.
