### ISSUE TITLE
Login ArgoCD Web UI encountered "this.props.onSubmitFailure is not a function"; CLI works well.

### ISSUE THREAD

**Issue by wadexu007** [argoproj/argo-cd#15966]
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**
ArgoCD CLI works well, `argocd login` and `argocd account update-password` both works well.

But login with Chrome or Edge, encountered this error, can't login.

Uncaught (in promise) TypeError: this.props.onSubmitFailure is not a function
    at t.<anonymous> (main.1d2e00654dba62cdf318.js:2:842643)
    at v (main.1d2e00654dba62cdf318.js:2:45329)
    at Generator._invoke (main.1d2e00654dba62cdf318.js:2:45117)
    at S.forEach.e.<computed> [as throw] (main.1d2e00654dba62cdf318.js:2:45509)
    at r (main.1d2e00654dba62cdf318.js:2:11650)
    at main.1d2e00654dba62cdf318.js:2:11774

**To Reproduce**

```
kubectl create namespace argocd
kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/v2.9.0-rc2/manifests/install.yaml
```

I tried several versions, all not work.
latest: [v2.9.0-rc2](https://github.com/argoproj/argo-cd/releases/tag/v2.9.0-rc2)
Stable: [v2.8.4](https://github.com/argoproj/argo-cd/releases/tag/v2.8.4)
and an old version: [v2.5.22](https://github.com/argoproj/argo-cd/releases/tag/v2.5.22)

**Expected behavior**

I can login from UI successfully.

**Screenshots**

**Version**

```shell
Paste the output from `argocd version` here.
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by gennway** [comment]
hey, i've got the same issue, have you found solution for that? @wadexu007

**Comment by andrii-korotkov-verkada** [comment]
ArgoCD versions 2.10 and below have reached EOL. Can you upgrade and let us know if the issue is still present, please?

**Comment by thulasi-ram** [comment]
Sorry for dropping a plain "This is not working". Did a small deep dive. I was using an insecure server (http) for testing. The issue seems to be the backend is setting the [Secure flag](https://github.com/argoproj/argo-cd/blob/a00446565c0c7783394ff62d90df9a83a18a8095/server/server.go#L1114C4-L1116C3) on `!server.Insecure` and as such a secure cookie is being sent.

Later I tracked it to a config issue. The helm chart doesn't implement `server.insecure` but instead implements it inside `configs -> params -> server.insecure`. One can confirm this by checking the `argocd-cmd-params-cm` and the corresponding [values.yaml](https://github.com/argoproj/argo-helm/blob/0f29eaf7939aab268e6a6b7c9323b875924f2a91/charts/argo-cd/values.yaml#L284)

<img width="970" alt="Image" src="https://github.com/user-attachments/assets/f6dadd84-def9-4180-b435-a73594f155ee" />

<br></br>

<img width="1792" alt="Image" src="https://github.com/user-attachments/assets/bfc2a612-c4d2-47c8-9ed1-925b39e04f7c" />

<br></br>

<img width="1070" alt="Image" src="https://github.com/user-attachments/assets/4d82c38c-e7cb-4fcc-9410-b61a0c6bb999" />
