### ISSUE TITLE
Error creating sync windows argocd

### ISSUE THREAD

**Issue by Abubakarr99** [argoproj/argo-cd#16701]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**
I get a segmentation fault when trying to list the sync window in the default argocd project. This is also true when i try to create a sync window from the UI

**To Reproduce**

`argocd proj windows list default`

**Expected behavior**
`
WARN[0000] Failed to invoke grpc call. Use flag --grpc-web in grpc calls. To avoid this warning message, use flag --grpc-web.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1d1ba84]

goroutine 1 [running]:
github.com/argoproj/argo-cd/v2/pkg/apis/application/v1alpha1.SyncWindow.active({{0xc000febac8, 0x5}, {0x0, 0x0}, {0x0, 0x0}, {0xc000766750, 0x1, 0x1}, {0x0, ...}, ...}, ...)
        /home/runner/work/argo-cd/argo-cd/pkg/apis/application/v1alpha1/types.go:2500 +0x104
github.com/argoproj/argo-cd/v2/pkg/apis/application/v1alpha1.SyncWindow.Active({{0xc000febac8, 0x5}, {0x0, 0x0}, {0x0, 0x0}, {0xc000766750, 0x1, 0x1}, {0x0, ...}, ...})
        /home/runner/work/argo-cd/argo-cd/pkg/apis/application/v1alpha1/types.go:2485 +0x3e
github.com/argoproj/argo-cd/v2/cmd/argocd/commands.printSyncWindows(0xc0006d0240)
        /home/runner/work/argo-cd/argo-cd/cmd/argocd/commands/projectwindows.go:295 +0x478
github.com/argoproj/argo-cd/v2/cmd/argocd/commands.NewProjectWindowsListCommand.func1(0xc0007ab500?, {0xc000435390?, 0x4?, 0x3a9311c?})
        /home/runner/work/argo-cd/argo-cd/cmd/argocd/commands/projectwindows.go:274 +0x285
github.com/spf13/cobra.(*Command).execute(0xc000806f00, {0xc0004352f0, 0x1, 0x1})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x863
github.com/spf13/cobra.(*Command).ExecuteC(0xc000004c00)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3a5
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
main.main()
        /home/runner/work/argo-cd/argo-cd/cmd/main.go:57 +0x33c`

**Screenshots**

**Version**

```shell
argocd: v2.9.3+6eba5be
  BuildDate: 2023-12-01T23:24:09Z
  GitCommit: 6eba5be864b7e031871ed7698f5233336dfe75c7
  GitTreeState: clean
  GoVersion: go1.21.4
  Compiler: gc
  Platform: linux/amd64
WARN[0000] Failed to invoke grpc call. Use flag --grpc-web in grpc calls. To avoid this warning message, use flag --grpc-web.
argocd-server: v2.8.4+c279299
  BuildDate: 2023-10-02T12:28:05Z
  GitCommit: c27929928104dc37b937764baf65f38b78930e59
  GitTreeState: clean
  GoVersion: go1.20.8
  Compiler: gc
  Platform: linux/arm64
  Kustomize Version: (devel) unknown
  Helm Version: v3.13.0+g825e86f
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.20.0
```

**Logs**

```
time="2023-12-26T09:24:16Z" level=info msg="received unary call /project.ProjectService/GetSyncWindowsState" grpc.method=GetSyncWindowsState grpc.request.claims="{\"at_hash\":\"fVqmI5a1ki-zngVFOEu-TA\",\"aud\":\"argocd\",\"auth_time\":1703578543,\"azp\":\"argocd\",\"email\":\"abubakarr.kamara@jump-informatique.com\",\"email_verified\":false,\"exp\":1703582918,\"family_name\":\"Kamara\",\"given_name\":\"Abubakarr\",\"iat\":1703582618,\"iss\":\"https://keycloak.jump-technology.com/auth/realms/Jump-Kubernetes\",\"jti\":\"a43f4244-cba3-4d15-9c3e-7fedfca7fd4e\",\"name\":\"Abubakarr Kamara\",\"preferred_username\":\"a.kamara\",\"session_state\":\"af02166e-7929-45ec-8104-8727415c1a71\",\"sid\":\"af02166e-7929-45ec-8104-8727415c1a71\",\"sub\":\"39802584-1184-4474-a2c5-97ad7c6b06fb\",\"typ\":\"ID\"}" grpc.request.content="name:\"default\" " grpc.service=project.ProjectService grpc.start_time="2023-12-26T09:24:16Z" span.kind=server system=grpc
time="2023-12-26T09:24:16Z" level=error msg="Recovered from panic: runtime error: invalid memory address or nil pointer dereference\ngoroutine 7237 [running]:\nruntime/debug.Stack()\n\t/opt/bitnami/go/src/runtime/debug/stack.go:24 +0x64\ngithub.com/argoproj/argo-cd/v2/util/grpc.PanicLoggerUnaryServerInterceptor.func1.1()\n\t/bitnami/blacksmith-sandox/argo-cd-2.8.4/src/github.com/argoproj/argo-cd/util/grpc/grpc.go:26 +0x48\npanic({0x2beaea0, 0x61a1260})\n\t/opt/bitnami/go/src/runtime/panic.go:884 +0x1f4\ngithub.com/argoproj/argo-cd/v2/pkg/apis/application/v1alpha1.(*SyncWindows).active(0x4001a1c1a8, {0x253e3e4?, 0x38?, 0x63d33a0?})\n\t/bitnami/blacksmith-sandox/argo-cd-2.8.4/src/github.com/argoproj/argo-cd/pkg/apis/application/v1alpha1/types.go:2176 +0x168\ngithub.com/argoproj/argo-cd/v2/pkg/apis/application/v1alpha1.(*SyncWindows).Active(0x4001bf0de0?)\n\t/bitnami/blacksmith-sandox/argo-cd-2.8.4/src/github.com/argoproj/argo-cd/pkg/apis/application/v1alpha1/types.go:2158 +0x34\ngithub.com/argoproj/argo-cd/v2/server/project.(*Server).GetSyncWindowsState(0x4000772e10, {0x43ec550, 0x4000f38780}, 0x4001a35230)\n\t/bitnami/blacksmith-sandox/argo-cd-2.8.4/src/github.com/argoproj/argo-cd/server/project/project.go:525 +0x1bc\ngithub.com/argoproj/argo-cd/v2/pkg/apiclient/project._ProjectService_GetSyncWindowsState_Handler.func1({0x43ec550, 0x4000f38780}, {0x300b140?, 0x4001a35230})\n\t/bitnami/blacksmith-sandox/argo-cd-2.8.4/src/github.com/argoproj/argo-cd/pkg/apiclient/project/project.pb.go:1191 +0x74\ngithub.com/argoproj/argo-cd/v2/util/grpc.PanicLoggerUnaryServerInterceptor.func1({0x43ec550?, 0x4000f38780?}, {0x300b140?, 0x4001a35230?}, 0x4b?, 0x3225daf?)\n\t/bitnami/blacksmith-sandox/argo-cd-2.8.4/src/github.com/argoproj/argo-cd/util/grpc/grpc.go:30 +0x78\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func2.1({0x43ec550?, 0x4000f38780?}, {0x300b140?, 0x4001a35230?})\n\t/bitnami/blacksmith-sandox/kustomize-5.1.1/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/chain.go:48 +0x50\ngithub.com/argoproj/argo-cd/v2/util/grpc.ErrorCodeGitUnaryServerInterceptor.func1({0x43ec550?, 0x4000f38780?}, {0x300b140?, 0x4001a35230?}, 0x0?, 0x2a477e0?)\n\t/bitnami/blacksmith-sandox/argo-cd-2.8.4/src/github.com/argoproj/argo-cd/util/grpc/errors.go:108 +0x34\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func2.1({0x43ec550?, 0x4000f38780?}, {0x300b140?, 0x4001a35230?})\n\t/bitnami/blacksmith-sandox/kustomize-5.1.1/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/chain.go:48 +0x50\ngithub.com/argoproj/argo-cd/v2/util/grpc.ErrorCodeK8sUnaryServerInterceptor.func1({0x43ec550?, 0x4000f38780?}, {0x300b140?, 0x4001a35230?}, 0x0?, 0x0?)\n\t/bitnami/blacksmith-sandox/argo-cd-2.8.4/src/github.com/argoproj/argo-cd/util/grpc/errors.go:124 +0x34\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func2.1({0x43ec550?, 0x4000f38780?}, {0x300b140?, 0x4001a35230?})\n\t/bitnami/blacksmith-sandox/kustomize-5.1.1/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/chain.go:48 +0x50\ngithub.com/argoproj/argo-cd/v2/util/grpc.PayloadUnaryServerInterceptor.func1({0x43ec550, 0x4000f38780}, {0x300b140, 0x4001a35230}, 0x4001bf0ae0, 0x40011be900)\n\t/bitnami/blacksmith-sandox/argo-cd-2.8.4/src/github.com/argoproj/argo-cd/util/grpc/logging.go:91 +0x114\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func2.1({0x43ec550?, 0x4000f38780?}, {0x300b140?, 0x4001a35230?})\n\t/bitnami/blacksmith-sandox/kustomize-5.1.1/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/chain.go:48 +0x50\ngithub.com/argoproj/argo-cd/v2/util/grpc.UserAgentUnaryServerInterceptor.func1({0x43ec550, 0x4000f38780}, {0x300b140, 0x4001a35230}, 0x4001a354a0?, 0x40011be980)\n\t/bitnami/blacksmith-sandox/argo-cd-2.8.4/src/github.com/argoproj/argo-cd/util/grpc/useragent.go:25 +0x8c\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func2.1({0x43ec550?, 0x4000f38780?}, {0x300b140?, 0x4001a35230?})\n\t/bitnami/blacksmith-sandox/kustomize-5.1.1/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/chain.go:48 +0x50\ngithub.com/grpc-ecosystem/go-grpc-middleware/auth.UnaryServerInterceptor.func1({0x43ec550, 0x4001a354a0}, {0x300b140, 0x4001a35230}, 0x4001bf0ae0, 0x40011be9c0)\n\t/bitnami/blacksmith-sandox/kustomize-5.1.1/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/auth/auth.go:47 +0xbc\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func2.1({0x43ec550?, 0x4001a354a0?}, {0x300b140?, 0x4001a35230?})\n\t/bitnami/blacksmith-sandox/kustomize-5.1.1/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/chain.go:48 +0x50\ngithub.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).UnaryServerInterceptor.func1({0x43ec550, 0x4001a354a0}, {0x300b140, 0x4001a35230}, 0x0?, 0x40011bea40)\n\t/bitnami/blacksmith-sandox/kustomize-5.1.1/pkg/mod/github.com/grpc-ecosystem/go-grpc-prometheus@v1.2.0/server_metrics.go:107 +0x74\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func2.1({0x43ec550?, 0x4001a354a0?}, {0x300b140?, 0x4001a35230?})\n\t/bitnami/blacksmith-sandox/kustomize-5.1.1/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/chain.go:48 +0x50\ngithub.com/grpc-ecosystem/go-grpc-middleware/logging/logrus.UnaryServerInterceptor.func1({0x43ec550, 0x4001a352f0}, {0x300b140, 0x4001a35230}, 0x4001bf0ae0, 0x40011bea80)\n\t/bitnami/blacksmith-sandox/kustomize-5.1.1/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/logging/logrus/server_interceptors.go:31 +0xb8\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func2.1({0x43ec550?, 0x4001a352f0?}, {0x300b140?, 0x4001a35230?})\n\t/bitnami/blacksmith-sandox/kustomize-5.1.1/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/chain.go:48 +0x50\ngo.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc.UnaryServerInterceptor.func1({0x43ec550, 0x4001a35200}, {0x300b140, 0x4001a35230}, 0x4001bf0ae0, 0x40011beb00)\n\t/bitnami/blacksmith-sandox/kustomize-5.1.1/pkg/mod/go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc@v0.42.0/interceptor.go:344 +0x3d0\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func2.1({0x43ec550?, 0x4001a35200?}, {0x300b140?, 0x4001a35230?})\n\t/bitnami/blacksmith-sandox/kustomize-5.1.1/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/chain.go:48 +0x50\ngithub.com/argoproj/argo-cd/v2/server.bug21955WorkaroundInterceptor({0x43ec550, 0x4001a35200}, {0x300b140?, 0x4001a35230?}, 0x4001a14b40?, 0x40011beb40)\n\t/bitnami/blacksmith-sandox/argo-cd-2.8.4/src/github.com/argoproj/argo-cd/server/server.go:1434 +0x4cc\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func2({0x43ec550, 0x4001a35200}, {0x300b140, 0x4001a35230}, 0x4001bf0ae0, 0x18f375c?)\n\t/bitnami/blacksmith-sandox/kustomize-5.1.1/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/chain.go:53 +0x158\ngithub.com/argoproj/argo-cd/v2/pkg/apiclient/project._ProjectService_GetSyncWindowsState_Handler({0x3033d60?, 0x4000772e10}, {0x43ec550, 0x4001a35200}, 0x40006cafc0, 0x4000c2ec60)\n\t/bitnami/blacksmith-sandox/argo-cd-2.8.4/src/github.com/argoproj/argo-cd/pkg/apiclient/project/project.pb.go:1193 +0x12c\ngoogle.golang.org/grpc.(*Server).processUnaryRPC(0x400055e1e0, {0x43faa20, 0x40009a01a0}, 0x4000624fc0, 0x4000c2f2c0, 0x6384bb0, 0x0)\n\t/bitnami/blacksmith-sandox/kustomize-5.1.1/pkg/mod/google.golang.org/grpc@v1.56.1/server.go:1337 +0xc28\ngoogle.golang.org/grpc.(*Server).handleStream(0x400055e1e0, {0x43faa20, 0x40009a01a0}, 0x4000624fc0, 0x0)\n\t/bitnami/blacksmith-sandox/kustomize-5.1.1/pkg/mod/google.golang.org/grpc@v1.56.1/server.go:1714 +0x80c\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.1()\n\t/bitnami/blacksmith-sandox/kustomize-5.1.1/pkg/mod/google.golang.org/grpc@v1.56.1/server.go:959 +0x84\ncreated by google.golang.org/grpc.(*Server).serveStreams.func1\n\t/bitnami/blacksmith-sandox/kustomize-5.1.1/pkg/mod/google.golang.org/grpc@v1.56.1/server.go:957 +0x164\n"
time="2023-12-26T09:24:16Z" level=error msg="finished unary call with code Internal" error="rpc error: code = Internal desc = runtime error: invalid memory address or nil pointer dereference" grpc.code=Internal grpc.method=GetSyncWindowsState grpc.service=project.ProjectService grpc.start_time="2023-12-26T09:24:16Z" grpc.time_ms=10.091 span.kind=server system=grpc
```

**Comment by reginapizza** [comment]
Having a similar issue right now, how was this completed?
