### ISSUE TITLE
Panic Error with 'dist/argocd admin app get-reconcile-results' Command Using --refresh Flag

### ISSUE THREAD

**Issue by Mangaal** [argoproj/argo-cd#17602]
### Description
When running the following command with the `--refresh` flag:

```dist/argocd admin app  get-reconcile-results test.txt  --refresh --repo-server-name=example-argocd-repo-server```

I encounter the following error:

```
Repo server is not provided, trying to port-forward to argocd-repo-server pod.
INFO[0000] Starting configmap/secret informers          
INFO[0000] Configmap/secret informer synced             
Reconciling apps of https://kubernetes.default.svc
guestbook
INFO[0000] Comparing app state (cluster: https://kubernetes.default.svc, namespace: argocd-operator)  application=argocd-operator/guestbook
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x50 pc=0x102867c90]

goroutine 1 [running]:
github.com/argoproj/argo-cd/v2/controller/cache.(*liveStateCache).canHandleCluster(...)
        /Users/mangaal/upstream/argo-cd/controller/cache/cache.go:731
github.com/argoproj/argo-cd/v2/controller/cache.(*liveStateCache).getCluster(0x14000f48380, {0x14000bb6820, 0x1e})
        /Users/mangaal/upstream/argo-cd/controller/cache/cache.go:440 +0x250
github.com/argoproj/argo-cd/v2/controller/cache.(*liveStateCache).getSyncedCluster(0x14000393ea0?, {0x14000bb6820?, 0x0?})
        /Users/mangaal/upstream/argo-cd/controller/cache/cache.go:570 +0x20
github.com/argoproj/argo-cd/v2/controller/cache.(*liveStateCache).GetVersionsInfo(0x14000091540?, {0x14000bb6820, 0x1e})
        /Users/mangaal/upstream/argo-cd/controller/cache/cache.go:651 +0x28
github.com/argoproj/argo-cd/v2/controller.(*appStateManager).GetRepoObjs(0x14001296000, 0x140002e9808, {0x14000b25ea0, 0x1, 0x14000f1f360?}, {0x1400110e340, 0x1a}, {0x1400063ab90, 0x1, 0x100b9a824?}, ...)
        /Users/mangaal/upstream/argo-cd/controller/state.go:164 +0x86c
github.com/argoproj/argo-cd/v2/controller.(*appStateManager).CompareAppState(0x14001296000, 0x140002e9808, 0x140008ef608, {0x1400063ab90, 0x1, 0x1}, {0x14000b25ea0, 0x1, 0x1}, 0x0, ...)
        /Users/mangaal/upstream/argo-cd/controller/state.go:421 +0x4bac
github.com/argoproj/argo-cd/v2/cmd/argocd/commands/admin.reconcileApplications({0x104e3f780, 0x1073470e0}, {0x104e75790, 0x14000d7d520}, {0x104e15308, 0x14000eb1c20}, {0x16f26b698, 0xf}, {0x104e041e8, 0x14000ede6c0}, ...)
        /Users/mangaal/upstream/argo-cd/cmd/argocd/commands/admin/app.go:425 +0xbf0
github.com/argoproj/argo-cd/v2/cmd/argocd/commands/admin.NewReconcileCommand.func1(0x14000bf4c00?, {0x14000b0e5f0?, 0x4?, 0x1036f4b02?})
        /Users/mangaal/upstream/argo-cd/cmd/argocd/commands/admin/app.go:284 +0x488
github.com/spf13/cobra.(*Command).execute(0x14000c48008, {0x14000b0e5a0, 0x5, 0x5})
        /Users/mangaal/upstream/argo-cd/vendor/github.com/spf13/cobra/command.go:944 +0x63c
github.com/spf13/cobra.(*Command).ExecuteC(0x140008a8c08)
        /Users/mangaal/upstream/argo-cd/vendor/github.com/spf13/cobra/command.go:1068 +0x320
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/mangaal/upstream/argo-cd/vendor/github.com/spf13/cobra/command.go:992
main.main()
        /Users/mangaal/upstream/argo-cd/cmd/main.go:57 +0x324
```

### Additional Information

 I encountered this error while using a locally built version of ArgoCD from the current master branch. The error is not present in my previously installed version(v2.9.3).

**Panic ArgoCD Version:**
```
dist/argocd version
argocd: v2.11.0+63a72ee.dirty
  BuildDate: 2024-03-21T12:10:16Z
  GitCommit: 63a72ee1e7856cc095952698ad859f96e1f16427
  GitTreeState: dirty
  GoVersion: go1.22.1
  Compiler: gc
  Platform: darwin/arm64
```

### Expected Behavior
The command should successfully reconcile all applications and store the reconciliation summary in the specified file, without encountering any errors.

Checklist:

*  I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
*  I've included steps to reproduce the bug.
* I've pasted the output of `argocd version`.

**Comment by Mangaal** [comment]
I have address this issue in a [PR #17613](https://github.com/argoproj/argo-cd/pull/17613)
