### ISSUE TITLE
error

### ISSUE THREAD

**Issue by customiz** [argoproj/argo-cd#18762]
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version**

```shell
Paste the output from `argocd version` here.
```

**Logs**

```
Something went wrong!

Consider submitting an issue [here](https://github.com/argoproj/argo-cd/issues/new?labels=bug&template=bug_report.md).


Stacktrace:

ChunkLoadError
    at i.f.j (https://argocd.speedhub.dev/main.a997caebf5e9d3fafbf3.js:2:2328778)
    at https://argocd.speedhub.dev/main.a997caebf5e9d3fafbf3.js:2:2324469
    at Array.reduce (<anonymous>)
    at i.e (https://argocd.speedhub.dev/main.a997caebf5e9d3fafbf3.js:2:2324447)
    at https://argocd.speedhub.dev/main.a997caebf5e9d3fafbf3.js:2:1425627
    at https://argocd.speedhub.dev/main.a997caebf5e9d3fafbf3.js:2:616013
    at Es (https://argocd.speedhub.dev/main.a997caebf5e9d3fafbf3.js:2:616162)
    at kl (https://argocd.speedhub.dev/main.a997caebf5e9d3fafbf3.js:2:608142)
    at xl (https://argocd.speedhub.dev/main.a997caebf5e9d3fafbf3.js:2:608067)
    at hl (https://argocd.speedhub.dev/main.a997caebf5e9d3fafbf3.js:2:605090)
```

**Comment by agaudreault** [comment]
Closing due to missing details. Feel free to reopen and add the details
