### ISSUE TITLE
UI error: Cannot read properties of null (reading 'appsInAnyNamespaceEnabled')

### ISSUE THREAD

**Issue by agaudreault** [argoproj/argo-cd#19538]
**Describe the bug**

When browsing to a project url directly such as https://cd.apps.argoproj.io/settings/projects/sync, we get the following

```
Something went wrong!

Consider submitting an issue [here](https://github.com/argoproj/argo-cd/issues/new?labels=bug&template=bug_report.md).


Stacktrace:

TypeError: Cannot read properties of null (reading 'appsInAnyNamespaceEnabled')
    at https://cd.apps.argoproj.io/main.57deacbb92d583aa2bca.js:2:2038149
    at Es (https://cd.apps.argoproj.io/main.57deacbb92d583aa2bca.js:2:806298)
    at kl (https://cd.apps.argoproj.io/main.57deacbb92d583aa2bca.js:2:795645)
    at xl (https://cd.apps.argoproj.io/main.57deacbb92d583aa2bca.js:2:795570)
    at hl (https://cd.apps.argoproj.io/main.57deacbb92d583aa2bca.js:2:792593)
    at https://cd.apps.argoproj.io/main.57deacbb92d583aa2bca.js:2:744254
    at t.unstable_runWithPriority (https://cd.apps.argoproj.io/main.57deacbb92d583aa2bca.js:2:819456)
    at qo (https://cd.apps.argoproj.io/main.57deacbb92d583aa2bca.js:2:743963)
    at Xo (https://cd.apps.argoproj.io/main.57deacbb92d583aa2bca.js:2:744199)
    at Jo (https://cd.apps.argoproj.io/main.57deacbb92d583aa2bca.js:2:744134)
```

**To Reproduce**

- Navigate to https://cd.apps.argoproj.io/settings/projects/sync directly (not through UI Settings -> Projects -> sync)

**Expected behavior**

No error

**Version**

```shell
v2.12.0
```

**Comment by rajatgupta24** [comment]
Hey @agaudreault, can I pick this up?

**Comment by agaudreault** [comment]
@rajatgupta24 go ahead! You can open a draft PR when you have some changes to let people know you are working on the issue.

**Comment by agaudreault** [comment]
Thanks for working on this @linghaoSu 🎉
