### ISSUE TITLE
Unable to add repository with git@github.com style URL

### ISSUE THREAD

**Issue by ghost** [argoproj/argo-cd#2033]
**Describe the bug**
Unable to add repository with git@github.com style URL

**To Reproduce**
Run `argocd repo add` with a git@github.com URL

**Expected behavior**
ArgoCD should add the specified repository without causing a panic.

**Screenshots**
N/A

**Version**

```shell
argocd: v1.1.1+8544bef.dirty
  BuildDate: 2019-07-24T17:31:40Z
  GitCommit: 8544bef56b8bee19e73a71b2d10ccd64156dd72c
  GitTreeState: dirty
  GoVersion: go1.11.4
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.1.1+8544bef.dirty
  BuildDate: 2019-07-24T17:31:17Z
  GitCommit: 8544bef56b8bee19e73a71b2d10ccd64156dd72c
  GitTreeState: dirty
  GoVersion: go1.11.4
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: 0.13.1
```

**Logs**

```
panic: read /Users/<USERNAME>/.ssh: is a directory

goroutine 16 [running]:
github.com/kevinburke/ssh_config.(*sshLexer).peek(0xc00054a580, 0x0)
	/go/src/github.com/kevinburke/ssh_config/lexer.go:202 +0x101
github.com/kevinburke/ssh_config.(*sshLexer).lexVoid(0xc00054a580, 0xc0006cc118)
	/go/src/github.com/kevinburke/ssh_config/lexer.go:141 +0x35
github.com/kevinburke/ssh_config.(*sshLexer).lexVoid-fm(0xc0006cc0c0)
	/go/src/github.com/kevinburke/ssh_config/lexer.go:93 +0x2a
github.com/kevinburke/ssh_config.(*sshLexer).run(0xc00054a580)
	/go/src/github.com/kevinburke/ssh_config/lexer.go:224 +0x4a
created by github.com/kevinburke/ssh_config.lexSSH
	/go/src/github.com/kevinburke/ssh_config/lexer.go:239 +0xd1
```

**Comment by alexec** [comment]
looking...

**Comment by rtkbhops** [comment]
Thanks @alexec. I've actually figured out what caused this, but don't really know why.
My ~/.ssh/config contains an `Include config.vagrant.*` directive, where the included files each contain Host configurations. If I remove the `Include` this works fine.

**Comment by alexec** [comment]
I get a different error:
```bash
~/go/src/github.com/argoproj/argo-cd (master)
$ argocd repo add git@github.com:argoproj/argocd-example-apps.git --loglevel debug
FATA[0000] rpc error: code = Unknown desc = ssh: handshake failed: ssh: unable to authenticate, attempted methods [publickey none], no supported methods remain 
```

**Comment by alexec** [comment]
ok, please close?

**Comment by rtkbhops** [comment]
> ok, please close?

I'm not sure if this is a problem with ArgoCD specifically, or more of a problem with an upstream library but my ~/.ssh/config is valid so this definitely shouldn't panic with the `Include` directive.

**Comment by jannfis** [comment]
From v1.2 upwards, local client does not execute SSH to access repositories anymore.
