### ISSUE TITLE
Dashboard: ChunkLoadError when clicking a running pod

### ISSUE THREAD

**Issue by DoctorOctopus-Zhan** [argoproj/argo-cd#20421]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**
Argocd dashboard web page, ChunkLoadError when clicking a running pod details.

**To Reproduce**
1. login to argocd dashboard
2. check any pod, with normal behavior
3. close argocd dashboard web page
4. open the same argocd dashboard (browser cache so no need to login)
5. check some pod-details, and possibly reproduce the bug

**Expected behavior**
The web should show pod status and log normally.

**Screenshots**

![argocd-bug](https://github.com/user-attachments/assets/1a56ecb9-fc95-407f-a904-71de6c2e8004)

**Version**

```shell
argocd: v2.10.1+a79e0ea
  BuildDate: 2024-02-14T17:56:39Z
  GitCommit: a79e0eaca415461dc36615470cecc25d6d38cefb
  GitTreeState: clean
  GoVersion: go1.21.7
  Compiler: gc
  Platform: linux/amd64
WARN[0001] Failed to invoke grpc call. Use flag --grpc-web in grpc calls. To avoid this warning message, use flag --grpc-web. 
argocd-server: v2.13.0+60df9eb
```

**Logs**

```
Something went wrong!

Consider submitting an issue [here](https://github.com/argoproj/argo-cd/issues/new?labels=bug&template=bug_report.md).


Stacktrace:

ChunkLoadError
    at Object.j (https://fs-argocd.wps.kingsoft.net/main.8caf59c082da65cc8104.js:2:2366672)
    at https://fs-argocd.wps.kingsoft.net/main.8caf59c082da65cc8104.js:2:2362287
    at Array.reduce (<anonymous>)
    at Function.e (https://fs-argocd.wps.kingsoft.net/main.8caf59c082da65cc8104.js:2:2362265)
    at https://fs-argocd.wps.kingsoft.net/main.8caf59c082da65cc8104.js:2:1427993
    at https://fs-argocd.wps.kingsoft.net/main.8caf59c082da65cc8104.js:2:615892
    at Es (https://fs-argocd.wps.kingsoft.net/main.8caf59c082da65cc8104.js:2:616041)
    at kl (https://fs-argocd.wps.kingsoft.net/main.8caf59c082da65cc8104.js:2:608045)
    at xl (https://fs-argocd.wps.kingsoft.net/main.8caf59c082da65cc8104.js:2:607970)
    at hl (https://fs-argocd.wps.kingsoft.net/main.8caf59c082da65cc8104.js:2:605003)
```

**Comment by andrii-korotkov-verkada** [comment]
I can't find any references to `ChunkLoadError` in argo-cd or argo-ui codebases. Where is this `main.<id>.js` coming from? Can you share its contents, or is the problem with loading it?

**Comment by andrii-korotkov-verkada** [comment]
Related https://github.com/argoproj/argo-cd/issues/20177
