### ISSUE TITLE
Error initializing argo-dex-server and argo-repo-server deployments

### ISSUE THREAD

**Issue by askhari** [argoproj/argo-cd#2045]
**Describe the bug**
After installing argo using the HA manifest, argo-dex-server and argo-repo-server pods crash due the error below

```shell
panic: stat /go/src/github.com/argoproj/argo-cd/assets/builtin-policy.csv: no such file or directory

goroutine 1 [running]:
github.com/argoproj/argo-cd/util/assets.init.0()
	/go/src/github.com/argoproj/argo-cd/util/assets/assets.go:19 +0x441
```

Also here you may see a list of all pods status:

```shell
ᐅ kubectl -n argocd get pods                                       
NAME                                            READY   STATUS             RESTARTS   AGE
argocd-application-controller-dc45b5ccd-8t42d   1/1     Running            0          113s
argocd-dex-server-6594d7756-5qmwj               0/1     CrashLoopBackOff   3          113s
argocd-redis-ha-server-0                        2/2     Running            0          112s
argocd-redis-ha-server-1                        2/2     Running            0          93s
argocd-redis-ha-server-2                        2/2     Running            0          73s
argocd-repo-server-b84db6dd6-5j8hw              0/1     CrashLoopBackOff   4          112s
argocd-repo-server-b84db6dd6-x7lrr              0/1     CrashLoopBackOff   3          112s
argocd-server-899966c6f-7bjmp                   1/1     Running            0          112s
argocd-server-899966c6f-9vvxn                   1/1     Running            0          112s
```

**To Reproduce**
Requirements:
* A Kubernetes cluster with enough resources to deploy all pods.

Steps to reproduce:
1. Clone the repository: git clone https://github.com/argoproj/argo-cd.git
2. Change to the created folder: cd argo-cd
3. Create a namespace for argo: kubectl create ns argocd
3. Apply manifest: kubectl apply -n argocd manifests/ha/install.yaml
4. Check pods status: kubectl -n argocd get pods -w
5. Get logs from pods to see the error: kubectl -n argocd logs -lapp.kubernetes.io/name=argocd-repo-server

**Expected behavior**
All argocd pods starting normally. Expected output:

```shell
ᐅ kubectl -n argocd get pods
NAME                                             READY   STATUS    RESTARTS   AGE
argocd-application-controller-78fcccf776-8zrf6   1/1     Running   2          35m
argocd-dex-server-db56d6cd-2d2z7                 1/1     Running   2          35m
argocd-redis-ha-server-0                         2/2     Running   0          35m
argocd-redis-ha-server-1                         2/2     Running   0          34m
argocd-redis-ha-server-2                         2/2     Running   0          34m
argocd-repo-server-67d8b46496-jq4pg              1/1     Running   0          35m
argocd-repo-server-67d8b46496-qhbcc              1/1     Running   0          35m
argocd-server-7bc8fcf95-8zzj5                    1/1     Running   0          32m
argocd-server-7bc8fcf95-sd7kl                    1/1     Running   0          32m
```

**Version**
This error comes from the argocd:latest docker released on July 26th at 8:23PM.
It may be related to this commit: 351e964e4eecc17ac4c45f345eb32557168d643c

**Logs**

```shell
ᐅ kubectl -n argocd logs argocd-repo-server-b84db6dd6-5j8hw
panic: stat /go/src/github.com/argoproj/argo-cd/assets/builtin-policy.csv: no such file or directory

goroutine 1 [running]:
github.com/argoproj/argo-cd/util/assets.init.0()
	/go/src/github.com/argoproj/argo-cd/util/assets/assets.go:19 +0x441
```

Thank you for your help! :)

**Comment by jannfis** [comment]
Hi askhari, have a look at PR #2041 :)

**Comment by askhari** [comment]
Hi @jannfis,

That was fast! I didn't realize that there were already a pull request solving this. Sorry.
Meanwhile we are using v1.1.1 .

Thank you very much!
