### ISSUE TITLE
argocd-server panic: interface conversion: runtime.Object is *v1.Status, not *v1alpha1.Application

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#2105]
Seeing this in some environments:

```
panic: interface conversion: runtime.Object is *v1.Status, not *v1alpha1.Application

goroutine 272460 [running]:
github.com/argoproj/argo-cd/server/application.(*Server).Watch.func2(0x1e41c80, 0xc001879f80, 0xc00086db80, 0xc0016d3ef0, 0xc001366300)
	/go/src/github.com/argoproj/argo-cd/server/application/application.go:495 +0x1ec
created by github.com/argoproj/argo-cd/server/application.(*Server).Watch
	/go/src/github.com/argoproj/argo-cd/server/application/application.go:493 +0x3fb
```

**Comment by jessesuen** [comment]
Happening in v1.1

**Comment by alexec** [comment]
line 495
```
a := *next.Object.(*appv1.Application)
```

**Comment by alexec** [comment]
Could change to 
```golang
			a, ok := next.Object.(*appv1.Application)
			if ok {
				_ = sendIfPermitted(*a, next.Type)
			}
```
But is this masking an underlying problem.
