### ISSUE TITLE
v1.2.0-rc1 Applications List View doesn't work

### ISSUE THREAD

**Issue by leominov** [argoproj/argo-cd#2174]
**Describe the bug**

List View on Applications page doesn't work. After removing key from Local Storage you will back to default view. Tested on Safari 12.1.2.

**To Reproduce**

1. Go to `/applications`
2. Be sure you have some added applications
3. Click on List View button (near Logout, see first screenshot)
4. See error (see second screenshot)
5. Reload page
6. Same error with another stacktrace (see logs)

**Expected behavior**

List View works fine :)

**Screenshots**

1. https://monosnap.com/direct/lB7aZScNGZV3fWENCBQcjrYA623G5v
2. https://monosnap.com/direct/DrqmRE7VBS0GSDYKwBRxzeizKKCBdI

**Version**

```shell
argocd-server: v1.2.0-rc1+2c691a8
  BuildDate: 2019-08-06T17:51:35Z
  GitCommit: 2c691a874b7acd708712396691ea2b050846229c
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: 0.13.1
```

**Logs**

```
[native code]
https://HOSTNAME/main.3ee201ab7946de8ec9c7.js:18:202020
map@[native code]
https://HOSTNAME/main.3ee201ab7946de8ec9c7.js:18:200771
Pi@https://HOSTNAME/main.3ee201ab7946de8ec9c7.js:86:69771
Ja@https://HOSTNAME/main.3ee201ab7946de8ec9c7.js:86:91583
Ga@https://HOSTNAME/main.3ee201ab7946de8ec9c7.js:86:91967
As@https://HOSTNAME/main.3ee201ab7946de8ec9c7.js:86:98876
Ls@https://HOSTNAME/main.3ee201ab7946de8ec9c7.js:86:98256
ks@https://HOSTNAME/main.3ee201ab7946de8ec9c7.js:86:97277
Za@https://HOSTNAME/main.3ee201ab7946de8ec9c7.js:86:96151
enqueueSetState@https://HOSTNAME/main.3ee201ab7946de8ec9c7.js:86:45413
setState@https://HOSTNAME/main.3ee201ab7946de8ec9c7.js:78:2145
__tryOrUnsub@https://HOSTNAME/main.3ee201ab7946de8ec9c7.js:7:4712
next@https://HOSTNAME/main.3ee201ab7946de8ec9c7.js:7:3998
_next@https://HOSTNAME/main.3ee201ab7946de8ec9c7.js:7:3041
next@https://HOSTNAME/main.3ee201ab7946de8ec9c7.js:7:2713
notifyNext@https://HOSTNAME/main.3ee201ab7946de8ec9c7.js:7:90876
_next@https://HOSTNAME/main.3ee201ab7946de8ec9c7.js:95:154758
next@https://HOSTNAME/main.3ee201ab7946de8ec9c7.js:7:2713
notifyNext@https://HOSTNAME/main.3ee201ab7946de8ec9c7.js:7:90876
_next@https://HOSTNAME/main.3ee201ab7946de8ec9c7.js:95:154758
next@https://HOSTNAME/main.3ee201ab7946de8ec9c7.js:7:2713
subscribeToResult@https://HOSTNAME/main.3ee201ab7946de8ec9c7.js:7:12458
_innerSub@https://HOSTNAME/main.3ee201ab7946de8ec9c7.js:7:90617
_tryNext@https://HOSTNAME/main.3ee201ab7946de8ec9c7.js:7:90542
_next@https://HOSTNAME/main.3ee201ab7946de8ec9c7.js:7:90364
next@https://HOSTNAME/main.3ee201ab7946de8ec9c7.js:7:2713
_subscribe@https://HOSTNAME/main.3ee201ab7946de8ec9c7.js:7:53542
_trySubscribe@https://HOSTNAME/main.3ee201ab7946de8ec9c7.js:1:56278
subscribe@https://HOSTNAME/main.3ee201ab7946de8ec9c7.js:1:56110
subscribe@https://HOSTNAME/main.3ee201ab7946de8ec9c7.js:1:56016
_innerSub@https://HOSTNAME/main.3ee201ab7946de8ec9c7.js:7:90617
_tryNext@https://HOSTNAME/main.3ee201ab7946de8ec9c7.js:7:90542
_next@https://HOSTNAME/main.3ee201ab7946de8ec9c7.js:7:90364
next@https://HOSTNAME/main.3ee201ab7946de8ec9c7.js:7:2713
https://HOSTNAME/main.3ee201ab7946de8ec9c7.js:38:270913
promiseReactionJob@[native code]
```

**Comment by leominov** [comment]
More informative trace from Google Chrome `76.0.3809.100 (Official Build) (64-bit)`:

```
TypeError: Failed to construct 'URL': Invalid URL
    at https://HOSTNAME/main.3ee201ab7946de8ec9c7.js:18:201965
    at Array.map (<anonymous>)
    at https://HOSTNAME/main.3ee201ab7946de8ec9c7.js:18:200720
    at Pi (https://HOSTNAME/main.3ee201ab7946de8ec9c7.js:86:69528)
    at Ja (https://HOSTNAME/main.3ee201ab7946de8ec9c7.js:86:91339)
    at Ga (https://HOSTNAME/main.3ee201ab7946de8ec9c7.js:86:91723)
    at As (https://HOSTNAME/main.3ee201ab7946de8ec9c7.js:86:98632)
    at Ls (https://HOSTNAME/main.3ee201ab7946de8ec9c7.js:86:98012)
    at ks (https://HOSTNAME/main.3ee201ab7946de8ec9c7.js:86:97033)
    at Za (https://HOSTNAME/main.3ee201ab7946de8ec9c7.js:86:95907)
```

**Comment by leominov** [comment]
Looks like problem with parsing URL from Application. In my case all links is `git@HOSTNAME:path/repo.git`.

**Comment by leominov** [comment]
Line in source code:
https://github.com/argoproj/argo-cd/blob/dacdeb6025ec30c845aed9e87546bbeaab0732a2/ui/src/app/applications/components/applications-list/applications-table.tsx#L13

**Comment by alexmt** [comment]
Thank you for catching it @leominov ! PR with the fix: https://github.com/argoproj/argo-cd/pull/2175 .

**Comment by alexmt** [comment]
Look like it is time for UI e2e tests

**Comment by leominov** [comment]
Yeah.
Thanks for fix :)
