### ISSUE TITLE
Controller panics due to nil pointer error

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#2290]
**Describe the bug**

Application controller is crashing after user upgraded Argo CD to v1.2.0

**Version**

```shell
v1.2.0
```

**Logs**

```
time="2019-09-11T01:37:16Z" level=info msg="Refreshing app status (comparison expired. reconciledAt: 2019-09-10 01:07:38 +0000 UTC, expiry: 3m0s), level (2)" application=august-infrastructure-maintainer
W0911 01:37:16.084849       1 listers.go:77] can not retrieve list of objects using index : Index with name namespace does not exist
time="2019-09-11T01:37:16Z" level=info msg="Reconciliation completed" application=august-infrastructure-maintainer fields.level=2 time_ms=0.029479
time="2019-09-11T01:37:16Z" level=error msg="Recovered from panic: runtime error: invalid memory address or nil pointer dereference\ngoroutine 86 [running]:\nruntime/debug.Stack(0xc000549890, 0x1846280, 0x2cea910)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x9d\ngithub.com/argoproj/argo-cd/controller.(*ApplicationController).processAppRefreshQueueItem.func1(0xc000184480, 0x17b6f00, 0xc0032298d0)\n\t/go/src/github.com/argoproj/argo-cd/controller/appcontroller.go:727 +0x85\npanic(0x1846280, 0x2cea910)\n\t/usr/local/go/src/runtime/panic.go:522 +0x1b5\ngithub.com/argoproj/argo-cd/controller.(*ApplicationController).processAppRefreshQueueItem(0xc000184480, 0x1)\n\t/go/src/github.com/argoproj/argo-cd/controller/appcontroller.go:792 +0x4ef\ngithub.com/argoproj/argo-cd/controller.(*ApplicationController).Run.func3()\n\t/go/src/github.com/argoproj/argo-cd/controller/appcontroller.go:405 +0x36\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc0004bb990)\n\t/go/src/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x54\nk8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0004bb990, 0x3b9aca00, 0x0, 0xffffffffffffff01, 0xc000474240)\n\t/go/src/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8\nk8s.io/apimachinery/pkg/util/wait.Until(0xc0004bb990, 0x3b9aca00, 0xc000474240)\n\t/go/src/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d\ncreated by github.com/argoproj/argo-cd/controller.(*ApplicationController).Run\n\t/go/src/github.com/argoproj/argo-cd/controller/appcontroller.go:404 +0x2a9\n"
```

**Comment by alexec** [comment]
@alexmt is this fixed please?
