### ISSUE TITLE
Panic in application controller Concurrent map iteration and map write

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#2310]
**Describe the bug**

Panic in the application controller

```
fatal error: concurrent map iteration and map write

goroutine 141 [running]:
runtime.throw(0x1a7fe7c, 0x26)
	/usr/local/go/src/runtime/panic.go:617 +0x72 fp=0xc00be0ae40 sp=0xc00be0ae10 pc=0x42cd92
runtime.mapiternext(0xc00be0af90)
	/usr/local/go/src/runtime/map.go:860 +0x597 fp=0xc00be0aec8 sp=0xc00be0ae40 pc=0x40ebf7
github.com/argoproj/argo-cd/controller/cache.(*clusterInfo).getManagedLiveObjs(0xc000e06150, 0xc01672ae00, 0xc0136dae80, 0x5, 0x8, 0xc00034fb00, 0x0, 0x0, 0x0)
	/go/src/github.com/argoproj/argo-cd/controller/cache/cluster.go:372 +0x100 fp=0xc00be0b000 sp=0xc00be0aec8 pc=0x14b61a0
github.com/argoproj/argo-cd/controller/cache.(*liveStateCache).GetManagedLiveObjs(0xc0004ab500, 0xc01672ae00, 0xc0136dae80, 0x5, 0x8, 0x0, 0x4f, 0x0)
	/go/src/github.com/argoproj/argo-cd/controller/cache/cache.go:178 +0xc5 fp=0xc00be0b058 sp=0xc00be0b000 pc=0x14b2fc5
github.com/argoproj/argo-cd/controller.(*appStateManager).CompareAppState(0xc0005e2000, 0xc01672ae00, 0xc017c38420, 0x28, 0xc012a8f0e0, 0x45, 0xc00aa931e0, 0x15, 0x0, 0x0, ...)
	/go/src/github.com/argoproj/argo-cd/controller/state.go:325 +0xba8 fp=0xc00be0bb10 sp=0xc00be0b058 pc=0x1657108
github.com/argoproj/argo-cd/controller.(*ApplicationController).processAppRefreshQueueItem(0xc000412120, 0x1)
	/go/src/github.com/argoproj/argo-cd/controller/appcontroller.go:695 +0x677 fp=0xc00be0be80 sp=0xc00be0bb10 pc=0x164f4b7
github.com/argoproj/argo-cd/controller.(*ApplicationController).Run.func3()
	/go/src/github.com/argoproj/argo-cd/controller/appcontroller.go:299 +0x36 fp=0xc00be0bea8 sp=0xc00be0be80 pc=0x1665ef6
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc00124a310)
	/go/src/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x54 fp=0xc00be0bee0 sp=0xc00be0bea8 pc=0x10723f4
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00124a310, 0x3b9aca00, 0x0, 0x3a2265756c617601, 0xc0005ca120)
	/go/src/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8 fp=0xc00be0bf90 sp=0xc00be0bee0 pc=0x1071918
k8s.io/apimachinery/pkg/util/wait.Until(0xc00124a310, 0x3b9aca00, 0xc0005ca120)
	/go/src/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d fp=0xc00be0bfc8 sp=0xc00be0bf90 pc=0x107180d
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc00be0bfd0 sp=0xc00be0bfc8 pc=0x4599e1
created by github.com/argoproj/argo-cd/controller.(*ApplicationController).Run
	/go/src/github.com/argoproj/argo-cd/controller/appcontroller.go:298 +0x2a9

goroutine 1 [select (no cases), 5760 minutes]:
main.newCommand.func1(0xc000399900, 0xc00012efc0, 0x0, 0xc, 0x0, 0x0)
	/go/src/github.com/argoproj/argo-cd/cmd/argocd-application-controller/main.go:98 +0x7dc
github.com/spf13/cobra.(*Command).execute(0xc000399900, 0xc00003a350, 0xc, 0xc, 0xc000399900, 0xc00003a350)
	/go/src/github.com/spf13/cobra/command.go:762 +0x465
github.com/spf13/cobra.(*Command).ExecuteC(0xc000399900, 0x26, 0xc000607f88, 0x40584f)
	/go/src/github.com/spf13/cobra/command.go:852 +0x2ec
github.com/spf13/cobra.(*Command).Execute(...)
	/go/src/github.com/spf13/cobra/command.go:800
main.main()
	/go/src/github.com/argoproj/argo-cd/cmd/argocd-application-controller/main.go:118 +0x2c
```

Full stack trace: [2310.txt](https://github.com/argoproj/argo-cd/files/3611846/2310.txt)

**Version**

```shell
v1.2.1
```

**Comment by alexmt** [comment]
Fixed in 1.4.0
