### ISSUE TITLE
"Unable to create K8s REST config: invalid configuration" error when running using make start

### ISSUE THREAD

**Issue by adamjohnson01** [argoproj/argo-cd#2379]
**Describe the bug**
The api-server terminates when it is not running inside a kubernetes cluster. **To Reproduce**

1. make && make start 
2. go to http://localhost:8080

**Screenshots**
<img width="359" alt="Screenshot 2019-09-29 at 13 07 39" src="https://user-images.githubusercontent.com/12121539/65832351-36a3a700-e2ba-11e9-85ed-1173941b5553.png">

**Expected behavior**

The ui should load

**Version**
master branch build

**Logs**

```
13:05:50  api-server | INFO[0015] received unary call /cluster.SettingsService/Get  grpc.method=Get grpc.request.claims=null grpc.request.content= grpc.service=cluster.SettingsService grpc.start_time="2019-09-29T13:05:50+01:00" span.kind=server system=grpc
13:05:50  api-server | INFO[0015] finished unary call with code OK              grpc.code=OK grpc.method=Get grpc.service=cluster.SettingsService grpc.start_time="2019-09-29T13:05:50+01:00" grpc.time_ms=1.173 span.kind=server system=grpc
13:05:50  api-server | INFO[0015] received unary call /cluster.SettingsService/Get  grpc.method=Get grpc.request.claims=null grpc.request.content= grpc.service=cluster.SettingsService grpc.start_time="2019-09-29T13:05:50+01:00" span.kind=server system=grpc
13:05:50  api-server | INFO[0015] finished unary call with code OK              grpc.code=OK grpc.method=Get grpc.service=cluster.SettingsService grpc.start_time="2019-09-29T13:05:50+01:00" grpc.time_ms=0.379 span.kind=server system=grpc
13:05:50  api-server | INFO[0015] received unary call /cluster.ClusterService/List  grpc.method=List grpc.request.claims=null grpc.request.content= grpc.service=cluster.ClusterService grpc.start_time="2019-09-29T13:05:50+01:00" span.kind=server system=grpc
13:05:50  api-server | W0929 13:05:50.165740   36826 listers.go:77] can not retrieve list of objects using index : Index with name namespace does not exist
13:05:50  api-server | panic: Unable to create K8s REST config: invalid configuration: no configuration has been provided
13:05:50  api-server | goroutine 256 [running]:
13:05:50  api-server | github.com/argoproj/argo-cd/pkg/apis/application/v1alpha1.(*Cluster).RESTConfig(0xc0008ca5a0, 0xc0008ca5a0)
13:05:50  api-server |    /Users/a.johnson/go/src/github.com/argoproj/argo-cd/pkg/apis/application/v1alpha1/types.go:1836 +0x7ed
13:05:50  api-server | github.com/argoproj/argo-cd/server/cluster.(*Server).List.func1(0x1, 0x2963e00, 0xc00067bb60)
13:05:50  api-server |    /Users/a.johnson/go/src/github.com/argoproj/argo-cd/server/cluster/cluster.go:105 +0x137
13:05:50  api-server | github.com/argoproj/argo-cd/util.RunAllAsync.func2(0xc00067bb60, 0xc0003ee2d0, 0xc000a68c10, 0x1)
13:05:50  api-server |    /Users/a.johnson/go/src/github.com/argoproj/argo-cd/util/util.go:148 +0x5a
13:05:50  api-server | created by github.com/argoproj/argo-cd/util.RunAllAsync
13:05:50  api-server |    /Users/a.johnson/go/src/github.com/argoproj/argo-cd/util/util.go:146 +0xf9
13:05:50  api-server | exit status 2
13:05:50  api-server | Terminating api-server
```

**Comment by alexec** [comment]
Sounds like a good idea and a simple change.
