### ISSUE TITLE
nil pointer dereference in application controller

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#271]
```
time="2018-06-06T18:22:53-07:00" level=error msg="Recovered from panic: runtime error: invalid memory address or nil pointer dereference
goroutine 461 [running]:
runtime/debug.Stack(0xc4210530e8, 0x20e8960, 0x31bc220)
\t/usr/local/Cellar/go/1.10/libexec/src/runtime/debug/stack.go:24 +0xa7
github.com/argoproj/argo-cd/controller.(*ApplicationController).processRequestedAppOperation.func1(0xc421053cf8, 0xc421d78160, 0xc421658580)
\t/Users/amatyushentsev/root/go/src/github.com/argoproj/argo-cd/controller/appcontroller.go:317 +0x77
panic(0x20e8960, 0x31bc220)
\t/usr/local/Cellar/go/1.10/libexec/src/runtime/panic.go:505 +0x229
github.com/argoproj/argo-cd/util/diff.ThreeWayDiff(0xc42145e260, 0x0, 0xc421bfc448, 0xc421b31440)
\t/Users/amatyushentsev/root/go/src/github.com/argoproj/argo-cd/util/diff/diff.go:63 +0x7f
github.com/argoproj/argo-cd/util/diff.Diff(0x0, 0xc421bfc448, 0xc4211fc780)
\t/Users/amatyushentsev/root/go/src/github.com/argoproj/argo-cd/util/diff/diff.go:33 +0x56
github.com/argoproj/argo-cd/util/diff.DiffArray(0xc4211fc500, 0x4, 0x4, 0xc4211fc520, 0x4, 0x4, 0x2, 0x4, 0x0)
\t/Users/amatyushentsev/root/go/src/github.com/argoproj/argo-cd/util/diff/diff.go:164 +0xea
github.com/argoproj/argo-cd/controller.(*KsonnetAppStateManager).CompareAppState(0xc420220ec0, 0xc421658580, 0x0, 0x0, 0x0, 0x0)
\t/Users/amatyushentsev/root/go/src/github.com/argoproj/argo-cd/controller/state.go:181 +0x11e2
github.com/argoproj/argo-cd/controller.(*KsonnetAppStateManager).syncAppResources(0xc420220ec0, 0xc421658580, 0xc421050000, 0x231ac36, 0x22)
\t/Users/amatyushentsev/root/go/src/github.com/argoproj/argo-cd/controller/state.go:365 +0xdd
github.com/argoproj/argo-cd/controller.(*KsonnetAppStateManager).SyncAppState(0xc420220ec0, 0xc421658580, 0x0, 0x0, 0x0, 0x22f0000, 0x7)
\t/Users/amatyushentsev/root/go/src/github.com/argoproj/argo-cd/controller/state.go:300 +0xd5
github.com/argoproj/argo-cd/controller.(*ApplicationController).processRequestedAppOperation(0xc421d78160, 0xc421658580)
\t/Users/amatyushentsev/root/go/src/github.com/argoproj/argo-cd/controller/appcontroller.go:349 +0x571
github.com/argoproj/argo-cd/controller.(*ApplicationController).processAppOperationQueueItem(0xc421d78160, 0x1)
\t/Users/amatyushentsev/root/go/src/github.com/argoproj/argo-cd/controller/appcontroller.go:237 +0x242
github.com/argoproj/argo-cd/controller.(*ApplicationController).Run.func2()
\t/Users/amatyushentsev/root/go/src/github.com/argoproj/argo-cd/controller/appcontroller.go:110 +0x36
github.com/argoproj/argo-cd/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc4201d51a0)
\t/Users/amatyushentsev/root/go/src/github.com/argoproj/argo-cd/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x54
github.com/argoproj/argo-cd/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc4201d51a0, 0x3b9aca00, 0x0, 0x1, 0xc421bec000)
\t/Users/amatyushentsev/root/go/src/github.com/argoproj/argo-cd/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0xbd
github.com/argoproj/argo-cd/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc4201d51a0, 0x3b9aca00, 0xc421bec000)
\t/Users/amatyushentsev/root/go/src/github.com/argoproj/argo-cd/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by github.com/argoproj/argo-cd/controller.(*ApplicationController).Run
\t/Users/amatyushentsev/root/go/src/github.com/argoproj/argo-cd/controller/appcontroller.go:109 +0x28c
"
```

**Comment by alexmt** [comment]
Fixed
