### ISSUE TITLE
panic adding credentials template

### ISSUE THREAD

**Issue by davidkarlsen** [argoproj/argo-cd#2974]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

When adding repo and clicking store as credentials template it panics:

```
argo-cd-argocd-server-7c74d884b9-pjjvp server time="2020-01-14T12:32:45Z" level=error msg="Recovered from panic: runtime error: invalid memory address or nil pointer dereference\ngoroutine 3635 [running]:\nruntime/debug.Stack(0xc000b550b8, 0x1e35e00, 0x3b4dad0)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x9d\ngithub.com/argoproj/argo-cd/util/grpc.PanicLoggerUnaryServerInterceptor.func1.1(0xc0001511d0, 0xc000b553c0)\n\t/go/src/github.com/argoproj/argo-cd/util/grpc/grpc.go:23 +0x6e\npanic(0x1e35e00, 0x3b4dad0)\n\t/usr/local/go/src/runtime/panic.go:522 +0x1b5\ngithub.com/argoproj/argo-cd/server/repocreds.(*Server).CreateRepositoryCredentials(0xc0008e8e70, 0x252d680, 0xc000d1e9c0, 0xc000d1e3f0, 0xc0008e8e70, 0xc00104e880, 0x7f0a2fb35d98)\n\t/go/src/github.com/argoproj/argo-cd/server/repocreds/repocreds.go:94 +0x254\ngithub.com/argoproj/argo-cd/pkg/apiclient/repocreds._RepoCredsService_CreateRepositoryCredentials_Handler.func1(0x252d680, 0xc000d1e9c0, 0x1ffca60, 0xc000d1e3f0, 0x442b8c, 0xc000b55320, 0x42bb0f, 0xc00104e8b0)\n\t/go/src/github.com/argoproj/argo-cd/pkg/apiclient/repocreds/repocreds.pb.go:455 +0x86\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x252d680, 0xc000d1e9c0, 0x1ffca60, 0xc000d1e3f0, 0x48, 0xc000dfc8c0, 0xffffffffffffffff, 0xc000b553d8)\n\t/go/src/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:31 +0x111\ngithub.com/argoproj/argo-cd/util/grpc.PanicLoggerUnaryServerInterceptor.func1(0x252d680, 0xc000d1e9c0, 0x1ffca60, 0xc000d1e3f0, 0xc000d57fa0, 0xc000dfc280, 0x0, 0x0, 0x0, 0x0)\n\t/go/src/github.com/argoproj/argo-cd/util/grpc/grpc.go:27 +0x97\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x252d680, 0xc000d1e9c0, 0x1ffca60, 0xc000d1e3f0, 0xc000b55488, 0x4ab7e8b0, 0xcfe4b486cc5c2657, 0x10000c000b55450)\n\t/go/src/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:34 +0x99\ngithub.com/argoproj/argo-cd/util/grpc.ErrorCodeUnaryServerInterceptor.func1(0x252d680, 0xc000d1e9c0, 0x1ffca60, 0xc000d1e3f0, 0xc000d57fa0, 0xc000dfc280, 0x1df2ac0, 0xc0008e8c60, 0x2168ced, 0x37)\n\t/go/src/github.com/argoproj/argo-cd/util/grpc/errors.go:64 +0x55\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x252d680, 0xc000d1e9c0, 0x1ffca60, 0xc000d1e3f0, 0x1eadb80, 0xc0008e8e70, 0x3ba3d00, 0x0)\n\t/go/src/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:34 +0x99\ngithub.com/argoproj/argo-cd/util/grpc.PayloadUnaryServerInterceptor.func1(0x252d680, 0xc000d1e9c0, 0x1ffca60, 0xc000d1e3f0, 0xc000d57fa0, 0xc000dfc280, 0x21101b8, 0xc000d22d20, 0xc000d22d20, 0x1d82320)\n\t/go/src/github.com/argoproj/argo-cd/util/grpc/logging.go:74 +0x24f\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x252d680, 0xc000d1e9c0, 0x1ffca60, 0xc000d1e3f0, 0x1f027a0, 0xc0000d32f8, 0x252d680, 0xc000d1e9c0)\n\t/go/src/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:34 +0x99\ngithub.com/argoproj/argo-cd/util/grpc.UserAgentUnaryServerInterceptor.func1(0x252d680, 0xc000d1e9c0, 0x1ffca60, 0xc000d1e3f0, 0xc000d57fa0, 0xc000dfc280, 0xc000d1e4e0, 0x252d680, 0xc000d1e9c0, 0x0)\n\t/go/src/github.com/argoproj/argo-cd/util/grpc/useragent.go:22 +0xa2\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x252d680, 0xc000d1e9c0, 0x1ffca60, 0xc000d1e3f0, 0x0, 0x0, 0x0, 0x0)\n\t/go/src/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:34 +0x99\ngithub.com/grpc-ecosystem/go-grpc-middleware/auth.UnaryServerInterceptor.func1(0x252d680, 0xc000d1e4e0, 0x1ffca60, 0xc000d1e3f0, 0xc000d57fa0, 0xc000dfc280, 0x5, 0x2168cee, 0x1a, 0x2168d09)\n\t/go/src/github.com/grpc-ecosystem/go-grpc-middleware/auth/auth.go:46 +0x108\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x252d680, 0xc000d1e4e0, 0x1ffca60, 0xc000d1e3f0, 0x37, 0xc000dfc3c0, 0x0, 0x0)\n\t/go/src/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:34 +0x99\ngithub.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).UnaryServerInterceptor.func1(0x252d680, 0xc000d1e4e0, 0x1ffca60, 0xc000d1e3f0, 0xc000d57fa0, 0xc000dfc280, 0x0, 0x0, 0x0, 0x0)\n\t/go/src/github.com/grpc-ecosystem/go-grpc-prometheus/server_metrics.go:107 +0xad\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x252d680, 0xc000d1e4e0, 0x1ffca60, 0xc000d1e3f0, 0x37, 0xbf7f8b1b6b90f4c8, 0x104c942d32b, 0x3b7d3a0)\n\t/go/src/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:34 +0x99\ngithub.com/grpc-ecosystem/go-grpc-middleware/logging/logrus.UnaryServerInterceptor.func1(0x252d680, 0xc000d1e3c0, 0x1ffca60, 0xc000d1e3f0, 0xc000d57fa0, 0xc000dfc280, 0x50, 0x48, 0x1fb9300, 0x0)\n\t/go/src/github.com/grpc-ecosystem/go-grpc-middleware/logging/logrus/server_interceptors.go:32 +0x110\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x252d680, 0xc000d1e3c0, 0x1ffca60, 0xc000d1e3f0, 0x7f0a2fb35d98, 0x0, 0xc001280b88, 0x40b899)\n\t/go/src/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:34 +0x99\ngithub.com/argoproj/argo-cd/server.bug21955WorkaroundInterceptor(0x252d680, 0xc000d1e3c0, 0x1ffca60, 0xc000d1e3f0, 0xc000d57fa0, 0xc000dfc280, 0xc000d1e3c0, 0xc000d57f80, 0xc001280bb8, 0x40c128)\n\t/go/src/github.com/argoproj/argo-cd/server/server.go:904 +0x15b\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1(0x252d680, 0xc000d1e3c0, 0x1ffca60, 0xc000d1e3f0, 0xc000d57fa0, 0xc000d57fc0, 0xc001280c28, 0x4e1dfa, 0x1f86480, 0xc000d1e3c0)\n\t/go/src/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:39 +0x153\ngithub.com/argoproj/argo-cd/pkg/apiclient/repocreds._RepoCredsService_CreateRepositoryCredentials_Handler(0x1eadb80, 0xc0008e8e70, 0x252d680, 0xc000d1e3c0, 0xc000685f80, 0xc0008e8d50, 0x252d680, 0xc000d1e3c0, 0xc0008394c0, 0x9b6768)\n\t/go/src/github.com/argoproj/argo-cd/pkg/apiclient/repocreds/repocreds.pb.go:457 +0x158\ngoogle.golang.org/grpc.(*Server).processUnaryRPC(0xc000380d80, 0x255ce60, 0xc000ae6c00, 0xc000eaa800, 0xc0008e9200, 0x3b5bb18, 0x0, 0x0, 0x0)\n\t/go/src/google.golang.org/grpc/server.go:982 +0x4c3\ngoogle.golang.org/grpc.(*Server).handleStream(0xc000380d80, 0x255ce60, 0xc000ae6c00, 0xc000eaa800, 0x0)\n\t/go/src/google.golang.org/grpc/server.go:1208 +0x12b5\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0008a48d0, 0xc000380d80, 0x255ce60, 0xc000ae6c00, 0xc000eaa800)\n\t/go/src/google.golang.org/grpc/server.go:686 +0x9f\ncreated by google.golang.org/grpc.(*Server).serveStreams.func1\n\t/go/src/google.golang.org/grpc/server.go:684 +0xa1\n"
argo-cd-argocd-server-7c74d884b9-pjjvp server time="2020-01-14T12:32:45Z" level=error msg="finished unary call with code Internal" error="rpc error: code = Internal desc = runtime error: invalid memory address or nil pointer dereference" grpc.code=Internal grpc.method=CreateRepositoryCredentials grpc.service=repocreds.RepoCredsService grpc.start_time="2020-01-14T12:32:45Z" grpc.time_ms=22.299 span.kind=server system=grpc
```

**To Reproduce**

Add repo and store as template.

**Expected behavior**

Should save ok

**Screenshots**

```
argo-cd-argocd-server-7c74d884b9-pjjvp server time="2020-01-14T12:32:45Z" level=error msg="Recovered from panic: runtime error: invalid memory address or nil pointer dereference\ngoroutine 3635 [running]:\nruntime/debug.Stack(0xc000b550b8, 0x1e35e00, 0x3b4dad0)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x9d\ngithub.com/argoproj/argo-cd/util/grpc.PanicLoggerUnaryServerInterceptor.func1.1(0xc0001511d0, 0xc000b553c0)\n\t/go/src/github.com/argoproj/argo-cd/util/grpc/grpc.go:23 +0x6e\npanic(0x1e35e00, 0x3b4dad0)\n\t/usr/local/go/src/runtime/panic.go:522 +0x1b5\ngithub.com/argoproj/argo-cd/server/repocreds.(*Server).CreateRepositoryCredentials(0xc0008e8e70, 0x252d680, 0xc000d1e9c0, 0xc000d1e3f0, 0xc0008e8e70, 0xc00104e880, 0x7f0a2fb35d98)\n\t/go/src/github.com/argoproj/argo-cd/server/repocreds/repocreds.go:94 +0x254\ngithub.com/argoproj/argo-cd/pkg/apiclient/repocreds._RepoCredsService_CreateRepositoryCredentials_Handler.func1(0x252d680, 0xc000d1e9c0, 0x1ffca60, 0xc000d1e3f0, 0x442b8c, 0xc000b55320, 0x42bb0f, 0xc00104e8b0)\n\t/go/src/github.com/argoproj/argo-cd/pkg/apiclient/repocreds/repocreds.pb.go:455 +0x86\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x252d680, 0xc000d1e9c0, 0x1ffca60, 0xc000d1e3f0, 0x48, 0xc000dfc8c0, 0xffffffffffffffff, 0xc000b553d8)\n\t/go/src/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:31 +0x111\ngithub.com/argoproj/argo-cd/util/grpc.PanicLoggerUnaryServerInterceptor.func1(0x252d680, 0xc000d1e9c0, 0x1ffca60, 0xc000d1e3f0, 0xc000d57fa0, 0xc000dfc280, 0x0, 0x0, 0x0, 0x0)\n\t/go/src/github.com/argoproj/argo-cd/util/grpc/grpc.go:27 +0x97\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x252d680, 0xc000d1e9c0, 0x1ffca60, 0xc000d1e3f0, 0xc000b55488, 0x4ab7e8b0, 0xcfe4b486cc5c2657, 0x10000c000b55450)\n\t/go/src/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:34 +0x99\ngithub.com/argoproj/argo-cd/util/grpc.ErrorCodeUnaryServerInterceptor.func1(0x252d680, 0xc000d1e9c0, 0x1ffca60, 0xc000d1e3f0, 0xc000d57fa0, 0xc000dfc280, 0x1df2ac0, 0xc0008e8c60, 0x2168ced, 0x37)\n\t/go/src/github.com/argoproj/argo-cd/util/grpc/errors.go:64 +0x55\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x252d680, 0xc000d1e9c0, 0x1ffca60, 0xc000d1e3f0, 0x1eadb80, 0xc0008e8e70, 0x3ba3d00, 0x0)\n\t/go/src/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:34 +0x99\ngithub.com/argoproj/argo-cd/util/grpc.PayloadUnaryServerInterceptor.func1(0x252d680, 0xc000d1e9c0, 0x1ffca60, 0xc000d1e3f0, 0xc000d57fa0, 0xc000dfc280, 0x21101b8, 0xc000d22d20, 0xc000d22d20, 0x1d82320)\n\t/go/src/github.com/argoproj/argo-cd/util/grpc/logging.go:74 +0x24f\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x252d680, 0xc000d1e9c0, 0x1ffca60, 0xc000d1e3f0, 0x1f027a0, 0xc0000d32f8, 0x252d680, 0xc000d1e9c0)\n\t/go/src/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:34 +0x99\ngithub.com/argoproj/argo-cd/util/grpc.UserAgentUnaryServerInterceptor.func1(0x252d680, 0xc000d1e9c0, 0x1ffca60, 0xc000d1e3f0, 0xc000d57fa0, 0xc000dfc280, 0xc000d1e4e0, 0x252d680, 0xc000d1e9c0, 0x0)\n\t/go/src/github.com/argoproj/argo-cd/util/grpc/useragent.go:22 +0xa2\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x252d680, 0xc000d1e9c0, 0x1ffca60, 0xc000d1e3f0, 0x0, 0x0, 0x0, 0x0)\n\t/go/src/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:34 +0x99\ngithub.com/grpc-ecosystem/go-grpc-middleware/auth.UnaryServerInterceptor.func1(0x252d680, 0xc000d1e4e0, 0x1ffca60, 0xc000d1e3f0, 0xc000d57fa0, 0xc000dfc280, 0x5, 0x2168cee, 0x1a, 0x2168d09)\n\t/go/src/github.com/grpc-ecosystem/go-grpc-middleware/auth/auth.go:46 +0x108\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x252d680, 0xc000d1e4e0, 0x1ffca60, 0xc000d1e3f0, 0x37, 0xc000dfc3c0, 0x0, 0x0)\n\t/go/src/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:34 +0x99\ngithub.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).UnaryServerInterceptor.func1(0x252d680, 0xc000d1e4e0, 0x1ffca60, 0xc000d1e3f0, 0xc000d57fa0, 0xc000dfc280, 0x0, 0x0, 0x0, 0x0)\n\t/go/src/github.com/grpc-ecosystem/go-grpc-prometheus/server_metrics.go:107 +0xad\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x252d680, 0xc000d1e4e0, 0x1ffca60, 0xc000d1e3f0, 0x37, 0xbf7f8b1b6b90f4c8, 0x104c942d32b, 0x3b7d3a0)\n\t/go/src/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:34 +0x99\ngithub.com/grpc-ecosystem/go-grpc-middleware/logging/logrus.UnaryServerInterceptor.func1(0x252d680, 0xc000d1e3c0, 0x1ffca60, 0xc000d1e3f0, 0xc000d57fa0, 0xc000dfc280, 0x50, 0x48, 0x1fb9300, 0x0)\n\t/go/src/github.com/grpc-ecosystem/go-grpc-middleware/logging/logrus/server_interceptors.go:32 +0x110\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x252d680, 0xc000d1e3c0, 0x1ffca60, 0xc000d1e3f0, 0x7f0a2fb35d98, 0x0, 0xc001280b88, 0x40b899)\n\t/go/src/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:34 +0x99\ngithub.com/argoproj/argo-cd/server.bug21955WorkaroundInterceptor(0x252d680, 0xc000d1e3c0, 0x1ffca60, 0xc000d1e3f0, 0xc000d57fa0, 0xc000dfc280, 0xc000d1e3c0, 0xc000d57f80, 0xc001280bb8, 0x40c128)\n\t/go/src/github.com/argoproj/argo-cd/server/server.go:904 +0x15b\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1(0x252d680, 0xc000d1e3c0, 0x1ffca60, 0xc000d1e3f0, 0xc000d57fa0, 0xc000d57fc0, 0xc001280c28, 0x4e1dfa, 0x1f86480, 0xc000d1e3c0)\n\t/go/src/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:39 +0x153\ngithub.com/argoproj/argo-cd/pkg/apiclient/repocreds._RepoCredsService_CreateRepositoryCredentials_Handler(0x1eadb80, 0xc0008e8e70, 0x252d680, 0xc000d1e3c0, 0xc000685f80, 0xc0008e8d50, 0x252d680, 0xc000d1e3c0, 0xc0008394c0, 0x9b6768)\n\t/go/src/github.com/argoproj/argo-cd/pkg/apiclient/repocreds/repocreds.pb.go:457 +0x158\ngoogle.golang.org/grpc.(*Server).processUnaryRPC(0xc000380d80, 0x255ce60, 0xc000ae6c00, 0xc000eaa800, 0xc0008e9200, 0x3b5bb18, 0x0, 0x0, 0x0)\n\t/go/src/google.golang.org/grpc/server.go:982 +0x4c3\ngoogle.golang.org/grpc.(*Server).handleStream(0xc000380d80, 0x255ce60, 0xc000ae6c00, 0xc000eaa800, 0x0)\n\t/go/src/google.golang.org/grpc/server.go:1208 +0x12b5\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0008a48d0, 0xc000380d80, 0x255ce60, 0xc000ae6c00, 0xc000eaa800)\n\t/go/src/google.golang.org/grpc/server.go:686 +0x9f\ncreated by google.golang.org/grpc.(*Server).serveStreams.func1\n\t/go/src/google.golang.org/grpc/server.go:684 +0xa1\n"
argo-cd-argocd-server-7c74d884b9-pjjvp server time="2020-01-14T12:32:45Z" level=error msg="finished unary call with code Internal" error="rpc error: code = Internal desc = runtime error: invalid memory address or nil pointer dereference" grpc.code=Internal grpc.method=CreateRepositoryCredentials grpc.service=repocreds.RepoCredsService grpc.start_time="2020-01-14T12:32:45Z" grpc.time_ms=22.299 span.kind=server system=grpc
```
**Version**
v1.4.0-rc1

```shell
Paste the output from `argocd version` here.
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by alexmt** [comment]
hello @davidkarlsen , thank you for bug report! Prepared PR with the fix: https://github.com/argoproj/argo-cd/pull/2975 . 

Looks like panic happens if for some reason ArgoCD fails to parse existing repo credentials or fails to update secret. So opens panic is fixed you will be able to see the real error. Hopefully not a bug but some environmental issue.
