### ISSUE TITLE
Panic on PostSync

### ISSUE THREAD

**Issue by bclermont** [argoproj/argo-cd#3362]
This affect 1.5.0, but I haven't tried on previous version.

When I try to sync with a `PostSync` job it panic:

```
Recovered from panic: runtime error: slice bounds out of range [:7] with length 5
goroutine 74 [running]:
runtime/debug.Stack(0xc001e0fbd8, 0x1cbc980, 0xc0048b5ec0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
github.com/argoproj/argo-cd/controller.(*ApplicationController).processRequestedAppOperation.func1(0xc002969e00, 0xc001e11cc8, 0xc00073c500, 0xc001e11d68)
	/go/src/github.com/argoproj/argo-cd/controller/appcontroller.go:664 +0x5a
panic(0x1cbc980, 0xc0048b5ec0)
	/usr/local/go/src/runtime/panic.go:967 +0x15d
github.com/argoproj/argo-cd/controller.(*syncContext).getSyncTasks(0xc004377860, 0xc001e10e30, 0x1, 0x1, 0xc001e11138)
	/go/src/github.com/argoproj/argo-cd/controller/sync.go:427 +0x239e
github.com/argoproj/argo-cd/controller.(*syncContext).sync(0xc004377860)
	/go/src/github.com/argoproj/argo-cd/controller/sync.go:212 +0x2b9
github.com/argoproj/argo-cd/controller.(*appStateManager).SyncAppState(0xc00047a180, 0xc00340f500, 0xc0034416c0)
	/go/src/github.com/argoproj/argo-cd/controller/sync.go:196 +0x1066
github.com/argoproj/argo-cd/controller.(*ApplicationController).processRequestedAppOperation(0xc00073c500, 0xc00340f500)
	/go/src/github.com/argoproj/argo-cd/controller/appcontroller.go:697 +0x2ea
github.com/argoproj/argo-cd/controller.(*ApplicationController).processAppOperationQueueItem(0xc00073c500, 0x20200a7d20202001)
	/go/src/github.com/argoproj/argo-cd/controller/appcontroller.go:499 +0x495
github.com/argoproj/argo-cd/controller.(*ApplicationController).Run.func4()
	/go/src/github.com/argoproj/argo-cd/controller/appcontroller.go:429 +0x36
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc00062c640)
	/go/src/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x5f
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00062c640, 0x3b9aca00, 0x0, 0x616d656863732d01, 0xc00005ac00)
	/go/src/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(0xc00062c640, 0x3b9aca00, 0xc00005ac00)
	/go/src/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by github.com/argoproj/argo-cd/controller.(*ApplicationController).Run
	/go/src/github.com/argoproj/argo-cd/controller/appcontroller.go:428 +0x43e
```

Panic [occurs here](https://github.com/argoproj/argo-cd/blame/master/controller/sync.go#L427) it assume that `Revision` is at least 8 chars. but in my case it's 5.

This is the first time that sync is running ... well it never could ran before.

**Comment by jannfis** [comment]
@bclermont Ouch, thanks for the report! I just submitted a PR that should fix this. The revision should have been resolved to a commit SHA, I think. Did you sync against a valid (resolvable) revision?

**Comment by bclermont** [comment]
> Did you sync against a valid (resolvable) revision?

everything was in sync but that postsync job

let me build and try that PR
