### ISSUE TITLE
invalid memory address or nil pointer dereference when creating a helm app

### ISSUE THREAD

**Issue by rcjames** [argoproj/argo-cd#3612]
**Describe the bug**

Several applications are stuck in an "Unknown" state. When trying to sync it error's with the below.
```
ComparisonError: rpc error: code = Internal desc = runtime error: invalid memory address or nil pointer dereference
```
The `invalid memory...` error can be seen in the repo server logs and the stack trace has been included below. 

The `invalid memory...` error seems to be being thrown in the below function
https://github.com/argoproj/argo-cd/blob/v1.5.5/util/helm/helm.go#L40
```
func NewHelmApp(workDir string, repos []HelmRepository, isLocal bool) (Helm, error) {
	cmd, err := NewCmd(workDir)
	cmd.IsLocal = isLocal                 ### << Error thrown here

	if err != nil {
		return nil, err
	}
	return &helm{repos: repos, cmd: *cmd}, nil
}
```
As `NewCmd(workDir)` can return `nil` if an error occurs, `cmd` might not be an object so `cmd.IsLocal` might fail.

This line just needs to be moved to after the error check to ensure that the error gets returned.

**To Reproduce**

I'm unsure what exactly is causing the error here, because the actual error is being thrown away when the `invalid memory address or nil pointer dereference` error is thrown, but I believe it would be down to one of the following.
* Chart.yaml can't be opened
* Chart.yaml can't be unmarshalled
* Can't detect Helm version from Chart.yaml
* Can't create a new tmp dir

**Expected behavior**

An useful error is returned instead of a nil pointer error being thrown.

**Version**

```shell
argocd-server: v1.5.5+0fdef48
  BuildDate: 2020-05-16T04:04:43Z
  GitCommit: 0fdef4861e12026e133224f7c9413072340e2983
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: {Version:kustomize/v3.5.4 GitCommit:3af514fa9f85430f0c1557c4a0291e62112ab026 BuildDate:2020-01-11T03:12:59Z GoOs:linux GoArch:amd64}
  Helm Version: version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
  Kubectl Version: v1.14.0

```

**Logs**

```
time="2020-05-19T07:21:05Z" level=error msg="finished unary call with code Internal" error="rpc error: code = Internal desc = runtime error: invalid memory address or nil pointer dereference" grpc.code=Internal grpc.method=GenerateManifest grpc.request.deadline="2020-05-19T07:26:04Z" grpc.service=repository.RepoServerService grpc.start_time="2020-05-19T07:21:04Z" grpc.time_ms=102.607 span.kind=server system=grpc

time="2020-05-19T07:21:05Z" level=error msg="Recovered from panic: runtime error: invalid memory address or nil pointer dereference
goroutine 903114 [running]:
runtime/debug.Stack(0xc000f48960, 0x1872140, 0x2cc8050)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
github.com/argoproj/argo-cd/util/grpc.PanicLoggerUnaryServerInterceptor.func1.1(0xc0000a0640, 0xc000f49738)
	/go/src/github.com/argoproj/argo-cd/util/grpc/grpc.go:23 +0x6e
panic(0x1872140, 0x2cc8050)
	/usr/local/go/src/runtime/panic.go:967 +0x166
github.com/argoproj/argo-cd/util/helm.NewHelmApp(0xc000fb8a50, 0x21, 0xc0002b2000, 0x7, 0x8, 0x0, 0x0, 0x1, 0x4, 0x6)
	/go/src/github.com/argoproj/argo-cd/util/helm/helm.go:40 +0x4d
github.com/argoproj/argo-cd/reposerver/repository.helmTemplate(0xc000fb8a50, 0x21, 0xc000fb8a50, 0x21, 0xc000f48fc0, 0xc000e860e0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/argoproj/argo-cd/reposerver/repository/repository.go:312 +0x8e5
github.com/argoproj/argo-cd/reposerver/repository.GenerateManifests(0xc000fb8a50, 0x21, 0xc000fb8a50, 0x21, 0xc000c3cf30, 0x6, 0xc000e860e0, 0x19c3b00, 0x1, 0xc000d5b280, ...)
	/go/src/github.com/argoproj/argo-cd/reposerver/repository/repository.go:358 +0xbd9
github.com/argoproj/argo-cd/reposerver/repository.(*Service).GenerateManifest.func2(0xc000fb8a50, 0x21, 0xc000fb8a50, 0x21, 0xc000c3cf30, 0x6, 0x1d208a0, 0xc00000e088)
	/go/src/github.com/argoproj/argo-cd/reposerver/repository/repository.go:208 +0xaf
github.com/argoproj/argo-cd/reposerver/repository.(*Service).runRepoOperation(0xc000215f50, 0x1d61d80, 0xc000f4ac30, 0xc000c3cf30, 0x6, 0xc001393440, 0xc0001f9ab0, 0xc000979588, 0xc000f495a8, 0x0, ...)
	/go/src/github.com/argoproj/argo-cd/reposerver/repository/repository.go:170 +0x366
github.com/argoproj/argo-cd/reposerver/repository.(*Service).GenerateManifest(0xc000215f50, 0x1d61d80, 0xc000f4ac30, 0xc000e860e0, 0xc000215f50, 0x0, 0x0)
	/go/src/github.com/argoproj/argo-cd/reposerver/repository/repository.go:206 +0x159
github.com/argoproj/argo-cd/reposerver/apiclient._RepoServerService_GenerateManifest_Handler.func1(0x1d61d80, 0xc000f4ac30, 0x1a28d60, 0xc000e860e0, 0xf99fe7ab22, 0x1a9112d, 0x6, 0x1a9557e)
	/go/src/github.com/argoproj/argo-cd/reposerver/apiclient/repository.pb.go:1304 +0x86
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x1d61d80, 0xc000f4ac30, 0x1a28d60, 0xc000e860e0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:31 +0x114
github.com/argoproj/argo-cd/util/grpc.PanicLoggerUnaryServerInterceptor.func1(0x1d61d80, 0xc000f4ac30, 0x1a28d60, 0xc000e860e0, 0xc000d2ca20, 0xc0016adf90, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/argoproj/argo-cd/util/grpc/grpc.go:27 +0xa7
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x1d61d80, 0xc000f4ac30, 0x1a28d60, 0xc000e860e0, 0x2e, 0xbfa9001858c30aae, 0x31f41980eb8b, 0x2e5e6c0)
	/go/src/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:34 +0x9c
github.com/grpc-ecosystem/go-grpc-middleware/logging/logrus.UnaryServerInterceptor.func1(0x1d61d80, 0xc000f4ab10, 0x1a28d60, 0xc000e860e0, 0xc000d2ca20, 0xc0016adf90, 0xc000f4ab10, 0xc000d2c9a0, 0xc000afda28, 0x40ca88)
	/go/src/github.com/grpc-ecosystem/go-grpc-middleware/logging/logrus/server_interceptors.go:32 +0x110
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1(0x1d61d80, 0xc000f4ab10, 0x1a28d60, 0xc000e860e0, 0xc000d2ca20, 0xc000d2ca40, 0xc000afda98, 0x4edc38, 0x196dc20, 0xc000f4ab10)
	/go/src/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:39 +0x155
github.com/argoproj/argo-cd/reposerver/apiclient._RepoServerService_GenerateManifest_Handler(0x196b3e0, 0xc000215f50, 0x1d61d80, 0xc000f4ab10, 0xc0001f99d0, 0xc000215200, 0x1d61d80, 0xc000f4ab10, 0x0, 0x0)
	/go/src/github.com/argoproj/argo-cd/reposerver/apiclient/repository.pb.go:1306 +0x14b
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00012d200, 0x1d76480, 0xc0008fea80, 0xc000ea6500, 0xc000412c60, 0x2d0fcc0, 0x0, 0x0, 0x0)
	/go/src/google.golang.org/grpc/server.go:982 +0x4bd
google.golang.org/grpc.(*Server).handleStream(0xc00012d200, 0x1d76480, 0xc0008fea80, 0xc000ea6500, 0x0)
	/go/src/google.golang.org/grpc/server.go:1208 +0x11f0
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000d1cbb0, 0xc00012d200, 0x1d76480, 0xc0008fea80, 0xc000ea6500)
	/go/src/google.golang.org/grpc/server.go:686 +0xa1
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/go/src/google.golang.org/grpc/server.go:684 +0xa1

```

**Comment by jannfis** [comment]
Good catch, @rcjames - I believe this was introduced with PR #3407.
