### ISSUE TITLE
Recovered from panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by cmattoon** [argoproj/argo-cd#3656]
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

Nil pointer dereference

**To Reproduce**

  1) Copy an existing `Application` file and update the info to point to a `Kustomize` project
  2) Forget to remove `spec.source.helm.values` from the Helm `Application` you copied 

(Removing the extraneous `spec.source.helm` section fixed this)

**Expected behavior**

Not panic/log that extra information is present

**Screenshots**

**Version**

```shell
$ argocd version
argocd: v1.6.0+710d06c
  BuildDate: 2020-05-20T18:46:55Z
  GitCommit: 710d06c800c60f56b144b7409d7d3c579e6a1af7
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.5.5+0fdef48
  BuildDate: 2020-05-16T04:04:43Z
  GitCommit: 0fdef4861e12026e133224f7c9413072340e2983
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: {Version:kustomize/v3.5.4 GitCommit:3af514fa9f85430f0c1557c4a0291e62112ab026 BuildDate:2020-01-11T03:12:59Z GoOs:linux GoArch:amd64}
  Helm Version: version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
  Kubectl Version: v1.14.0
```

**Logs**

```
argocd-repo-server-77b8887877-wv8jh argocd-repo-server time="2020-05-26T23:44:20Z" level=info msg="manifest cache miss: &ApplicationSource{RepoURL:ssh://git@github.com/exampleorg/kubernetes.git,Path:apps/cert-manager,TargetRevision:master,Helm:&ApplicationSourceHelm{ValueFiles:[],Parameters:[]HelmParameter{},ReleaseName:,Values:txtOwnerId: \"use2-dev1-us-east-2-master\"
,FileParameters:[]HelmFileParameter{},},Kustomize:nil,Ksonnet:nil,Directory:nil,Plugin:nil,Chart:,}/204d293e560a8fbe6af10dce35e875f0b92531b0"
argocd-repo-server-77b8887877-wv8jh argocd-repo-server time="2020-05-26T23:44:20Z" level=info msg="git fetch origin --tags --force" dir=/tmp/git@github.com_exampleorg_kubernetes execID=wTkaj
argocd-repo-server-77b8887877-wv8jh argocd-repo-server time="2020-05-26T23:44:20Z" level=info msg="git checkout --force 204d293e560a8fbe6af10dce35e875f0b92531b0" dir=/tmp/git@github.com_exampleorg_kubernetes execID=xUQrU
argocd-repo-server-77b8887877-wv8jh argocd-repo-server time="2020-05-26T23:44:20Z" level=info msg="git clean -fdx" dir=/tmp/git@github.com_exampleorg_kubernetes execID=DkqGV
argocd-repo-server-77b8887877-wv8jh argocd-repo-server time="2020-05-26T23:44:20Z" level=info msg="git rev-parse HEAD" dir=/tmp/git@github.com_exampleorg_kubernetes execID=0kcuU
argocd-repo-server-77b8887877-wv8jh argocd-repo-server time="2020-05-26T23:44:20Z" level=error msg="Recovered from panic: runtime error: invalid memory address or nil pointer dereference
goroutine 2007717 [running]:
runtime/debug.Stack(0xc000714960, 0x1872140, 0x2cc8050)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
github.com/argoproj/argo-cd/util/grpc.PanicLoggerUnaryServerInterceptor.func1.1(0xc000088b90, 0xc000715738)
	/go/src/github.com/argoproj/argo-cd/util/grpc/grpc.go:23 +0x6e
panic(0x1872140, 0x2cc8050)
	/usr/local/go/src/runtime/panic.go:967 +0x166
github.com/argoproj/argo-cd/util/helm.NewHelmApp(0xc00096c980, 0x3e, 0x2e8b558, 0x0, 0x0, 0x0, 0x0, 0x1, 0x4, 0x0)
	/go/src/github.com/argoproj/argo-cd/util/helm/helm.go:40 +0x4d
github.com/argoproj/argo-cd/reposerver/repository.helmTemplate(0xc00096c980, 0x3e, 0xc0007f1020, 0x2c, 0xc000714fc0, 0xc0002549a0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/argoproj/argo-cd/reposerver/repository/repository.go:312 +0x8e5
github.com/argoproj/argo-cd/reposerver/repository.GenerateManifests(0xc00096c980, 0x3e, 0xc0007f1020, 0x2c, 0xc0007f1ad0, 0x28, 0xc0002549a0, 0xc000b2e800, 0x1, 0x1d20820, ...)
	/go/src/github.com/argoproj/argo-cd/reposerver/repository/repository.go:358 +0xbd9
github.com/argoproj/argo-cd/reposerver/repository.(*Service).GenerateManifest.func2(0xc00096c980, 0x3e, 0xc0007f1020, 0x2c, 0xc0007f1ad0, 0x28, 0x0, 0x0)
	/go/src/github.com/argoproj/argo-cd/reposerver/repository/repository.go:208 +0xaf
github.com/argoproj/argo-cd/reposerver/repository.(*Service).runRepoOperation(0xc000503590, 0x1d61d80, 0xc000909590, 0xc0007f1ad0, 0x28, 0xc000179980, 0xc00017c690, 0xc000715588, 0xc0007155a8, 0x0, ...)
	/go/src/github.com/argoproj/argo-cd/reposerver/repository/repository.go:186 +0x693
github.com/argoproj/argo-cd/reposerver/repository.(*Service).GenerateManifest(0xc000503590, 0x1d61d80, 0xc000909590, 0xc0002549a0, 0xc000503590, 0x0, 0x0)
	/go/src/github.com/argoproj/argo-cd/reposerver/repository/repository.go:206 +0x159
github.com/argoproj/argo-cd/reposerver/apiclient._RepoServerService_GenerateManifest_Handler.func1(0x1d61d80, 0xc000909590, 0x1a28d60, 0xc0002549a0, 0x90db8e8e74, 0x1a9112d, 0x6, 0x1a9557e)
	/go/src/github.com/argoproj/argo-cd/reposerver/apiclient/repository.pb.go:1304 +0x86
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x1d61d80, 0xc000909590, 0x1a28d60, 0xc0002549a0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:31 +0x114
github.com/argoproj/argo-cd/util/grpc.PanicLoggerUnaryServerInterceptor.func1(0x1d61d80, 0xc000909590, 0x1a28d60, 0xc0002549a0, 0xc00088fea0, 0xc00086a320, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/argoproj/argo-cd/util/grpc/grpc.go:27 +0xa7
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x1d61d80, 0xc000909590, 0x1a28d60, 0xc0002549a0, 0x2e, 0xbfab885504a752d6, 0xfe53c7c5514e, 0x2e5e6c0)
	/go/src/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:34 +0x9c
github.com/grpc-ecosystem/go-grpc-middleware/logging/logrus.UnaryServerInterceptor.func1(0x1d61d80, 0xc000909470, 0x1a28d60, 0xc0002549a0, 0xc00088fea0, 0xc00086a320, 0xc000909470, 0xc00088fe40, 0xc000618a28, 0x40ca88)
	/go/src/github.com/grpc-ecosystem/go-grpc-middleware/logging/logrus/server_interceptors.go:32 +0x110
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1(0x1d61d80, 0xc000909470, 0x1a28d60, 0xc0002549a0, 0xc00088fea0, 0xc00088fec0, 0xc000618a98, 0x4edc38, 0x196dc20, 0xc000909470)
	/go/src/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:39 +0x155
github.com/argoproj/argo-cd/reposerver/apiclient._RepoServerService_GenerateManifest_Handler(0x196b3e0, 0xc000503590, 0x1d61d80, 0xc000909470, 0xc00017c620, 0xc0005033e0, 0x1d61d80, 0xc000909470, 0x0, 0x0)
	/go/src/github.com/argoproj/argo-cd/reposerver/apiclient/repository.pb.go:1306 +0x14b
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00027c300, 0x1d76480, 0xc0009c5080, 0xc000c08e00, 0xc000503620, 0x2d0fcc0, 0x0, 0x0, 0x0)
	/go/src/google.golang.org/grpc/server.go:982 +0x4bd
google.golang.org/grpc.(*Server).handleStream(0xc00027c300, 0x1d76480, 0xc0009c5080, 0xc000c08e00, 0x0)
	/go/src/google.golang.org/grpc/server.go:1208 +0x11f0
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0002a3c20, 0xc00027c300, 0x1d76480, 0xc0009c5080, 0xc000c08e00)
	/go/src/google.golang.org/grpc/server.go:686 +0xa1
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/go/src/google.golang.org/grpc/server.go:684 +0xa1
"
argocd-repo-server-77b8887877-wv8jh argocd-repo-server time="2020-05-26T23:44:20Z" level=error msg="finished unary call with code Internal" error="rpc error: code = Internal desc = runtime error: invalid memory address or nil pointer dereference" grpc.code=Internal grpc.method=GenerateManifest grpc.request.deadline="2020-05-26T23:45:20Z" grpc.service=repository.RepoServerService grpc.start_time="2020-05-26T23:44:20Z" grpc.time_ms=710.941 span.kind=server system=grpc
```

**Comment by alexmt** [comment]
Thank you for creating the ticket @cmattoon . This was fixed in master by  https://github.com/argoproj/argo-cd/commit/313de8694160c20a952b942400a7cf417e669473 . Cherry-picked into 1.5 branch.
