### ISSUE TITLE
runtime error: slice bounds out of range [:7] with length 5

### ISSUE THREAD

**Issue by estahn** [argoproj/argo-cd#3713]
**Describe the bug**

ArgoCD is getting stuck at times but then continues to apply manifests sometime later. See the slack discussion [here](https://argoproj.slack.com/archives/CASHNF6MS/p1591241105409800).

**To Reproduce**

No idea.

**Expected behavior**

No delay in applying the manifest.

**Version**

```shell
v1.5.1+8a3b36b
```

**Logs**

```
argocd-server-595d45986d-5ktsd argocd-server 2020/06/04 03:24:07 http: panic serving 100.97.45.83:56180: runtime error: slice bounds out of range [:7] with length 5
argocd-server-595d45986d-5ktsd argocd-server goroutine 13559 [running]:
argocd-server-595d45986d-5ktsd argocd-server net/http.(*conn).serve.func1(0xc003943ae0)
argocd-server-595d45986d-5ktsd argocd-server 	/usr/local/go/src/net/http/server.go:1772 +0x139
argocd-server-595d45986d-5ktsd argocd-server panic(0x1ea2680, 0xc003002280)
argocd-server-595d45986d-5ktsd argocd-server 	/usr/local/go/src/runtime/panic.go:973 +0x396
argocd-server-595d45986d-5ktsd argocd-server github.com/argoproj/argo-cd/server/badge.(*Handler).ServeHTTP(0xc00090f050, 0x240ca80, 0xc0009cc1c0, 0xc000a15300)
argocd-server-595d45986d-5ktsd argocd-server 	/go/src/github.com/argoproj/argo-cd/server/badge/badge.go:125 +0xe6e
argocd-server-595d45986d-5ktsd argocd-server github.com/argoproj/argo-cd/server.(*handlerSwitcher).ServeHTTP(0xc00090c640, 0x240ca80, 0xc0009cc1c0, 0xc000a15300)
argocd-server-595d45986d-5ktsd argocd-server 	/go/src/github.com/argoproj/argo-cd/server/server.go:839 +0x95
argocd-server-595d45986d-5ktsd argocd-server net/http.serverHandler.ServeHTTP(0xc00001e700, 0x240ca80, 0xc0009cc1c0, 0xc000a15300)
argocd-server-595d45986d-5ktsd argocd-server 	/usr/local/go/src/net/http/server.go:2807 +0xa3
argocd-server-595d45986d-5ktsd argocd-server net/http.(*conn).serve(0xc003943ae0, 0x2411e80, 0xc002471680)
argocd-server-595d45986d-5ktsd argocd-server 	/usr/local/go/src/net/http/server.go:1895 +0x86c
argocd-server-595d45986d-5ktsd argocd-server created by net/http.(*Server).Serve
argocd-server-595d45986d-5ktsd argocd-server 	/usr/local/go/src/net/http/server.go:2933 +0x35c
```

**Comment by alexmt** [comment]
Fixed by https://github.com/argoproj/argo-cd/pull/3741 . Cherry-picking into 1.5
