### ISSUE TITLE
Synchronization failed due to nil pointer dereference error 

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#3752]
Observed panic in argocd logs:

```
time="2020-05-18T17:28:21Z" level=error msg="Recovered from panic: runtime error: invalid memory address or nil pointer dereference
goroutine 87 [running]:
runtime/debug.Stack(0xc001515200, 0x1b98c60, 0x3461f90)
\t/opt/hostedtoolcache/go/1.14.1/x64/src/runtime/debug/stack.go:24 +0x9d
github.com/argoproj/argo-cd/controller.(*ApplicationController).processAppRefreshQueueItem.func1(0xc0003bea00, 0x1af3d60, 0xc006329f60)
\t/home/runner/work/argo-cd/argo-cd/src/github.com/argoproj/argo-cd/controller/appcontroller.go:809 +0x85
panic(0x1b98c60, 0x3461f90)
\t/opt/hostedtoolcache/go/1.14.1/x64/src/runtime/panic.go:973 +0x3e3
github.com/argoproj/argo-cd/vendor/github.com/argoproj/gitops-engine/pkg/utils/kube.filterAPIResources(0xc0005ea000, 0x0, 0x0, 0x1f024e0, 0xc001508000, 0x2421, 0x3e00, 0xc0056edde0, 0x10)
\t/home/runner/work/argo-cd/argo-cd/src/github.com/argoproj/argo-cd/vendor/github.com/argoproj/gitops-engine/pkg/utils/kube/ctl.go:83 +0x309
github.com/argoproj/argo-cd/vendor/github.com/argoproj/gitops-engine/pkg/utils/kube.(*KubectlCmd).GetAPIResources(0xc00011a7b8, 0xc0005ea000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
\t/home/runner/work/argo-cd/argo-cd/src/github.com/argoproj/argo-cd/vendor/github.com/argoproj/gitops-engine/pkg/utils/kube/ctl.go:130 +0x1cd
github.com/argoproj/argo-cd/vendor/github.com/argoproj/gitops-engine/pkg/utils/kube/cache.(*clusterCache).sync(0xc000a5c000, 0xc002032a00, 0xc0019cf0b8)
\t/home/runner/work/argo-cd/argo-cd/src/github.com/argoproj/argo-cd/vendor/github.com/argoproj/gitops-engine/pkg/utils/kube/cache/cluster.go:494 +0x333
github.com/argoproj/argo-cd/vendor/github.com/argoproj/gitops-engine/pkg/utils/kube/cache.(*clusterCache).EnsureSynced(0xc000a5c000, 0x0, 0x0)
\t/home/runner/work/argo-cd/argo-cd/src/github.com/argoproj/argo-cd/vendor/github.com/argoproj/gitops-engine/pkg/utils/kube/cache/cluster.go:569 +0xaa
github.com/argoproj/argo-cd/controller/cache.(*liveStateCache).getSyncedCluster(0xc00053c280, 0xc0000154c0, 0x1e, 0xc03844f6d4, 0x3844f6d4019cefc0, 0x5ec2c5b4, 0xc001569980)
\t/home/runner/work/argo-cd/argo-cd/src/github.com/argoproj/argo-cd/controller/cache/cache.go:271 +0x70
github.com/argoproj/argo-cd/controller/cache.(*liveStateCache).GetVersionsInfo(0xc00053c280, 0xc0000154c0, 0x1e, 0xc0006505d0, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0)
\t/home/runner/work/argo-cd/argo-cd/src/github.com/argoproj/argo-cd/controller/cache/cache.go:335 +0x43
github.com/argoproj/argo-cd/controller.(*appStateManager).getRepoObjs(0xc00028a000, 0xc003695180, 0xc0006a7c50, 0x30, 0xc0006505d0, 0x8, 0x0, 0x0, 0x0, 0x0, ...)
\t/home/runner/work/argo-cd/argo-cd/src/github.com/argoproj/argo-cd/controller/state.go:138 +0x859
github.com/argoproj/argo-cd/controller.(*appStateManager).CompareAppState(0xc00028a000, 0xc003695180, 0xc00067e588, 0x0, 0x0, 0xc0006a7c50, 0x30, 0xc0006505d0, 0x8, 0x0, ...)
\t/home/runner/work/argo-cd/argo-cd/src/github.com/argoproj/argo-cd/controller/state.go:274 +0x47b
github.com/argoproj/argo-cd/controller.(*ApplicationController).processAppRefreshQueueItem(0xc0003bea00, 0x1)
\t/home/runner/work/argo-cd/argo-cd/src/github.com/argoproj/argo-cd/controller/appcontroller.go:898 +0x66e
github.com/argoproj/argo-cd/controller.(*ApplicationController).Run.func3()
\t/home/runner/work/argo-cd/argo-cd/src/github.com/argoproj/argo-cd/controller/appcontroller.go:432 +0x36
github.com/argoproj/argo-cd/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc0003b3c20)
\t/home/runner/work/argo-cd/argo-cd/src/github.com/argoproj/argo-cd/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x5f
github.com/argoproj/argo-cd/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0003b3c20, 0x3b9aca00, 0x0, 0x1, 0xc0000969c0)
\t/home/runner/work/argo-cd/argo-cd/src/github.com/argoproj/argo-cd/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8
github.com/argoproj/argo-cd/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc0003b3c20, 0x3b9aca00, 0xc0000969c0)
\t/home/runner/work/argo-cd/argo-cd/src/github.com/argoproj/argo-cd/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by github.com/argoproj/argo-cd/controller.(*ApplicationController).Run
\t/home/runner/work/argo-cd/argo-cd/src/github.com/argoproj/argo-cd/controller/appcontroller.go:431 +0x377
```

**Comment by alexmt** [comment]
Still not fixed

**Comment by alexmt** [comment]
Noticed in logs this:

```
msg="Changing cluster cache settings to: {<nil> <nil>}"
```
