### ISSUE TITLE
End-to-End tests failing intermittently (flaky tests)

### ISSUE THREAD

**Issue by jannfis** [argoproj/argo-cd#3932]
Umbrella issue to track intermittent failing end-to-end tests.

I noticed at least two quirks failing intermittently in the recent time:

* ~~Sometimes, `make cli-local` (dependance of `make test-e2e-local`) fails with a permission denied error when trying to write the binary~~ (fixed by #3952)
* ~~The test `TestSyncOptionDryRun` fails very often, also locally~~ (fixed by #3939)
* ~~The CLI fails sometimes with nil pointer exceptions (see comments below)~~ (should be fixed by #3951)
* TestWatchClusters_CreateRemoveCluster
* ~~TestSyncToSignedCommitKeyWithKnownKey~~

For a list of flaky unit tests, see #5566

**Comment by jannfis** [comment]
TestSyncOptionDryRun was fixed by #3939

**Comment by darshanime** [comment]
Any idea why the `make cli-local` is flakey? I am not sure if it's related to https://github.com/argoproj/argo-cd/pull/3884/, as that just renames the target name.

**Comment by jannfis** [comment]
@darshanime No, unfortunately, this is a mystery to me currently. It failed also before it was renamed, and I've only see it failing in the CI not locally.

**Comment by jannfis** [comment]
I've also seen some of the CLI commands failing with nil pointer exceptions, for example the following test ran fine on a PR, and failed once merged into master (the PR was not changing anything relatable):

```
time="2020-07-14T07:48:04Z" level=error msg="`../../dist/argocd app sync test-manipulate-application-resources --timeout 10 --prune --plaintext --server 127.0.0.1:8088 --auth-token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1OTQ3MTI4MDYsImlzcyI6ImFyZ29jZCIsIm5iZiI6MTU5NDcxMjgwNiwic3ViIjoiYWRtaW4ifQ.g0pNS_SjUDfS3oodNndeZNkbH_yPr2oWtN7L1_w6tsM --insecure` failed exit status 2: panic: runtime error: invalid memory address or nil pointer dereference\n[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x1a37472]\n\ngoroutine 1 [running]:\ngithub.com/argoproj/argo-cd/cmd/argocd/commands.NewApplicationSyncCommand.func1(0xc0000e0c80, 0xc0007ebc20, 0x1, 0xa)\n\t/home/runner/work/argo-cd/argo-cd/cmd/argocd/commands/app.go:1563 +0x6c2\ngithub.com/spf13/cobra.(*Command).execute(0xc0000e0c80, 0xc0007ebae0, 0xa, 0xa, 0xc0000e0c80, 0xc0007ebae0)\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x29d\ngithub.com/spf13/cobra.(*Command).ExecuteC(0xc0001b2f00, 0x0, 0x0, 0x0)\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb\ngithub.com/spf13/cobra.(*Command).Execute(...)\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864\nmain.main()\n\t/home/runner/work/argo-cd/argo-cd/cmd/argocd/main.go:15 +0x27" execID=Qr2HO
##[error]    TestManipulateApplicationResources: app_management_test.go:335: failed expectation: error
```

**Comment by jannfis** [comment]
Also:
```
time="2020-07-14T07:52:44Z" level=info msg="../../dist/argocd app sync test-cr-ds --timeout 10 --prune --plaintext --server 127.0.0.1:8088 --auth-token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1OTQ3MTMwNzYsImlzcyI6ImFyZ29jZCIsIm5iZiI6MTU5NDcxMzA3Niwic3ViIjoiYWRtaW4ifQ.AqVUcGVPMfqMwuQ5glVkRsbPWSPVB-CnPUCatzdJAn0 --insecure" dir= execID=09L2v
time="2020-07-14T07:52:45Z" level=debug msg="\nName:               test-cr-ds\nProject:            default\nServer:             https://kubernetes.default.svc\nNamespace:          argocd-e2e--test-cr-ds-pvogl\nURL:                http://127.0.0.1:8088/applications/test-cr-ds\nRepo:               file:///tmp/argo-e2e/testdata.git\nTarget:             \nPath:               crd-creation\nSyncWindow:         Sync Allowed\nSync Policy:        <none>\nSync Status:        \nHealth Status:      \n\n" duration=291.393868ms execID=09L2v
time="2020-07-14T07:52:45Z" level=error msg="`../../dist/argocd app sync test-cr-ds --timeout 10 --prune --plaintext --server 127.0.0.1:8088 --auth-token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1OTQ3MTMwNzYsImlzcyI6ImFyZ29jZCIsIm5iZiI6MTU5NDcxMzA3Niwic3ViIjoiYWRtaW4ifQ.AqVUcGVPMfqMwuQ5glVkRsbPWSPVB-CnPUCatzdJAn0 --insecure` failed exit status 2: panic: runtime error: invalid memory address or nil pointer dereference\n[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x1a37472]\n\ngoroutine 1 [running]:\ngithub.com/argoproj/argo-cd/cmd/argocd/commands.NewApplicationSyncCommand.func1(0xc0001a9900, 0xc000393e00, 0x1, 0xa)\n\t/home/runner/work/argo-cd/argo-cd/cmd/argocd/commands/app.go:1563 +0x6c2\ngithub.com/spf13/cobra.(*Command).execute(0xc0001a9900, 0xc000393cc0, 0xa, 0xa, 0xc0001a9900, 0xc000393cc0)\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x29d\ngithub.com/spf13/cobra.(*Command).ExecuteC(0xc00048f180, 0x0, 0x0, 0x0)\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb\ngithub.com/spf13/cobra.(*Command).Execute(...)\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864\nmain.main()\n\t/home/runner/work/argo-cd/argo-cd/cmd/argocd/main.go:15 +0x27" execID=09L2v
##[error]    TestCRDs: app_management_test.go:563: failed expectation: error
```

**Comment by lcostea** [comment]
I have the same error as above on TestRevisionHistoryLimit, when doing app sync with the cli, same line of code
Happened a few times on my PR #3944 

level=error msg="`../../dist/argocd app sync test-revision-history-limit --timeout 10 --prune --plaintext --server 127.0.0.1:8088 --auth-token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1OTQ5MjE1NjAsImlzcyI6ImFyZ29jZCIsIm5iZiI6MTU5NDkyMTU2MCwic3ViIjoiYWRtaW4ifQ.ukM_cuZEAPQ8zihc8F1Rj_y2A38yuTbFqH-69YGSupc --insecure` failed exit status 2: panic: runtime error: invalid memory address or nil pointer dereference\n[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x1a37c22]\n\ngoroutine 1 [running]:\ngithub.com/argoproj/argo-cd/cmd/argocd/commands.NewApplicationSyncCommand.func1(0xc0005dca00, 0xc0005e85a0, 0x1, 0xa)\n\t/home/runner/work/argo-cd/argo-cd/cmd/argocd/commands/app.go:1563 +0x6c2\ngithub.com/spf13/cobra.(*Command).execute(0xc0005dca00, 0xc0005e8460, 0xa, 0xa, 0xc0005dca00, 0xc0005e8460)\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x29d\ngithub.com/spf13/cobra.(*Command).ExecuteC(0xc0000faf00, 0x0, 0x0, 0x0)\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb\ngithub.com/spf13/cobra.(*Command).Execute(...)\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864\nmain.main()\n\t/home/runner/work/argo-cd/argo-cd/cmd/argocd/main.go:15 +0x27" execID=mSqzo
2020-07-16T17:48:30.9589627Z ##[error]    TestRevisionHistoryLimit: app_management_test.go:969: failed expectation:

**Comment by jannfis** [comment]
Nil pointer exceptions during `app sync` should be fixed by #3951

**Comment by jannfis** [comment]
Another one bites the dust from time to time:
```
time="2020-07-17T19:03:50Z" level=info msg="pending: operation phase should be Succeeded, is Error"
time="2020-07-17T19:03:53Z" level=info msg="pending: operation phase should be Succeeded, is Error"
time="2020-07-17T19:03:56Z" level=info msg="pending: operation phase should be Succeeded, is Error"
time="2020-07-17T19:03:59Z" level=info msg="pending: operation phase should be Succeeded, is Error"
time="2020-07-17T19:04:02Z" level=info msg="pending: operation phase should be Succeeded, is Error"
##[error]    TestSyncToSignedCommitKeyWithKnownKey: app_management_test.go:91: timeout waiting for: operation phase should be Succeeded, is Error
```

**Comment by jannfis** [comment]
Unit test:
```
time="2020-07-21T08:12:09Z" level=info msg="Comparing app state (cluster: https://kubernetes.default.svc, namespace: default)" application=test
2020/07/21 08:12:09 proto: tag has too few fields: "-"
time="2020-07-21T08:12:09Z" level=info msg="getRepoObjs stats" application=test build_options_ms=0 helm_ms=0 plugins_ms=0 repo_ms=0 time_ms=0 unmarshal_ms=0 version_ms=0
--- FAIL: TestDiffReconcileResults_DifferentApps (0.00s)
    apps_test.go:158: 
        	Error Trace:	apps_test.go:158
        	Error:      	Not equal: 
        	            	expected: "app1\napp2\n1,9d0\n< conditions: null\n< health: null\n< name: app2\n< sync:\n<   comparedTo:\n<     destination: {}\n<     source:\n<       repoURL: \"\"\n<   status: OutOfSync\napp3\n0a1,9\n> conditions: null\n> health: null\n> name: app3\n> sync:\n>   comparedTo:\n>     destination: {}\n>     source:\n>       repoURL: \"\"\n>   status: OutOfSync\n"
        	            	actual  : "app2\n1,9d0\n< conditions: null\n< health: null\n< name: app2\n< sync:\n<   comparedTo:\n<     destination: {}\n<     source:\n<       repoURL: \"\"\n<   status: OutOfSync\napp1\napp3\n0a1,9\n> conditions: null\n> health: null\n> name: app3\n> sync:\n>   comparedTo:\n>     destination: {}\n>     source:\n>       repoURL: \"\"\n>   status: OutOfSync\n"
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1,2 +1 @@
        	            	-app1
        	            	 app2
        	            	@@ -12,2 +11,3 @@
        	            	 <   status: OutOfSync
        	            	+app1
        	            	 app3
        	Test:       	TestDiffReconcileResults_DifferentApps
FAIL
```

**Comment by darshanime** [comment]
One more e2e tests I have seen be flaky:

```
2020-08-01T03:29:33.4792456Z === RUN   TestOneProgressingDeploymentIsSucceededAndSynced
2020-08-01T03:29:33.5065668Z time="2020-08-01T03:29:33Z" level=info msg="kubectl delete ns -l e2e.argoproj.io=true --field-selector status.phase=Active --wait=false" dir= execID=uVzxN
2020-08-01T03:29:33.5839909Z time="2020-08-01T03:29:33Z" level=debug msg="namespace \"argocd-e2e--test-fixing-degraded-app-kpjzj\" deleted\n" duration=77.093458ms execID=uVzxN
2020-08-01T03:29:33.5841059Z time="2020-08-01T03:29:33Z" level=info msg="kubectl delete crd -l e2e.argoproj.io=true --wait=false" dir= execID=fyKe6
2020-08-01T03:29:33.6621832Z time="2020-08-01T03:29:33Z" level=debug msg="No resources found\n" duration=78.312569ms execID=fyKe6
2020-08-01T03:29:33.8671809Z time="2020-08-01T03:29:33Z" level=info msg="../../dist/argocd proj create gpg --plaintext --server 127.0.0.1:8088 --auth-token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1OTYyNTE5NjEsImlzcyI6ImFyZ29jZCIsIm5iZiI6MTU5NjI1MTk2MSwic3ViIjoiYWRtaW4ifQ.5hN4UNihkBkSV8QjYzAwO5rpkL3_92uye4D67yUb1fE --insecure" dir= execID=leVUE
2020-08-01T03:29:33.9452138Z time="2020-08-01T03:29:33Z" level=debug msg="EE: 0/[]\n" duration=78.007966ms execID=leVUE
2020-08-01T03:29:34.2848158Z time="2020-08-01T03:29:34Z" level=info msg="mkdir -p /tmp/argo-e2e" dir= execID=4eAIa
2020-08-01T03:29:34.2859933Z time="2020-08-01T03:29:34Z" level=debug duration=1.296111ms execID=4eAIa
2020-08-01T03:29:34.2860591Z time="2020-08-01T03:29:34Z" level=info msg="mkdir -p /tmp/argo-e2e/app/config/tls" dir= execID=ZyYOc
2020-08-01T03:29:34.2877489Z time="2020-08-01T03:29:34Z" level=debug duration=1.247911ms execID=ZyYOc
2020-08-01T03:29:34.2878377Z time="2020-08-01T03:29:34Z" level=info msg="mkdir -p /tmp/argo-e2e/app/config/ssh" dir= execID=rJ23P
2020-08-01T03:29:34.2891111Z time="2020-08-01T03:29:34Z" level=debug duration=1.312611ms execID=rJ23P
2020-08-01T03:29:34.2891940Z time="2020-08-01T03:29:34Z" level=info msg="mkdir -p /tmp/argo-e2e/gpg" dir= execID=fs8QG
2020-08-01T03:29:34.2904669Z time="2020-08-01T03:29:34Z" level=debug duration=1.304911ms execID=fs8QG
2020-08-01T03:29:34.2905504Z time="2020-08-01T03:29:34Z" level=info msg="chmod 0700 /tmp/argo-e2e/gpg" dir= execID=YAZXD
2020-08-01T03:29:34.2916846Z time="2020-08-01T03:29:34Z" level=debug duration=1.053309ms execID=YAZXD
2020-08-01T03:29:34.2917601Z time="2020-08-01T03:29:34Z" level=info msg="pkill -9 gpg-agent" dir= execID=FMo6o
2020-08-01T03:29:34.2993246Z time="2020-08-01T03:29:34Z" level=debug duration=7.607165ms execID=FMo6o
2020-08-01T03:29:34.2994141Z time="2020-08-01T03:29:34Z" level=error msg="`pkill -9 gpg-agent` failed exit status 1" execID=FMo6o
2020-08-01T03:29:34.2995006Z time="2020-08-01T03:29:34Z" level=info msg="gpg --import ../fixture/gpg/signingkey.asc" dir= execID=TBpeC
2020-08-01T03:29:34.3143314Z time="2020-08-01T03:29:34Z" level=debug duration=14.931528ms execID=TBpeC
2020-08-01T03:29:34.3144741Z time="2020-08-01T03:29:34Z" level=info msg="mkdir -p /tmp/argo-e2e/app/config/gpg/source" dir= execID=HetNc
2020-08-01T03:29:34.3157447Z time="2020-08-01T03:29:34Z" level=debug duration=1.321411ms execID=HetNc
2020-08-01T03:29:34.3159040Z time="2020-08-01T03:29:34Z" level=info msg="mkdir -p /tmp/argo-e2e/app/config/gpg/keys" dir= execID=uR6ls
2020-08-01T03:29:34.3201739Z time="2020-08-01T03:29:34Z" level=debug duration=4.348137ms execID=uR6ls
2020-08-01T03:29:34.3202915Z time="2020-08-01T03:29:34Z" level=info msg="chmod 0700 /tmp/argo-e2e/app/config/gpg/keys" dir= execID=3M8ap
2020-08-01T03:29:34.3210957Z time="2020-08-01T03:29:34Z" level=debug duration="779.406µs" execID=3M8ap
2020-08-01T03:29:34.3211637Z time="2020-08-01T03:29:34Z" level=info msg="cp -Rf testdata /tmp/argo-e2e/testdata.git" dir= execID=44HgD
2020-08-01T03:29:34.3290829Z time="2020-08-01T03:29:34Z" level=debug duration=7.958668ms execID=44HgD
2020-08-01T03:29:34.3291734Z time="2020-08-01T03:29:34Z" level=info msg="chmod 777 ." dir=/tmp/argo-e2e/testdata.git execID=VOeI9
2020-08-01T03:29:34.3300793Z time="2020-08-01T03:29:34Z" level=debug duration=1.053909ms execID=VOeI9
2020-08-01T03:29:34.3302001Z time="2020-08-01T03:29:34Z" level=info msg="git init" dir=/tmp/argo-e2e/testdata.git execID=CGrBr
2020-08-01T03:29:34.3328454Z time="2020-08-01T03:29:34Z" level=debug msg="Initialized empty Git repository in /tmp/argo-e2e/testdata.git/.git/\n" duration=2.698923ms execID=CGrBr
2020-08-01T03:29:34.3329819Z time="2020-08-01T03:29:34Z" level=info msg="git add ." dir=/tmp/argo-e2e/testdata.git execID=QR4Sw
2020-08-01T03:29:34.3520113Z time="2020-08-01T03:29:34Z" level=debug duration=18.875961ms execID=QR4Sw
2020-08-01T03:29:34.3521698Z time="2020-08-01T03:29:34Z" level=info msg="git commit -q -m initial commit" dir=/tmp/argo-e2e/testdata.git execID=wzM12
2020-08-01T03:29:34.3672395Z time="2020-08-01T03:29:34Z" level=debug duration=15.27313ms execID=wzM12
2020-08-01T03:29:34.3673102Z time="2020-08-01T03:29:34Z" level=info msg="kubectl create ns argocd-e2e--test-one-progressing-deployment-is-succeeded--xzsyz" dir= execID=5TiZ1
2020-08-01T03:29:34.4417066Z time="2020-08-01T03:29:34Z" level=debug msg="namespace/argocd-e2e--test-one-progressing-deployment-is-succeeded--xzsyz created\n" duration=67.440275ms execID=5TiZ1
2020-08-01T03:29:34.4417588Z time="2020-08-01T03:29:34Z" level=info msg="kubectl label ns argocd-e2e--test-one-progressing-deployment-is-succeeded--xzsyz e2e.argoproj.io=true" dir= execID=ehHKw
2020-08-01T03:29:34.5048183Z time="2020-08-01T03:29:34Z" level=debug msg="namespace/argocd-e2e--test-one-progressing-deployment-is-succeeded--xzsyz labeled\n" duration=69.944496ms execID=ehHKw
2020-08-01T03:29:34.5049559Z time="2020-08-01T03:29:34Z" level=info msg="clean state" duration=1.025568853s id=TestOneProgressingDeploymentIsSucceededAndSynced-xzsyz name=TestOneProgressingDeploymentIsSucceededAndSynced password=password username=admin
2020-08-01T03:29:35.5054508Z time="2020-08-01T03:29:35Z" level=info msg=patching jsonPatch="[\n    {\n        \"op\": \"replace\",\n        \"path\": \"/spec/template/spec/containers/0/image\",\n        \"value\": \"alpine:ops!\"\n    }\n]" path=one-deployment/deployment.yaml
2020-08-01T03:29:35.5056622Z time="2020-08-01T03:29:35Z" level=info msg="converting YAML to JSON"
2020-08-01T03:29:35.5058108Z time="2020-08-01T03:29:35Z" level=info msg=JSON bytes="{\"apiVersion\":\"apps/v1\",\"kind\":\"Deployment\",\"metadata\":{\"name\":\"main\"},\"spec\":{\"progressDeadlineSeconds\":10,\"replicas\":1,\"selector\":{\"matchLabels\":{\"my-label\":\"whatever\"}},\"template\":{\"metadata\":{\"labels\":{\"my-label\":\"whatever\"}},\"spec\":{\"containers\":[{\"command\":[\"sleep\",\"999\"],\"image\":\"alpine:3.10.2\",\"imagePullPolicy\":\"IfNotPresent\",\"name\":\"main\"}]}}}}"
2020-08-01T03:29:35.5059620Z time="2020-08-01T03:29:35Z" level=info msg="converting JSON back to YAML"
2020-08-01T03:29:35.5062659Z time="2020-08-01T03:29:35Z" level=info msg="git diff" dir=/tmp/argo-e2e/testdata.git execID=aMG8X
2020-08-01T03:29:35.5090666Z time="2020-08-01T03:29:35Z" level=debug msg="diff --git a/one-deployment/deployment.yaml b/one-deployment/deployment.yaml\nindex 4aaaa91..12f6395 100644\n--- a/one-deployment/deployment.yaml\n+++ b/one-deployment/deployment.yaml\n@@ -3,8 +3,8 @@ kind: Deployment\n metadata:\n   name: main\n spec:\n-  replicas: 1\n   progressDeadlineSeconds: 10\n+  replicas: 1\n   selector:\n     matchLabels:\n       my-label: whatever\n@@ -14,8 +14,9 @@ spec:\n         my-label: whatever\n     spec:\n       containers:\n-        - name: main\n-          command: [\"sleep\", \"999\"]\n-          image: alpine:3.10.2\n-          imagePullPolicy: IfNotPresent\n-\n+      - command:\n+        - sleep\n+        - \"999\"\n+        image: alpine:ops!\n+        imagePullPolicy: IfNotPresent\n+        name: main\n" duration=3.003526ms execID=aMG8X
2020-08-01T03:29:35.5091681Z time="2020-08-01T03:29:35Z" level=info msg="git commit -am patch" dir=/tmp/argo-e2e/testdata.git execID=i9YEw
2020-08-01T03:29:35.5177970Z time="2020-08-01T03:29:35Z" level=debug msg="[master f4d3a52] patch\n 1 file changed, 7 insertions(+), 6 deletions(-)\n" duration=8.655974ms execID=i9YEw
2020-08-01T03:29:35.5179327Z time="2020-08-01T03:29:35Z" level=info msg="../../dist/argocd app create test-one-progressing-deployment-is-succeeded-and-synced --repo file:///tmp/argo-e2e/testdata.git --dest-server https://kubernetes.default.svc --path one-deployment --project default --dest-namespace argocd-e2e--test-one-progressing-deployment-is-succeeded--xzsyz --plaintext --server 127.0.0.1:8088 --auth-token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1OTYyNTE5NjEsImlzcyI6ImFyZ29jZCIsIm5iZiI6MTU5NjI1MTk2MSwic3ViIjoiYWRtaW4ifQ.5hN4UNihkBkSV8QjYzAwO5rpkL3_92uye4D67yUb1fE --insecure" dir= execID=qUHCA
2020-08-01T03:29:35.8328445Z time="2020-08-01T03:29:35Z" level=debug msg="application 'test-one-progressing-deployment-is-succeeded-and-synced' created\n" duration=314.884184ms execID=qUHCA
2020-08-01T03:29:35.8328951Z time="2020-08-01T03:29:35Z" level=info msg="expectation succeeded: no error and output contained ''"
2020-08-01T03:29:35.8329919Z time="2020-08-01T03:29:35Z" level=info msg="../../dist/argocd app sync test-one-progressing-deployment-is-succeeded-and-synced --timeout 10 --prune --plaintext --server 127.0.0.1:8088 --auth-token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1OTYyNTE5NjEsImlzcyI6ImFyZ29jZCIsIm5iZiI6MTU5NjI1MTk2MSwic3ViIjoiYWRtaW4ifQ.5hN4UNihkBkSV8QjYzAwO5rpkL3_92uye4D67yUb1fE --insecure" dir= execID=l6sEz
2020-08-01T03:29:46.8706012Z + report
2020-08-01T03:29:46.8708628Z time="2020-08-01T03:29:45Z" level=debug msg="TIMESTAMP  GROUP        KIND   NAMESPACE                  NAME    STATUS   HEALTH        HOOK  MESSAGE\n\nName:               test-one-progressing-deployment-is-succeeded-and-synced\nProject:            default\nServer:             https://kubernetes.default.svc\nNamespace:          argocd-e2e--test-one-progressing-deployment-is-succeeded--xzsyz\nURL:                http://127.0.0.1:8088/applications/test-one-progressing-deployment-is-succeeded-and-synced\nRepo:               file:///tmp/argo-e2e/testdata.git\nTarget:             \nPath:               one-deployment\nSyncWindow:         Sync Allowed\nSync Policy:        <none>\nSync Status:        Synced to  (f4d3a52)\nHealth Status:      Progressing\n\nOperation:          Sync\nSync Revision:      f4d3a522d9a32948c2cf7770c5ab5cc42f69dc7b\nPhase:              Succeeded\nStart:              2020-08-01 03:29:35 +0000 UTC\nFinished:           2020-08-01 03:29:36 +0000 UTC\nDuration:           1s\nMessage:            successfully synced (all tasks run)\n\nGROUP  KIND        NAMESPACE                                                        NAME  STATUS  HEALTH       HOOK  MESSAGE\napps   Deployment  argocd-e2e--test-one-progressing-deployment-is-succeeded--xzsyz  main  Synced  Progressing        deployment.apps/main created\n" duration=10.103067867s execID=l6sEz
2020-08-01T03:29:46.8711271Z + set -eux -o pipefail
2020-08-01T03:29:46.8712363Z time="2020-08-01T03:29:45Z" level=error msg="`../../dist/argocd app sync test-one-progressing-deployment-is-succeeded-and-synced --timeout 10 --prune --plaintext --server 127.0.0.1:8088 --auth-token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1OTYyNTE5NjEsImlzcyI6ImFyZ29jZCIsIm5iZiI6MTU5NjI1MTk2MSwic3ViIjoiYWRtaW4ifQ.5hN4UNihkBkSV8QjYzAwO5rpkL3_92uye4D67yUb1fE --insecure` failed exit status 20: time=\"2020-08-01T03:29:45Z\" level=fatal msg=\"timed out (10s) waiting for app \\\"test-one-progressing-deployment-is-succeeded-and-synced\\\" match desired state\"" execID=l6sEz
2020-08-01T03:29:46.8714242Z ##[error]    TestOneProgressingDeploymentIsSucceededAndSynced: sync_waves_test.go:73: failed expectation: error
2020-08-01T03:29:46.8715745Z --- FAIL: TestOneProgressingDeploymentIsSucceededAndSynced (12.46s)
```

**Comment by pasha-codefresh** [comment]
@jannfis closing it, looks like tests work now fine
