### ISSUE TITLE
Errors caused by erroneous manifests should be reported to the UI

### ISSUE THREAD

**Issue by Bhashit** [argoproj/argo-cd#3995]
# Summary

I was trying to deploy an app using argocd. When I logged into the UI, the status was "unknown" and there was no indication of what went wrong. 

# Motivation

To find the problems faster. Make it more user-friendly.

# Logs

Following are the logs that helped me find the issue. These are from `argocd-application-controller` pod.

```
time="2020-07-24T21:31:10Z" level=info msg="getRepoObjs stats" application=external-secrets-manager build_options_ms=0 helm_ms=0 manifests_ms=221 plugins_ms=0 repo_ms=0 time_ms=221 unmarshal_ms=0 version_ms=0
time="2020-07-24T21:31:10Z" level=warning msg="Could not unmarshal to object of type /v1, Kind=ServiceAccount: json: cannot unmarshal string into Go struct field ObjectMeta.metadata.annotations of type map[string]string"
time="2020-07-24T21:31:10Z" level=info msg="Reconciliation completed" application=external-secrets-manager dest-namespace=default dest-server="https://kubernetes.default.svc" fields.level=2 time_ms=222
time="2020-07-24T21:31:10Z" level=error msg="Recovered from panic: interface conversion: interface {} is string, not map[string]interface {}\ngoroutine 99 [running]:\nruntime/debug.Stack(0xc000d1bba0, 0x1ba9820, 0xc002256de0)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x9d\ngithub.com/argoproj/argo-cd/controller.(*ApplicationController).processAppRefreshQueueItem.func1(0xc000414280, 0x1af1fc0, 0xc002afd9a0)\n\t/go/src/github.com/argoproj/argo-cd/controller/appcontroller.go:803 +0x85\npanic(0x1ba9820, 0xc002256de0)\n\t/usr/local/go/src/runtime/panic.go:973 +0x3e3\ngithub.com/argoproj/argo-cd/util/diff.removeNamespaceAnnotation(0xc002870f28, 0x0)\n\t/go/src/github.com/argoproj/argo-cd/util/diff/diff.go:188 +0x178\ngithub.com/argoproj/argo-cd/util/diff.getLegacyTwoWayDiff(0xc002870f18, 0x0, 0xc0021a4b40, 0x1cd)\n\t/go/src/github.com/argoproj/argo-cd/util/diff/diff.go:73 +0x119\ngithub.com/argoproj/argo-cd/util/diff.TwoWayDiff(0xc002870f18, 0x0, 0xc00423bac0, 0x0, 0x0)\n\t/go/src/github.com/argoproj/argo-cd/util/diff/diff.go:97 +0xed\ngithub.com/argoproj/argo-cd/util/diff.Diff(0xc002870f18, 0x0, 0x2101d00, 0xc00423bac0, 0xc001dde910, 0x0, 0x0)\n\t/go/src/github.com/argoproj/argo-cd/util/diff/diff.go:67 +0x7b\ngithub.com/argoproj/argo-cd/util/diff.DiffArray(0xc006e6dc00, 0x7, 0x8, 0xc00ccf8f80, 0x7, 0x7, 0x2101d00, 0xc00423bac0, 0x0, 0x0, ...)\n\t/go/src/github.com/argoproj/argo-cd/util/diff/diff.go:268 +0xf3\ngithub.com/argoproj/argo-cd/controller.(*appStateManager).CompareAppState(0xc000638100, 0xc001085880, 0xc0007b0f00, 0x0, 0x0, 0xc000053680, 0x35, 0xc000053600, 0x37, 0x0, ...)\n\t/go/src/github.com/argoproj/argo-cd/controller/state.go:416 +0x1ffd\ngithub.com/argoproj/argo-cd/controller.(*ApplicationController).processAppRefreshQueueItem(0xc000414280, 0x1)\n\t/go/src/github.com/argoproj/argo-cd/controller/appcontroller.go:892 +0x66e\ngithub.com/argoproj/argo-cd/controller.(*ApplicationController).Run.func3()\n\t/go/src/github.com/argoproj/argo-cd/controller/appcontroller.go:426 +0x36\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc0003bc2d0)\n\t/go/src/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x5f\nk8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0003bc2d0, 0x3b9aca00, 0x0, 0x1, 0xc00084a240)\n\t/go/src/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8\nk8s.io/apimachinery/pkg/util/wait.Until(0xc0003bc2d0, 0x3b9aca00, 0xc00084a240)\n\t/go/src/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d\ncreated by github.com/argoproj/argo-cd/controller.(*ApplicationController).Run\n\t/go/src/github.com/argoproj/argo-cd/controller/appcontroller.go:425 +0x377\n"
g]string"

```

**Comment by andrii-korotkov-verkada** [comment]
Seems reported in UI now
