### ISSUE TITLE
Recovered from panic: interface conversion: runtime.Object is *v1.Status, not *unstructured.Unstructured

### ISSUE THREAD

**Issue by mayzhang2000** [argoproj/argo-cd#3999]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a
question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [ ] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**
Controller logged quite a few errors below. It would be good to get it fixed to make the logs usable.
```
{code}DEBU[3963] Failed to watch Endpoints on https://192.168.99.103:8443: Recovered from panic: interface conversion: runtime.Object is *v1.Status, not *unstructured.Unstructured
goroutine 321 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/debug/stack.go:24 +0xa1
github.com/argoproj/gitops-engine/pkg/cache.(*clusterCache).watchEvents.func1.1(0xc000f91928)
        /Users/mayz985/go/src/github.com/argoproj/argo-cd/vendor/github.com/argoproj/gitops-engine/pkg/cache/cluster.go:424 +0x63
panic(0x3285060, 0xc0009d1ad0)
        /usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/panic.go:975 +0x41b
github.com/argoproj/gitops-engine/pkg/cache.(*clusterCache).watchEvents.func1(0x0, 0x0)
        /Users/mayz985/go/src/github.com/argoproj/argo-cd/vendor/github.com/argoproj/gitops-engine/pkg/cache/cluster.go:480 +0x13c9
github.com/argoproj/gitops-engine/pkg/utils/kube.RetryUntilSucceed.func1(0xc000f91b00, 0x0, 0x0)
        /Users/mayz985/go/src/github.com/argoproj/argo-cd/vendor/github.com/argoproj/gitops-engine/pkg/utils/kube/kube.go:375 +0x133
k8s.io/apimachinery/pkg/util/wait.WaitFor(0xc0017e6900, 0xc000f91d50, 0xc0002be720, 0x0, 0x0)
        /Users/mayz985/go/src/github.com/argoproj/argo-cd/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:434 +0x1b1
k8s.io/apimachinery/pkg/util/wait.PollUntil(0x3b9aca00, 0xc00089fd50, 0xc0006b2180, 0x0, 0x0)
        /Users/mayz985/go/src/github.com/argoproj/argo-cd/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:385 +0x153
k8s.io/apimachinery/pkg/util/wait.PollImmediateUntil(0x3b9aca00, 0xc00089fd50, 0xc0006b2180, 0x0, 0x0)
        /Users/mayz985/go/src/github.com/argoproj/argo-cd/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:404 +0x121
github.com/argoproj/gitops-engine/pkg/utils/kube.RetryUntilSucceed(0x3922580, 0xc00090c2c0, 0x3b9aca00, 0xc000c4c030, 0x2e, 0xc000c6ce40)
        /Users/mayz985/go/src/github.com/argoproj/argo-cd/vendor/github.com/argoproj/gitops-engine/pkg/utils/kube/kube.go:373 +0x101
github.com/argoproj/gitops-engine/pkg/cache.(*clusterCache).watchEvents(0xc0000d4780, 0x3922580, 0xc00090c2c0, 0x0, 0x0, 0xc0006a51a0, 0x9, 0xc0006a5190, 0x9, 0x0, ...)
        /Users/mayz985/go/src/github.com/argoproj/argo-cd/vendor/github.com/argoproj/gitops-engine/pkg/cache/cluster.go:421 +0x2dd
created by github.com/argoproj/gitops-engine/pkg/cache.(*clusterCache).sync.func1.1
        /Users/mayz985/go/src/github.com/argoproj/argo-cd/vendor/github.com/argoproj/gitops-engine/pkg/cache/cluster.go:597 +0x54e
, retrying in 1s 
{code}
```

**To Reproduce**

A list of the steps required to reproduce the issue. Best of all, give us the URL to a repository that exhibits this issue.

**Expected behavior**

**Screenshots**

**Version**

```shell
Paste the output from `argocd version` here.
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by mayzhang2000** [comment]
Fixed in https://github.com/argoproj/gitops-engine/pull/109
