### ISSUE TITLE
API server nil pointer dereference in GetSpecErrors()

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#407]
```
13:49:27  api-server | time="2018-07-13T13:49:27-07:00" level=error msg="Recovered from panic: runtime error: invalid memory address or nil pointer dereference
goroutine 7046 [running]:
runtime/debug.Stack(0xc4211a2700, 0x20d7a00, 0x31a6180)
	/usr/local/Cellar/go/1.10.3/libexec/src/runtime/debug/stack.go:24 +0xa7
github.com/argoproj/argo-cd/util/grpc.PanicLoggerUnaryServerInterceptor.func1.1(0xc4212f5180, 0xc4211a3490)
	/Users/amerenbach/go/src/github.com/argoproj/argo-cd/util/grpc/grpc.go:27 +0x6e
panic(0x20d7a00, 0x31a6180)
	/usr/local/Cellar/go/1.10.3/libexec/src/runtime/panic.go:502 +0x229
github.com/argoproj/argo-cd/util/argo.GetSpecErrors(0x280e3c0, 0xc4214b6180, 0xc42050a3c8, 0xc4202dc000, 0x27eb5c0, 0xc4201d83f0, 0x2821ee0, 0xc421420060, 0x0, 0x0, ...)
	/Users/amerenbach/go/src/github.com/argoproj/argo-cd/util/argo/argo.go:260 +0x1074
github.com/argoproj/argo-cd/server/application.(*Server).validateApp(0xc4212f8af0, 0x280e3c0, 0xc4214b6180, 0xc42050a3c8, 0xc420310001, 0x9)
	/Users/amerenbach/go/src/github.com/argoproj/argo-cd/server/application/application.go:422 +0x34b
github.com/argoproj/argo-cd/server/application.(*Server).Create(0xc4212f8af0, 0x280e3c0, 0xc4214b6180, 0xc42050a000, 0x0, 0x0, 0x0)
	/Users/amerenbach/go/src/github.com/argoproj/argo-cd/server/application/application.go:106 +0x335
github.com/argoproj/argo-cd/server/application._ApplicationService_Create_Handler.func1(0x280e3c0, 0xc4214b6180, 0x21dd5c0, 0xc42050a000, 0x0, 0xc42147b3f0, 0x102a239, 0xc4214480b0)
	/Users/amerenbach/go/src/github.com/argoproj/argo-cd/server/application/application.pb.go:810 +0x86
github.com/argoproj/argo-cd/vendor/github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x280e3c0, 0xc4214b6180, 0x21dd5c0, 0xc42050a000, 0x0, 0x0, 0x0, 0x0)
	/Users/amerenbach/go/src/github.com/argoproj/argo-cd/vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:31 +0x118
github.com/argoproj/argo-cd/util/grpc.PanicLoggerUnaryServerInterceptor.func1(0x280e3c0, 0xc4214b6180, 0x21dd5c0, 0xc42050a000, 0xc4205286a0, 0xc4200c7220, 0x0, 0x0, 0x0, 0x0)
	/Users/amerenbach/go/src/github.com/argoproj/argo-cd/util/grpc/grpc.go:31 +0x97
github.com/argoproj/argo-cd/vendor/github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x280e3c0, 0xc4214b6180, 0x21dd5c0, 0xc42050a000, 0xc420030000, 0x20f31e0, 0x225c6c0, 0x43d02f8)
	/Users/amerenbach/go/src/github.com/argoproj/argo-cd/vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:34 +0x9f
github.com/argoproj/argo-cd/util/grpc.ErrorCodeUnaryServerInterceptor.func1(0x280e3c0, 0xc4214b6180, 0x21dd5c0, 0xc42050a000, 0xc4205286a0, 0xc4200c7220, 0xc4214b6180, 0x280e3c0, 0xc4214b6180, 0x0)
	/Users/amerenbach/go/src/github.com/argoproj/argo-cd/util/grpc/errors.go:64 +0x55
github.com/argoproj/argo-cd/vendor/github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x280e3c0, 0xc4214b6180, 0x21dd5c0, 0xc42050a000, 0x0, 0x0, 0x2055e60, 0x27e67f0)
	/Users/amerenbach/go/src/github.com/argoproj/argo-cd/vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:34 +0x9f
github.com/argoproj/argo-cd/vendor/github.com/grpc-ecosystem/go-grpc-middleware/auth.UnaryServerInterceptor.func1(0x280e3c0, 0xc4214b6180, 0x21dd5c0, 0xc42050a000, 0xc4205286a0, 0xc4200c7220, 0x0, 0x0, 0x0, 0x0)
	/Users/amerenbach/go/src/github.com/argoproj/argo-cd/vendor/github.com/grpc-ecosystem/go-grpc-middleware/auth/auth.go:46 +0x10a
github.com/argoproj/argo-cd/vendor/github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x280e3c0, 0xc4214b6180, 0x21dd5c0, 0xc42050a000, 0x26, 0xbeca61f58ee31fd1, 0xad97edd7c02, 0x31ca100)
	/Users/amerenbach/go/src/github.com/argoproj/argo-cd/vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:34 +0x9f
github.com/argoproj/argo-cd/vendor/github.com/grpc-ecosystem/go-grpc-middleware/logging/logrus.UnaryServerInterceptor.func1(0x280e3c0, 0xc42145b2f0, 0x21dd5c0, 0xc42050a000, 0xc4205286a0, 0xc4200c7220, 0x1d10d2a, 0x31e9818, 0x48, 0x48)
	/Users/amerenbach/go/src/github.com/argoproj/argo-cd/vendor/github.com/grpc-ecosystem/go-grpc-middleware/logging/logrus/server_interceptors.go:32 +0x10d
github.com/argoproj/argo-cd/vendor/github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x280e3c0, 0xc42145b2f0, 0x21dd5c0, 0xc42050a000, 0x10121b9, 0xc4205286e0, 0x20, 0xc42147b980)
	/Users/amerenbach/go/src/github.com/argoproj/argo-cd/vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:34 +0x9f
github.com/argoproj/argo-cd/server.bug21955WorkaroundInterceptor(0x280e3c0, 0xc42145b2f0, 0x21dd5c0, 0xc42050a000, 0xc4205286a0, 0xc4200c7220, 0x68, 0x224a2a0, 0xc42147ba00, 0x1012a08)
	/Users/amerenbach/go/src/github.com/argoproj/argo-cd/server/server.go:617 +0xf0
github.com/argoproj/argo-cd/vendor/github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1(0x280e3c0, 0xc42145b2f0, 0x21dd5c0, 0xc42050a000, 0xc4205286a0, 0xc4205286e0, 0xc4214bfa70, 0x1012a08, 0x70, 0x224a2a0)
	/Users/amerenbach/go/src/github.com/argoproj/argo-cd/vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:39 +0x16c
github.com/argoproj/argo-cd/server/application._ApplicationService_Create_Handler(0x225c6c0, 0xc4212f8af0, 0x280e3c0, 0xc42145b2f0, 0xc421180000, 0xc42141e1b0, 0x0, 0x0, 0xc42168e1f8, 0x9)
	/Users/amerenbach/go/src/github.com/argoproj/argo-cd/server/application/application.pb.go:812 +0x167
github.com/argoproj/argo-cd/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc4202818c0, 0x2819280, 0xc4217dfb00, 0xc421179180, 0xc42141e480, 0x31b4290, 0x0, 0x0, 0x0)
	/Users/amerenbach/go/src/github.com/argoproj/argo-cd/vendor/google.golang.org/grpc/server.go:920 +0x848
github.com/argoproj/argo-cd/vendor/google.golang.org/grpc.(*Server).handleStream(0xc4202818c0, 0x2819280, 0xc4217dfb00, 0xc421179180, 0x0)
	/Users/amerenbach/go/src/github.com/argoproj/argo-cd/vendor/google.golang.org/grpc/server.go:1142 +0x1318
github.com/argoproj/argo-cd/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc42038ba80, 0xc4202818c0, 0x2819280, 0xc4217dfb00, 0xc421179180)
	/Users/amerenbach/go/src/github.com/argoproj/argo-cd/vendor/google.golang.org/grpc/server.go:637 +0x9f
created by github.com/argoproj/argo-cd/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
	/Users/amerenbach/go/src/github.com/argoproj/argo-cd/vendor/google.golang.org/grpc/server.go:635 +0xa1
"
13:49:27  api-server | time="2018-07-13T13:49:27-07:00" level=error msg="finished unary call with code Internal" error="rpc error: code = Internal desc = runtime error: invalid memory address or nil pointer dereference" grpc.code=Internal grpc.method=Create grpc.service=application.ApplicationService grpc.start_time="2018-07-13T13:49:26-07:00" grpc.time_ms=833.963 span.kind=server system=grpc
```

**Comment by merenbach** [comment]
Can reproduce with

    ./dist/argocd app create --name guestbook --repo https://github.com/argoproj/argocd-example-apps.git --path pre-post-sync --env minikube --dest-server https://`minikube ip`:8443
