### ISSUE TITLE
Panic from CLI when JSON logging enabled

### ISSUE THREAD

**Issue by k-mckinney** [argoproj/argo-cd#4117]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a
question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [ x ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ x ] I've included steps to reproduce the bug.
* [ x ] I've pasted the output of `argocd version`.

**Describe the bug**

When JSON logging is enabled, CLI commands fail when trying to log, a panic is thrown, and the `argocd-server` pod restarts.

**To Reproduce**

Start ArgoCD with JSON logging enabled:

```--logformat json```

Then make any CLI command, such as `argocd proj create foo`.

**Expected behavior**

The CLI commands should be successful, and JSON log output should be visible.

**Screenshots**

N/A

**Version**

```shell
argocd: v1.6.0+c10ae24
  BuildDate: 2020-06-16T22:41:56Z
  GitCommit: c10ae246ab02f1356147118a1979fedcd1ceb704
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.6.1+159674e
  BuildDate: 2020-06-19T00:41:05Z
  GitCommit: 159674ee844a378fb98fe297006bf7b83a6e32d2
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: {Version:kustomize/v3.6.1 GitCommit:c97fa946d576eb6ed559f17f2ac43b3b5a8d5dbd BuildDate:2020-05-27T20:47:35Z GoOs:linux GoArch:amd64}
  Helm Version: version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
  Kubectl Version: v1.14.0
```

**Logs**

```
proto: tag has too few fields: "-"
panic: interface conversion: *time.Time is not proto.Message: missing method ProtoMessage [recovered]
	panic: interface conversion: *time.Time is not proto.Message: missing method ProtoMessage

goroutine 90453 [running]:
encoding/json.(*encodeState).marshal.func1(0xc000e30ad0)
	/usr/local/go/src/encoding/json/encode.go:326 +0x9a
panic(0x1dbf160, 0xc0006d7aa0)
	/usr/local/go/src/runtime/panic.go:967 +0x166
github.com/golang/protobuf/jsonpb.(*Marshaler).marshalValue(0x3743240, 0xc000e306d0, 0xc000fb0780, 0x2021060, 0xc00004f088, 0x199, 0x0, 0x0, 0x1, 0xc000fb0780)
	/go/pkg/mod/github.com/golang/protobuf@v1.2.0/jsonpb/jsonpb.go:554 +0x1d91
github.com/golang/protobuf/jsonpb.(*Marshaler).marshalField(0x3743240, 0xc000e306d0, 0xc000fb0780, 0x2021060, 0xc00004f088, 0x199, 0x0, 0x0, 0x0, 0xc000b0cb10)
	/go/pkg/mod/github.com/golang/protobuf@v1.2.0/jsonpb/jsonpb.go:475 +0xe5
github.com/golang/protobuf/jsonpb.(*Marshaler).marshalObject(0x3743240, 0xc000e306d0, 0x7f7c73bb9920, 0xc00004f088, 0x0, 0x0, 0x0, 0x0, 0x1, 0x40c496)
	/go/pkg/mod/github.com/golang/protobuf@v1.2.0/jsonpb/jsonpb.go:333 +0x4d5
github.com/golang/protobuf/jsonpb.(*Marshaler).marshalValue(0x3743240, 0xc000e306d0, 0xc000fb06c0, 0x201ccc0, 0xc00004f088, 0x199, 0x0, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/golang/protobuf@v1.2.0/jsonpb/jsonpb.go:554 +0x1e44
github.com/golang/protobuf/jsonpb.(*Marshaler).marshalField(0x3743240, 0xc000e306d0, 0xc000fb06c0, 0x201ccc0, 0xc00004f088, 0x199, 0x0, 0x0, 0x68, 0xc000b0cad8)
	/go/pkg/mod/github.com/golang/protobuf@v1.2.0/jsonpb/jsonpb.go:475 +0xe5
github.com/golang/protobuf/jsonpb.(*Marshaler).marshalObject(0x3743240, 0xc000e306d0, 0x7f7c73bb9890, 0xc00004f020, 0x0, 0x0, 0x0, 0x0, 0x1, 0x40c496)
	/go/pkg/mod/github.com/golang/protobuf@v1.2.0/jsonpb/jsonpb.go:333 +0x4d5
github.com/golang/protobuf/jsonpb.(*Marshaler).marshalValue(0x3743240, 0xc000e306d0, 0xc000fb0540, 0x1fe79e0, 0xc00004f020, 0x199, 0x0, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/golang/protobuf@v1.2.0/jsonpb/jsonpb.go:554 +0x1e44
github.com/golang/protobuf/jsonpb.(*Marshaler).marshalField(0x3743240, 0xc000e306d0, 0xc000fb0540, 0x1fe79e0, 0xc00004f020, 0x199, 0x0, 0x0, 0x20, 0xc000b0ca28)
	/go/pkg/mod/github.com/golang/protobuf@v1.2.0/jsonpb/jsonpb.go:475 +0xe5
github.com/golang/protobuf/jsonpb.(*Marshaler).marshalObject(0x3743240, 0xc000e306d0, 0x247e600, 0xc00004f000, 0x0, 0x0, 0x0, 0x0, 0x1, 0x3)
	/go/pkg/mod/github.com/golang/protobuf@v1.2.0/jsonpb/jsonpb.go:333 +0x4d5
github.com/golang/protobuf/jsonpb.(*Marshaler).marshalValue(0x3743240, 0xc000e306d0, 0xc000fb03c0, 0x1ef9760, 0xc00004f000, 0x199, 0x0, 0x0, 0x1, 0xc000fb03c0)
	/go/pkg/mod/github.com/golang/protobuf@v1.2.0/jsonpb/jsonpb.go:554 +0x1e44
github.com/golang/protobuf/jsonpb.(*Marshaler).marshalField(0x3743240, 0xc000e306d0, 0xc000fb03c0, 0x1ef9760, 0xc00004f000, 0x199, 0x0, 0x0, 0x0, 0xc000b0c9b8)
	/go/pkg/mod/github.com/golang/protobuf@v1.2.0/jsonpb/jsonpb.go:475 +0xe5
github.com/golang/protobuf/jsonpb.(*Marshaler).marshalObject(0x3743240, 0xc000e306d0, 0x247c6c0, 0xc00004f000, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc0014471e0)
	/go/pkg/mod/github.com/golang/protobuf@v1.2.0/jsonpb/jsonpb.go:333 +0x4d5
github.com/golang/protobuf/jsonpb.(*Marshaler).Marshal(0x3743240, 0x2445d40, 0xc0006d7a40, 0x247c6c0, 0xc00004f000, 0x40a6d3, 0x1dc20e0)
	/go/pkg/mod/github.com/golang/protobuf@v1.2.0/jsonpb/jsonpb.go:138 +0x1a6
github.com/argoproj/argo-cd/util/grpc.(*jsonpbMarshalleble).MarshalJSON(0xc000ce7230, 0x1e1c760, 0xc000ce7230, 0x7f7c73dba030, 0xc000ce7230, 0xc000ce7201)
	/go/src/github.com/argoproj/argo-cd/util/grpc/logging.go:35 +0x87
encoding/json.marshalerEncoder(0xc000c78800, 0x1e1c760, 0xc000ce7230, 0x16, 0xc000ce0100)
	/usr/local/go/src/encoding/json/encode.go:477 +0xba
encoding/json.(*encodeState).reflectValue(0xc000c78800, 0x1e1c760, 0xc000ce7230, 0x16, 0xc000ce0100)
	/usr/local/go/src/encoding/json/encode.go:358 +0x82
encoding/json.interfaceEncoder(0xc000c78800, 0x1d58080, 0xc000ce7410, 0x94, 0xc000ce0100)
	/usr/local/go/src/encoding/json/encode.go:713 +0xac
encoding/json.mapEncoder.encode(0x21b4568, 0xc000c78800, 0x1dc98e0, 0xc0006d79b0, 0x15, 0x1dc0100)
	/usr/local/go/src/encoding/json/encode.go:800 +0x354
encoding/json.(*encodeState).reflectValue(0xc000c78800, 0x1dc98e0, 0xc0006d79b0, 0x15, 0xc000970100)
	/usr/local/go/src/encoding/json/encode.go:358 +0x82
encoding/json.(*encodeState).marshal(0xc000c78800, 0x1dc98e0, 0xc0006d79b0, 0x3740100, 0x0, 0x0)
	/usr/local/go/src/encoding/json/encode.go:330 +0xf0
encoding/json.(*Encoder).Encode(0xc000e30c78, 0x1dc98e0, 0xc0006d79b0, 0x5, 0xc0003fb508)
	/usr/local/go/src/encoding/json/stream.go:206 +0x8a
github.com/sirupsen/logrus.(*JSONFormatter).Format(0xc0005e0300, 0xc000729730, 0x3, 0x4, 0xc0005e3c00, 0x3, 0xc000972e90)
	/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/json_formatter.go:116 +0x623
github.com/sirupsen/logrus.(*Entry).write(0xc000729730)
	/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/entry.go:255 +0x7c
github.com/sirupsen/logrus.Entry.log(0xc0001be000, 0xc0006d7980, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/entry.go:231 +0x19e
github.com/sirupsen/logrus.(*Entry).Log(0xc0007296c0, 0x4, 0xc000973088, 0x1, 0x1)
	/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/entry.go:268 +0xeb
github.com/sirupsen/logrus.(*Entry).Info(...)
	/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/entry.go:285
github.com/argoproj/argo-cd/util/grpc.logRequest(0xc000729500, 0xc00117f2c0, 0x3a, 0x1f6f160, 0xc00004f000, 0x2496580, 0xc0006d7860, 0x1)
	/go/src/github.com/argoproj/argo-cd/util/grpc/logging.go:26 +0x106
github.com/argoproj/argo-cd/util/grpc.PayloadUnaryServerInterceptor.func1(0x2496580, 0xc0006d7860, 0x1f6f160, 0xc00004f000, 0xc000a04dc0, 0xc0008b5ae0, 0x2087d68, 0xc000a05040, 0xc000a05040, 0x1cf2300)
	/go/src/github.com/argoproj/argo-cd/util/grpc/logging.go:77 +0x196
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x2496580, 0xc0006d7860, 0x1f6f160, 0xc00004f000, 0x1e709c0, 0xc00167e608, 0x2496580, 0xc0006d7860)
	/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v0.0.0-20190222133341-cfaf5686ec79/chain.go:34 +0x9c
github.com/argoproj/argo-cd/util/grpc.UserAgentUnaryServerInterceptor.func1(0x2496580, 0xc0006d7860, 0x1f6f160, 0xc00004f000, 0xc000a04dc0, 0xc0008b5ae0, 0xc0006d75f0, 0x2496580, 0xc0006d7860, 0x0)
	/go/src/github.com/argoproj/argo-cd/util/grpc/useragent.go:22 +0xa2
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x2496580, 0xc0006d7860, 0x1f6f160, 0xc00004f000, 0x0, 0x0, 0x2459780, 0xc0005ce700)
	/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v0.0.0-20190222133341-cfaf5686ec79/chain.go:34 +0x9c
github.com/grpc-ecosystem/go-grpc-middleware/auth.UnaryServerInterceptor.func1(0x2496580, 0xc0006d75f0, 0x1f6f160, 0xc00004f000, 0xc000a04dc0, 0xc0008b5ae0, 0xc0006d7650, 0x3, 0x3, 0x7f7c73b9ca50)
	/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v0.0.0-20190222133341-cfaf5686ec79/auth/auth.go:46 +0x108
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x2496580, 0xc0006d75f0, 0x1f6f160, 0xc00004f000, 0x26, 0xc0008b5b30, 0x0, 0x0)
	/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v0.0.0-20190222133341-cfaf5686ec79/chain.go:34 +0x9c
github.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).UnaryServerInterceptor.func1(0x2496580, 0xc0006d75f0, 0x1f6f160, 0xc00004f000, 0xc000a04dc0, 0xc0008b5ae0, 0x0, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-prometheus@v1.2.0/server_metrics.go:107 +0xad
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x2496580, 0xc0006d75f0, 0x1f6f160, 0xc00004f000, 0x26, 0xbfc71736531d14fe, 0x4067d1f40321, 0x3743d80)
	/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v0.0.0-20190222133341-cfaf5686ec79/chain.go:34 +0x9c
github.com/grpc-ecosystem/go-grpc-middleware/logging/logrus.UnaryServerInterceptor.func1(0x2496580, 0xc0006d74d0, 0x1f6f160, 0xc00004f000, 0xc000a04dc0, 0xc0008b5ae0, 0x50, 0x48, 0x1f292a0, 0x0)
	/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v0.0.0-20190222133341-cfaf5686ec79/logging/logrus/server_interceptors.go:32 +0x110
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x2496580, 0xc0006d74d0, 0x1f6f160, 0xc00004f000, 0x7f7c9aa6e560, 0x0, 0xc0009739f8, 0x40c496)
	/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v0.0.0-20190222133341-cfaf5686ec79/chain.go:34 +0x9c
github.com/argoproj/argo-cd/server.bug21955WorkaroundInterceptor(0x2496580, 0xc0006d74d0, 0x1f6f160, 0xc00004f000, 0xc000a04dc0, 0xc0008b5ae0, 0xc0006d74d0, 0xc000bf88e0, 0xc000973a28, 0x40cd08)
	/go/src/github.com/argoproj/argo-cd/server/server.go:971 +0x15b
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1(0x2496580, 0xc0006d74d0, 0x1f6f160, 0xc00004f000, 0xc000a04dc0, 0xc000a04de0, 0xc000abba98, 0x4f5a78, 0x1ef7700, 0xc0006d74d0)
	/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v0.0.0-20190222133341-cfaf5686ec79/chain.go:39 +0x155
github.com/argoproj/argo-cd/pkg/apiclient/application._ApplicationService_Create_Handler(0x200a7c0, 0xc0000ccd20, 0x2496580, 0xc0006d74d0, 0xc000728930, 0xc00054ccc0, 0x2496580, 0xc0006d74d0, 0x36, 0xe)
	/go/src/github.com/argoproj/argo-cd/pkg/apiclient/application/application.pb.go:2516 +0x14b
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0008c1380, 0x24b1fc0, 0xc000ac5200, 0xc001317d00, 0xc00054d0e0, 0x3724870, 0x0, 0x0, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.15.0/server.go:982 +0x4bd
google.golang.org/grpc.(*Server).handleStream(0xc0008c1380, 0x24b1fc0, 0xc000ac5200, 0xc001317d00, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.15.0/server.go:1208 +0x11f0
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000cd30f0, 0xc0008c1380, 0x24b1fc0, 0xc000ac5200, 0xc001317d00)
	/go/pkg/mod/google.golang.org/grpc@v1.15.0/server.go:686 +0xa1
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/go/pkg/mod/google.golang.org/grpc@v1.15.0/server.go:684 +0xa1
```

If there's any other information which would be helpful, please let me know!

**Comment by k-mckinney** [comment]
We also discovered that it's not only when creating the application. `argocd proj create foo` also fails.

**Comment by igaskin** [comment]
fixed in https://github.com/argoproj/argo-cd/pull/4319
