### ISSUE TITLE
Panic occurred when change target revision on web ui

### ISSUE THREAD

**Issue by Asuforce** [argoproj/argo-cd#4510]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When I change target revision on web ui, Immediately argocd-server crashes.

**To Reproduce**

change target revision.

**Expected behavior**

do not crush

**Screenshots**

![Screen Shot 0002-10-08 at 16 20 49](https://user-images.githubusercontent.com/9331040/95427327-56b47e80-0982-11eb-8426-6659eea084c4.png)

**Version**

```shell
argocd: v1.7.6+b04c25e
  BuildDate: 2020-09-19T00:53:13Z
  GitCommit: b04c25eca8f1660359e325acd4be5338719e59a0
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.7.7+33c93ae
  BuildDate: 2020-09-29T04:56:23Z
  GitCommit: 33c93aea0b9ee3d02fb9703cd82cecce3540e954
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: {Version:kustomize/v3.6.1 GitCommit:c97fa946d576eb6ed559f17f2ac43b3b5a8d5dbd BuildDate:2020-05-27T20:47:35Z GoOs:linux GoArch:amd64}
  Helm Version: version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
  Kubectl Version: v1.17.8
```

**Logs**

```
2020/10/08 07:06:34 proto: tag has too few fields: "-"
panic: interface conversion: *time.Time is not proto.Message: missing method ProtoMessage [recovered]
        panic: interface conversion: *time.Time is not proto.Message: missing method ProtoMessage

goroutine 983 [running]:
encoding/json.(*encodeState).marshal.func1(0xc001862ad0)
        /usr/local/go/src/encoding/json/encode.go:326 +0x9a
panic(0x1f2e740, 0xc0017e70b0)
        /usr/local/go/src/runtime/panic.go:967 +0x166
github.com/golang/protobuf/jsonpb.(*Marshaler).marshalValue(0x3a40ec0, 0xc0018626d0, 0xc0018652c0, 0x21b43a0, 0xc00183ec88, 0x199, 0x0, 0x0, 0x1, 0xc0018652c0)
        /go/pkg/mod/github.com/golang/protobuf@v1.3.2/jsonpb/jsonpb.go:567 +0x1d91
github.com/golang/protobuf/jsonpb.(*Marshaler).marshalField(0x3a40ec0, 0xc0018626d0, 0xc0018652c0, 0x21b43a0, 0xc00183ec88, 0x199, 0x0, 0x0, 0x0, 0xc00184b408)
        /go/pkg/mod/github.com/golang/protobuf@v1.3.2/jsonpb/jsonpb.go:488 +0xe5
github.com/golang/protobuf/jsonpb.(*Marshaler).marshalObject(0x3a40ec0, 0xc0018626d0, 0x7f6fe8d85828, 0xc00183ec88, 0x0, 0x0, 0x0, 0x0, 0x220d705, 0xc00184b3f0)
        /go/pkg/mod/github.com/golang/protobuf@v1.3.2/jsonpb/jsonpb.go:346 +0x4d5
github.com/golang/protobuf/jsonpb.(*Marshaler).marshalValue(0x3a40ec0, 0xc0018626d0, 0xc001865200, 0x21b1200, 0xc00183ec88, 0x199, 0x0, 0x0, 0x0, 0x0)
        /go/pkg/mod/github.com/golang/protobuf@v1.3.2/jsonpb/jsonpb.go:567 +0x1e44
github.com/golang/protobuf/jsonpb.(*Marshaler).marshalField(0x3a40ec0, 0xc0018626d0, 0xc001865200, 0x21b1200, 0xc00183ec88, 0x199, 0x0, 0x0, 0x68, 0xc00184b3e0)
        /go/pkg/mod/github.com/golang/protobuf@v1.3.2/jsonpb/jsonpb.go:488 +0xe5
github.com/golang/protobuf/jsonpb.(*Marshaler).marshalObject(0x3a40ec0, 0xc0018626d0, 0x7f6fe8d85758, 0xc00183ec20, 0x0, 0x0, 0x0, 0x0, 0x220d741, 0x40c4b6)
        /go/pkg/mod/github.com/golang/protobuf@v1.3.2/jsonpb/jsonpb.go:346 +0x4d5
github.com/golang/protobuf/jsonpb.(*Marshaler).marshalValue(0x3a40ec0, 0xc0018626d0, 0xc001864cc0, 0x2177380, 0xc00183ec20, 0x199, 0x0, 0x0, 0x0, 0x0)
        /go/pkg/mod/github.com/golang/protobuf@v1.3.2/jsonpb/jsonpb.go:567 +0x1e44
github.com/golang/protobuf/jsonpb.(*Marshaler).marshalField(0x3a40ec0, 0xc0018626d0, 0xc001864cc0, 0x2177380, 0xc00183ec20, 0x199, 0x0, 0x0, 0x20, 0xc00184b248)
        /go/pkg/mod/github.com/golang/protobuf@v1.3.2/jsonpb/jsonpb.go:488 +0xe5
github.com/golang/protobuf/jsonpb.(*Marshaler).marshalObject(0x3a40ec0, 0xc0018626d0, 0x2665c80, 0xc00183ec00, 0x0, 0x0, 0x0, 0x0, 0x1ef0b80, 0xc00011c8d0)
        /go/pkg/mod/github.com/golang/protobuf@v1.3.2/jsonpb/jsonpb.go:346 +0x4d5
github.com/golang/protobuf/jsonpb.(*Marshaler).marshalValue(0x3a40ec0, 0xc0018626d0, 0xc001864b40, 0x21d9420, 0xc0017e6600, 0x196, 0x0, 0x0, 0x1, 0xc001864b40)
        /go/pkg/mod/github.com/golang/protobuf@v1.3.2/jsonpb/jsonpb.go:567 +0x1e44
github.com/golang/protobuf/jsonpb.(*Marshaler).marshalField(0x3a40ec0, 0xc0018626d0, 0xc001864b40, 0x21d9420, 0xc0017e6600, 0x196, 0x0, 0x0, 0x0, 0xc00184b1d8)
        /go/pkg/mod/github.com/golang/protobuf@v1.3.2/jsonpb/jsonpb.go:488 +0xe5
github.com/golang/protobuf/jsonpb.(*Marshaler).marshalObject(0x3a40ec0, 0xc0018626d0, 0x26641c0, 0xc0017e6600, 0x0, 0x0, 0x0, 0x0, 0x2, 0xc00106d450)
        /go/pkg/mod/github.com/golang/protobuf@v1.3.2/jsonpb/jsonpb.go:346 +0x4d5
github.com/golang/protobuf/jsonpb.(*Marshaler).Marshal(0x3a40ec0, 0x2629b20, 0xc0017e6c90, 0x26641c0, 0xc0017e6600, 0x40a6f3, 0x1f316c0)
        /go/pkg/mod/github.com/golang/protobuf@v1.3.2/jsonpb/jsonpb.go:139 +0x1a6
github.com/argoproj/argo-cd/util/grpc.(*jsonpbMarshalleble).MarshalJSON(0xc001749dd0, 0x1f93720, 0xc001749dd0, 0x7f6fe8fbed58, 0xc001749dd0, 0xc001749d01)
        /go/src/github.com/argoproj/argo-cd/util/grpc/logging.go:35 +0x87
encoding/json.marshalerEncoder(0xc000db1280, 0x1f93720, 0xc001749dd0, 0x16, 0xc001740100)
        /usr/local/go/src/encoding/json/encode.go:477 +0xba
encoding/json.(*encodeState).reflectValue(0xc000db1280, 0x1f93720, 0xc001749dd0, 0x16, 0xc001740100)
        /usr/local/go/src/encoding/json/encode.go:358 +0x82
encoding/json.interfaceEncoder(0xc000db1280, 0x1ec1000, 0xc001749ee0, 0x94, 0xc001740100)
        /usr/local/go/src/encoding/json/encode.go:713 +0xac
encoding/json.mapEncoder.encode(0x2371c70, 0xc000db1280, 0x1f36940, 0xc0017e6c00, 0x15, 0x1f30100)
        /usr/local/go/src/encoding/json/encode.go:800 +0x354
encoding/json.(*encodeState).reflectValue(0xc000db1280, 0x1f36940, 0xc0017e6c00, 0x15, 0xc001860100)
        /usr/local/go/src/encoding/json/encode.go:358 +0x82
encoding/json.(*encodeState).marshal(0xc000db1280, 0x1f36940, 0xc0017e6c00, 0xc000100100, 0x0, 0x0)
        /usr/local/go/src/encoding/json/encode.go:330 +0xf0
encoding/json.(*Encoder).Encode(0xc001862c78, 0x1f36940, 0xc0017e6c00, 0x5, 0xc000407e28)
        /usr/local/go/src/encoding/json/stream.go:206 +0x8a
github.com/sirupsen/logrus.(*JSONFormatter).Format(0xc00029d100, 0xc0017b4a80, 0x470732, 0x3, 0x0, 0x455549, 0xc001862e90)
        /go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/json_formatter.go:120 +0x63d
github.com/sirupsen/logrus.(*Entry).write(0xc0017b4a80)
        /go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/entry.go:275 +0x7c
github.com/sirupsen/logrus.Entry.log(0xc000148000, 0xc0017e6bd0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/entry.go:251 +0x1c2
github.com/sirupsen/logrus.(*Entry).Log(0xc0017b4a10, 0x4, 0xc001863088, 0x1, 0x1)
        /go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/entry.go:287 +0xeb
github.com/sirupsen/logrus.(*Entry).Info(...)
        /go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/entry.go:304
github.com/argoproj/argo-cd/util/grpc.logRequest(0xc0017b4930, 0xc0015c1900, 0x3a, 0x20f9240, 0xc0017e6600, 0x267fd00, 0xc0017e6ab0, 0x1)
        /go/src/github.com/argoproj/argo-cd/util/grpc/logging.go:26 +0x106
github.com/argoproj/argo-cd/util/grpc.PayloadUnaryServerInterceptor.func1(0x267fd00, 0xc0017e6ab0, 0x20f9240, 0xc0017e6600, 0xc0017e3140, 0xc00173dcc0, 0x221dadb, 0xc0017e3520, 0xc0017e3520, 0x1e5ab20)
        /go/src/github.com/argoproj/argo-cd/util/grpc/logging.go:77 +0x196
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x267fd00, 0xc0017e6ab0, 0x20f9240, 0xc0017e6600, 0x2063d60, 0xc0017e6a80, 0x267fd00, 0xc0017e6ab0)
        /go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.1-0.20190118093823-f849b5445de4/chain.go:34 +0x9c
github.com/argoproj/argo-cd/util/grpc.UserAgentUnaryServerInterceptor.func1(0x267fd00, 0xc0017e6ab0, 0x20f9240, 0xc0017e6600, 0xc0017e3140, 0xc00173dcc0, 0xc0017e6750, 0x267fd00, 0xc0017e6ab0, 0x0)
        /go/src/github.com/argoproj/argo-cd/util/grpc/useragent.go:22 +0xa2
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x267fd00, 0xc0017e6ab0, 0x20f9240, 0xc0017e6600, 0x0, 0x0, 0x263de00, 0xc0007e8400)
        /go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.1-0.20190118093823-f849b5445de4/chain.go:34 +0x9c
github.com/grpc-ecosystem/go-grpc-middleware/auth.UnaryServerInterceptor.func1(0x267fd00, 0xc0017e6750, 0x20f9240, 0xc0017e6600, 0xc0017e3140, 0xc00173dcc0, 0xc0017e67b0, 0x3, 0x3, 0x7f6fe8daff70)
        /go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.1-0.20190118093823-f849b5445de4/auth/auth.go:46 +0x108
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x267fd00, 0xc0017e6750, 0x20f9240, 0xc0017e6600, 0x26, 0xc00173dd10, 0x0, 0x0)
        /go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.1-0.20190118093823-f849b5445de4/chain.go:34 +0x9c
github.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).UnaryServerInterceptor.func1(0x267fd00, 0xc0017e6750, 0x20f9240, 0xc0017e6600, 0xc0017e3140, 0xc00173dcc0, 0x0, 0x0, 0x0, 0x0)
        /go/pkg/mod/github.com/grpc-ecosystem/go-grpc-prometheus@v1.2.0/server_metrics.go:107 +0xad
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x267fd00, 0xc0017e6750, 0x20f9240, 0xc0017e6600, 0x26, 0xbfd7cc7eb8cb4162, 0x1295e2949e, 0x3a41be0)
        /go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.1-0.20190118093823-f849b5445de4/chain.go:34 +0x9c
github.com/grpc-ecosystem/go-grpc-middleware/logging/logrus.UnaryServerInterceptor.func1(0x267fd00, 0xc0017e65d0, 0x20f9240, 0xc0017e6600, 0xc0017e3140, 0xc00173dcc0, 0x50, 0x48, 0x20b10c0, 0x0)
        /go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.1-0.20190118093823-f849b5445de4/logging/logrus/server_interceptors.go:32 +0x110
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x267fd00, 0xc0017e65d0, 0x20f9240, 0xc0017e6600, 0x7f700fc2b560, 0x0, 0xc0001139f8, 0x40c4b6)
        /go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.1-0.20190118093823-f849b5445de4/chain.go:34 +0x9c
github.com/argoproj/argo-cd/server.bug21955WorkaroundInterceptor(0x267fd00, 0xc0017e65d0, 0x20f9240, 0xc0017e6600, 0xc0017e3140, 0xc00173dcc0, 0xc0017e65d0, 0xc0017e2f00, 0xc000113a28, 0x40cd28)
        /go/src/github.com/argoproj/argo-cd/server/server.go:1014 +0x15b
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1(0x267fd00, 0xc0017e65d0, 0x20f9240, 0xc0017e6600, 0xc0017e3140, 0xc0017e3160, 0xc001450a98, 0x4f5cb8, 0x207ad20, 0xc0017e65d0)
        /go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.1-0.20190118093823-f849b5445de4/chain.go:39 +0x155
github.com/argoproj/argo-cd/pkg/apiclient/application._ApplicationService_Update_Handler(0x219c2e0, 0xc0005404d0, 0x267fd00, 0xc0017e65d0, 0xc0017b4620, 0xc0007fa840, 0x267fd00, 0xc0017e65d0, 0x20, 0xc0015c2a60)
        /go/src/github.com/argoproj/argo-cd/pkg/apiclient/application/application.pb.go:2681 +0x14b
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000962780, 0x269f500, 0xc000ce7b00, 0xc001a5be00, 0xc0007fad80, 0x3a20e48, 0x0, 0x0, 0x0)
        /go/pkg/mod/google.golang.org/grpc@v1.15.0/server.go:982 +0x4bd
google.golang.org/grpc.(*Server).handleStream(0xc000962780, 0x269f500, 0xc000ce7b00, 0xc001a5be00, 0x0)
        /go/pkg/mod/google.golang.org/grpc@v1.15.0/server.go:1208 +0x11f0
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000b08170, 0xc000962780, 0x269f500, 0xc000ce7b00, 0xc001a5be00)
        /go/pkg/mod/google.golang.org/grpc@v1.15.0/server.go:686 +0xa1
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /go/pkg/mod/google.golang.org/grpc@v1.15.0/server.go:684 +0xa1
```

**Comment by Asuforce** [comment]
Seemed to be this problem
https://github.com/argoproj/argo-cd/issues/4117
