### ISSUE TITLE
"failed to create new OS thread" application controller error

### ISSUE THREAD

**Issue by hintofbasil** [argoproj/argo-cd#4692]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

During normal operation we hit an error `runtime: failed to create new OS thread (have 64 already; errno=12)` in the application controller.  A dump of the logs around this error is provided below.

We run ArgoCD with 10CPU and 6Gi memory limits and requests.  We are frequently running at 90%+ CPU for long periods of time.

**To Reproduce**

Unsure how to reproduce reliably.  Assuming this is an issue with how much we are pushing the application server.  Will continue to monitor to see if it happens regularly.

**Expected behavior**

Expect the application not to crash.

**Screenshots**

**Version**

```shell
argocd: v1.7.8+ef5010c.dirty
  BuildDate: 2020-10-16T04:56:45Z
  GitCommit: ef5010c3a0b5e027fd642732d03c5b0391b1e574
  GitTreeState: dirty
  GoVersion: go1.15.2
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.6.2+3d1f37b
  BuildDate: 2020-07-31T23:45:07Z
  GitCommit: 3d1f37b0c53f4c75864dc7339e2831c6e6a947e0
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: {Version:kustomize/v3.6.1 GitCommit:c97fa946d576eb6ed559f17f2ac43b3b5a8d5dbd BuildDate:2020-05-27T20:47:35Z GoOs:linux GoArch:amd64}
  Helm Version: version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
  Kubectl Version: v1.14.0
```

**Logs**

```shell
time="2020-10-28T12:14:01Z" level=debug msg="Chose API 'serviceentries' for networking.istio.io/v1alpha3, Kind=ServiceEntry"
time="2020-10-28T12:14:01Z" level=debug msg="Start watch Alertmanager.monitoring.coreos.com on https://api.cells-2-eu-central-1a-1.cells-2.skyscannerplatform.net"
time="2020-10-28T12:14:01Z" level=debug msg="Chose API 'rolebindings' for rbac.authorization.k8s.io/v1, Kind=RoleBinding"
time="2020-10-28T12:14:01Z" level=debug msg="Failed to watch ServiceMonitor.monitoring.coreos.com on https://api.heritage-ap-southeast-1-1.heritage.skyscannerplatfor
m.net: Watch ServiceMonitor.monitoring.coreos.com on https://api.heritage-ap-southeast-1-1.heritage.skyscannerplatform.net has closed, retrying in 1s"
time="2020-10-28T12:14:01Z" level=debug msg="Start watch PodMonitor.monitoring.coreos.com on https://api.heritage-eu-west-1-1.heritage.skyscannerplatform.net"
time="2020-10-28T12:14:01Z" level=debug msg="Chose API 'serviceentries' for networking.istio.io/v1alpha3, Kind=ServiceEntry"
time="2020-10-28T12:14:01Z" level=debug msg="Chose API 'authorizationpolicies' for security.istio.io/v1beta1, Kind=AuthorizationPolicy"
time="2020-10-28T12:14:01Z" level=debug msg="Chose API 'destinationrules' for networking.istio.io/v1alpha3, Kind=DestinationRule"
time="2020-10-28T12:14:01Z" level=debug msg="Failed to watch HTTPAPISpec.config.istio.io on https://api.cells-1-eu-west-1a-2.cells-1.skyscannerplatform.net: Watch HT
TPAPISpec.config.istio.io on https://api.cells-1-eu-west-1a-2.cells-1.skyscannerplatform.net has closed, retrying in 1s"
runtime: failed to create new OS thread (have 64 already; errno=12)
fatal error: newosproc

runtime stack:
runtime.throw(0x1e12520, 0x9)
        /usr/local/go/src/runtime/panic.go:1114 +0x72
runtime.newosproc(0xc062f38a80)
        /usr/local/go/src/runtime/os_linux.go:161 +0x1ba
runtime.newm1(0xc062f38a80)
        /usr/local/go/src/runtime/proc.go:1753 +0xdc
runtime.newm(0x0, 0xc000065800)
        /usr/local/go/src/runtime/proc.go:1732 +0x8f
runtime.startm(0xc000065800, 0x32b8e00)
        /usr/local/go/src/runtime/proc.go:1869 +0x12a
runtime.handoffp(0xc000065800)
        /usr/local/go/src/runtime/proc.go:1896 +0x52
runtime.retake(0x3b9e88fab244, 0xc000068000)
        /usr/local/go/src/runtime/proc.go:4628 +0x157
runtime.sysmon()
        /usr/local/go/src/runtime/proc.go:4537 +0x138
runtime.mstart1()
        /usr/local/go/src/runtime/proc.go:1097 +0xc3
runtime.mstart()
        /usr/local/go/src/runtime/proc.go:1062 +0x6e


goroutine 1 [select (no cases), 2 minutes]:
main.newCommand.func1(0xc0002f2c80, 0xc0004fa780, 0x0, 0xc, 0x0, 0x0)
        /go/src/github.com/argoproj/argo-cd/cmd/argocd-application-controller/main.go:110 +0x920
github.com/spf13/cobra.(*Command).execute(0xc0002f2c80, 0xc00004c900, 0xc, 0xc, 0xc0002f2c80, 0xc00004c900)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x453
github.com/spf13/cobra.(*Command).ExecuteC(0xc0002f2c80, 0xc0000b2778, 0xc000161f78, 0x405b0f)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main()
        /go/src/github.com/argoproj/argo-cd/cmd/argocd-application-controller/main.go:133 +0x2b

goroutine 6 [chan receive]:
k8s.io/klog.(*loggingT).flushDaemon(0x32b8840)
        /go/pkg/mod/k8s.io/klog@v1.0.0/klog.go:1010 +0x8b
created by k8s.io/klog.init.0
        /go/pkg/mod/k8s.io/klog@v1.0.0/klog.go:411 +0xd6

goroutine 4567 [select, 2 minutes]:
github.com/argoproj/gitops-engine/pkg/utils/kube.RetryUntilSucceed.func1(0x2161340, 0xc0045f5380, 0xc008406570, 0xc000b37680)
        /go/pkg/mod/github.com/argoproj/gitops-engine@v0.1.3/pkg/utils/kube/kube.go:376 +0xb7
created by github.com/argoproj/gitops-engine/pkg/utils/kube.RetryUntilSucceed
        /go/pkg/mod/github.com/argoproj/gitops-engine@v0.1.3/pkg/utils/kube/kube.go:375 +0xd4

goroutine 16 [chan receive]:
github.com/go-redis/redis/internal/pool.(*ConnPool).reaper(0xc0001a4000, 0xdf8475800)
        /go/pkg/mod/github.com/go-redis/redis@v6.15.6+incompatible/internal/pool/pool.go:449 +0x8d
created by github.com/go-redis/redis/internal/pool.NewConnPool
        /go/pkg/mod/github.com/go-redis/redis@v6.15.6+incompatible/internal/pool/pool.go:99 +0x1af
```

**Comment by jessesuen** [comment]
> We run ArgoCD with 10CPU and 6Gi memory limits and requests. We are frequently running at 90%+ CPU for long periods of time.

Could you provide some information about the size of your environment?
* # clusters
* # applications
* # resources in cluster(s)
* kubectl api-resources

Do you use the AWS exec plugin auth?

Consider tuning down the number of concurrent kubectl interactions using `--kubectl-parallelism-limit`. See: https://argoproj.github.io/argo-cd/operator-manual/high_availability/#argocd-application-controller

> The controller uses kubectl fork/exec to push changes into the cluster and to convert resource from preferred version into user specified version (e.g. Deployment apps/v1 into extensions/v1beta1). Same as config management tool kubectl fork/exec might cause pod OOM kill. Use --kubectl-parallelism-limit flag to limit number of allowed concurrent kubectl fork/execs.

**Comment by hintofbasil** [comment]
> number of clusters

33

> number of applications

35 (3 app of apps + 32 high resource apps)

> number of resources in cluster(s)

~2100 deployed by each of the high resource apps.

> kubectl api-resources

~100 api-resources per cluster - varies slightly depending on the cluster.

> Do you use the AWS exec plugin auth?

No

> Consider tuning down the number of concurrent kubectl interactions using --kubectl-parallelism-limit.

If we see the issue again we will try using that flag.  So far it seems to be a one off.
