### ISSUE TITLE
Issue during adding app to cluster 

### ISSUE THREAD

**Issue by I327358** [argoproj/argo-cd#4776]
Stacktrace:

TypeError: Cannot read property 'split' of undefined
    at m.match (https://dashboard.ingress.argocd.lp.shoot.live.k8s-hana.ondemand.com/main.2e65a524d04617fac156.js:33:480154)
    at h (https://dashboard.ingress.argocd.lp.shoot.live.k8s-hana.ondemand.com/main.2e65a524d04617fac156.js:33:474962)
    at https://dashboard.ingress.argocd.lp.shoot.live.k8s-hana.ondemand.com/main.2e65a524d04617fac156.js:33:313777
    at Array.some (<anonymous>)
    at https://dashboard.ingress.argocd.lp.shoot.live.k8s-hana.ondemand.com/main.2e65a524d04617fac156.js:33:313752
    at Array.filter (<anonymous>)
    at ec (https://dashboard.ingress.argocd.lp.shoot.live.k8s-hana.ondemand.com/main.2e65a524d04617fac156.js:33:313337)
    at Object.children (https://dashboard.ingress.argocd.lp.shoot.live.k8s-hana.ondemand.com/main.2e65a524d04617fac156.js:33:319077)
    at t.render (https://dashboard.ingress.argocd.lp.shoot.live.k8s-hana.ondemand.com/main.2e65a524d04617fac156.js:33:86283)
    at Oi (https://dashboard.ingress.argocd.lp.shoot.live.k8s-hana.ondemand.com/main.2e65a524d04617fac156.js:354:63228)

**Comment by jessesuen** [comment]
Could you provide more details (e.g. procedure to reproduce, app to reproduce, etc...). Also what version?

**Comment by alexmt** [comment]
The Javascript file name matches v1.7.7 version. I think this bug was fixed in v1.7.8 release https://github.com/argoproj/argo-cd/issues/4134

@I327358 please try upgrading to v1.7.8

**Comment by jessesuen** [comment]
Duplicate of https://github.com/argoproj/argo-cd/issues/4134
