### ISSUE TITLE
Server crash when set "logFormat: json"

### ISSUE THREAD

**Issue by kfirfer** [argoproj/argo-cd#5067]
Hello

When I try to add application in argo CD UI, the server pod is crashes, and this is the output logs:

```
vostro@dev101:~/code/kfirfer/go-sample$ kubectl logs argo-cd-argocd-server-794867f4c-qt4pv
{"level":"info","msg":"Starting configmap/secret informers","time":"2020-12-16T02:48:31Z"}
{"level":"info","msg":"Configmap/secret informer synced","time":"2020-12-16T02:48:31Z"}
{"level":"info","msg":"Starting configmap/secret informers","time":"2020-12-16T02:48:31Z"}
{"level":"info","msg":"secrets informer cancelled","time":"2020-12-16T02:48:31Z"}
{"level":"info","msg":"configmap informer cancelled","time":"2020-12-16T02:48:31Z"}
{"level":"info","msg":"Configmap/secret informer synced","time":"2020-12-16T02:48:31Z"}
{"level":"info","msg":"Starting configmap/secret informers","time":"2020-12-16T02:48:31Z"}
{"level":"info","msg":"secrets informer cancelled","time":"2020-12-16T02:48:31Z"}
{"level":"info","msg":"configmap informer cancelled","time":"2020-12-16T02:48:31Z"}
{"level":"info","msg":"Configmap/secret informer synced","time":"2020-12-16T02:48:31Z"}
{"level":"info","msg":"Starting configmap/secret informers","time":"2020-12-16T02:48:31Z"}
{"level":"info","msg":"secrets informer cancelled","time":"2020-12-16T02:48:31Z"}
{"level":"info","msg":"configmap informer cancelled","time":"2020-12-16T02:48:31Z"}
{"level":"info","msg":"Configmap/secret informer synced","time":"2020-12-16T02:48:31Z"}
{"level":"info","msg":"argocd v1.7.6+b04c25e serving on port 8080 (url: https://argocd.tatzan.com, tls: false, namespace: argo-cd, sso: false)","time":"2020-12-16T02:48:31Z"}
{"level":"info","msg":"0xc000529860 subscribed to settings updates","time":"2020-12-16T02:48:31Z"}
{"level":"info","msg":"Starting rbac config informer","time":"2020-12-16T02:48:31Z"}
{"level":"info","msg":"RBAC ConfigMap 'argocd-rbac-cm' added","time":"2020-12-16T02:48:31Z"}
{"grpc.method":"Watch","grpc.request.claims":"{\"iat\":1608085642,\"iss\":\"argocd\",\"nbf\":1608085642,\"sub\":\"admin\"}","grpc.request.content":{"resourceVersion":"29787157"},"grpc.service":"application.ApplicationService","grpc.start_time":"2020-12-16T02:48:32Z","level":"info","msg":"received streaming call /application.ApplicationService/Watch","span.kind":"server","system":"grpc","time":"2020-12-16T02:48:32Z"}
2020/12/16 02:48:59 proto: tag has too few fields: "-"
panic: interface conversion: *time.Time is not proto.Message: missing method ProtoMessage [recovered]
        panic: interface conversion: *time.Time is not proto.Message: missing method ProtoMessage

goroutine 400 [running]:
encoding/json.(*encodeState).marshal.func1(0xc000a6ead0)
        /usr/local/go/src/encoding/json/encode.go:326 +0x9a
panic(0x1f2e740, 0xc000982810)
        /usr/local/go/src/runtime/panic.go:967 +0x166
github.com/golang/protobuf/jsonpb.(*Marshaler).marshalValue(0x3a40ec0, 0xc000a6e6d0, 0xc001102480, 0x21b43a0, 0xc000998088, 0x199, 0x0, 0x0, 0x1, 0xc001102480)
        /go/pkg/mod/github.com/golang/protobuf@v1.3.2/jsonpb/jsonpb.go:567 +0x1d91
github.com/golang/protobuf/jsonpb.(*Marshaler).marshalField(0x3a40ec0, 0xc000a6e6d0, 0xc001102480, 0x21b43a0, 0xc000998088, 0x199, 0x0, 0x0, 0x0, 0xc0000c52e8)
        /go/pkg/mod/github.com/golang/protobuf@v1.3.2/jsonpb/jsonpb.go:488 +0xe5
github.com/golang/protobuf/jsonpb.(*Marshaler).marshalObject(0x3a40ec0, 0xc000a6e6d0, 0x7fd8c3e1faf8, 0xc000998088, 0x0, 0x0, 0x0, 0x0, 0x220d741, 0x1)
        /go/pkg/mod/github.com/golang/protobuf@v1.3.2/jsonpb/jsonpb.go:346 +0x4d5
github.com/golang/protobuf/jsonpb.(*Marshaler).marshalValue(0x3a40ec0, 0xc000a6e6d0, 0xc0011023c0, 0x21b1200, 0xc000998088, 0x199, 0x0, 0x0, 0x0, 0x0)
        /go/pkg/mod/github.com/golang/protobuf@v1.3.2/jsonpb/jsonpb.go:567 +0x1e44
github.com/golang/protobuf/jsonpb.(*Marshaler).marshalField(0x3a40ec0, 0xc000a6e6d0, 0xc0011023c0, 0x21b1200, 0xc000998088, 0x199, 0x0, 0x0, 0x68, 0xc0000c52c0)
        /go/pkg/mod/github.com/golang/protobuf@v1.3.2/jsonpb/jsonpb.go:488 +0xe5
github.com/golang/protobuf/jsonpb.(*Marshaler).marshalObject(0x3a40ec0, 0xc000a6e6d0, 0x7fd8c3e1fa68, 0xc000998020, 0x0, 0x0, 0x0, 0x0, 0x220d741, 0x1)
        /go/pkg/mod/github.com/golang/protobuf@v1.3.2/jsonpb/jsonpb.go:346 +0x4d5
github.com/golang/protobuf/jsonpb.(*Marshaler).marshalValue(0x3a40ec0, 0xc000a6e6d0, 0xc001102240, 0x2177380, 0xc000998020, 0x199, 0x0, 0x0, 0x0, 0x0)
        /go/pkg/mod/github.com/golang/protobuf@v1.3.2/jsonpb/jsonpb.go:567 +0x1e44
github.com/golang/protobuf/jsonpb.(*Marshaler).marshalField(0x3a40ec0, 0xc000a6e6d0, 0xc001102240, 0x2177380, 0xc000998020, 0x199, 0x0, 0x0, 0x20, 0xc0000c5020)
        /go/pkg/mod/github.com/golang/protobuf@v1.3.2/jsonpb/jsonpb.go:488 +0xe5
github.com/golang/protobuf/jsonpb.(*Marshaler).marshalObject(0x3a40ec0, 0xc000a6e6d0, 0x2665c80, 0xc000998000, 0x0, 0x0, 0x0, 0x0, 0x220d741, 0x1)
        /go/pkg/mod/github.com/golang/protobuf@v1.3.2/jsonpb/jsonpb.go:346 +0x4d5
github.com/golang/protobuf/jsonpb.(*Marshaler).marshalValue(0x3a40ec0, 0xc000a6e6d0, 0xc001102000, 0x207d3a0, 0xc000998000, 0x199, 0x0, 0x0, 0x1, 0xc001102000)
        /go/pkg/mod/github.com/golang/protobuf@v1.3.2/jsonpb/jsonpb.go:567 +0x1e44
github.com/golang/protobuf/jsonpb.(*Marshaler).marshalField(0x3a40ec0, 0xc000a6e6d0, 0xc001102000, 0x207d3a0, 0xc000998000, 0x199, 0x0, 0x0, 0x0, 0xc0000c4fa0)
        /go/pkg/mod/github.com/golang/protobuf@v1.3.2/jsonpb/jsonpb.go:488 +0xe5
github.com/golang/protobuf/jsonpb.(*Marshaler).marshalObject(0x3a40ec0, 0xc000a6e6d0, 0x2663a80, 0xc000998000, 0x0, 0x0, 0x0, 0x0, 0x3, 0xc0002f49c0)
        /go/pkg/mod/github.com/golang/protobuf@v1.3.2/jsonpb/jsonpb.go:346 +0x4d5
github.com/golang/protobuf/jsonpb.(*Marshaler).Marshal(0x3a40ec0, 0x2629b20, 0xc0009827b0, 0x2663a80, 0xc000998000, 0x40a6f3, 0x1f316c0)
        /go/pkg/mod/github.com/golang/protobuf@v1.3.2/jsonpb/jsonpb.go:139 +0x1a6
github.com/argoproj/argo-cd/util/grpc.(*jsonpbMarshalleble).MarshalJSON(0xc000a5e5a0, 0x1f93720, 0xc000a5e5a0, 0x7fd8c3da33c8, 0xc000a5e5a0, 0xc000a5e501)
        /go/src/github.com/argoproj/argo-cd/util/grpc/logging.go:35 +0x87
encoding/json.marshalerEncoder(0xc000cd2180, 0x1f93720, 0xc000a5e5a0, 0x16, 0xc000a50100)
        /usr/local/go/src/encoding/json/encode.go:477 +0xba
encoding/json.(*encodeState).reflectValue(0xc000cd2180, 0x1f93720, 0xc000a5e5a0, 0x16, 0xc000a50100)
        /usr/local/go/src/encoding/json/encode.go:358 +0x82
encoding/json.interfaceEncoder(0xc000cd2180, 0x1ec1000, 0xc000a5e6b0, 0x94, 0xc000a50100)
        /usr/local/go/src/encoding/json/encode.go:713 +0xac
encoding/json.mapEncoder.encode(0x2371c70, 0xc000cd2180, 0x1f36940, 0xc000982720, 0x15, 0x1f30100)
        /usr/local/go/src/encoding/json/encode.go:800 +0x354
encoding/json.(*encodeState).reflectValue(0xc000cd2180, 0x1f36940, 0xc000982720, 0x15, 0xc000d00100)
        /usr/local/go/src/encoding/json/encode.go:358 +0x82
encoding/json.(*encodeState).marshal(0xc000cd2180, 0x1f36940, 0xc000982720, 0xc000700100, 0x0, 0x0)
        /usr/local/go/src/encoding/json/encode.go:330 +0xf0
encoding/json.(*Encoder).Encode(0xc000a6ec78, 0x1f36940, 0xc000982720, 0x5, 0xc0002469b8)
        /usr/local/go/src/encoding/json/stream.go:206 +0x8a
github.com/sirupsen/logrus.(*JSONFormatter).Format(0xc00063eb00, 0xc000350f50, 0xc000d00e48, 0x534dbd, 0x1ff3da0, 0xc0009826f0, 0xc000d00e90)
        /go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/json_formatter.go:120 +0x63d
github.com/sirupsen/logrus.(*Entry).write(0xc000350f50)
        /go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/entry.go:275 +0x7c
github.com/sirupsen/logrus.Entry.log(0xc000128000, 0xc0009826c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/entry.go:251 +0x1c2
github.com/sirupsen/logrus.(*Entry).Log(0xc000350ee0, 0x4, 0xc000d01088, 0x1, 0x1)
        /go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/entry.go:287 +0xeb
github.com/sirupsen/logrus.(*Entry).Info(...)
        /go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/entry.go:304
github.com/argoproj/argo-cd/util/grpc.logRequest(0xc000350e00, 0xc000ac02c0, 0x3a, 0x210a940, 0xc000998000, 0x267fd00, 0xc0009825a0, 0x1)
        /go/src/github.com/argoproj/argo-cd/util/grpc/logging.go:26 +0x106
github.com/argoproj/argo-cd/util/grpc.PayloadUnaryServerInterceptor.func1(0x267fd00, 0xc0009825a0, 0x210a940, 0xc000998000, 0xc0005aaf80, 0xc000a7e7d0, 0x221dadb, 0xc0005ab3c0, 0xc0005ab3c0, 0x1e5ab20)
        /go/src/github.com/argoproj/argo-cd/util/grpc/logging.go:77 +0x196
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x267fd00, 0xc0009825a0, 0x210a940, 0xc000998000, 0x1febee0, 0xc0007ae038, 0x267fd00, 0xc0009825a0)
        /go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.1-0.20190118093823-f849b5445de4/chain.go:34 +0x9c
github.com/argoproj/argo-cd/util/grpc.UserAgentUnaryServerInterceptor.func1(0x267fd00, 0xc0009825a0, 0x210a940, 0xc000998000, 0xc0005aaf80, 0xc000a7e7d0, 0xc0009822a0, 0x267fd00, 0xc0009825a0, 0x0)
        /go/src/github.com/argoproj/argo-cd/util/grpc/useragent.go:22 +0xa2
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x267fd00, 0xc0009825a0, 0x210a940, 0xc000998000, 0x0, 0x0, 0x263de00, 0xc0005f20c0)
        /go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.1-0.20190118093823-f849b5445de4/chain.go:34 +0x9c
github.com/grpc-ecosystem/go-grpc-middleware/auth.UnaryServerInterceptor.func1(0x267fd00, 0xc0009822a0, 0x210a940, 0xc000998000, 0xc0005aaf80, 0xc000a7e7d0, 0xc000982360, 0x3, 0x3, 0x7fd8c3ebcc48)
        /go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.1-0.20190118093823-f849b5445de4/auth/auth.go:46 +0x108
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x267fd00, 0xc0009822a0, 0x210a940, 0xc000998000, 0x26, 0xc000a7e820, 0x0, 0x0)
        /go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.1-0.20190118093823-f849b5445de4/chain.go:34 +0x9c
github.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).UnaryServerInterceptor.func1(0x267fd00, 0xc0009822a0, 0x210a940, 0xc000998000, 0xc0005aaf80, 0xc000a7e7d0, 0x0, 0x0, 0x0, 0x0)
        /go/pkg/mod/github.com/grpc-ecosystem/go-grpc-prometheus@v1.2.0/server_metrics.go:107 +0xad
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x267fd00, 0xc0009822a0, 0x210a940, 0xc000998000, 0x26, 0xbfee7b46f48286b7, 0x69f7553dc, 0x3a41be0)
        /go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.1-0.20190118093823-f849b5445de4/chain.go:34 +0x9c
github.com/grpc-ecosystem/go-grpc-middleware/logging/logrus.UnaryServerInterceptor.func1(0x267fd00, 0xc000982180, 0x210a940, 0xc000998000, 0xc0005aaf80, 0xc000a7e7d0, 0x50, 0x48, 0x20b10c0, 0x0)
        /go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.1-0.20190118093823-f849b5445de4/logging/logrus/server_interceptors.go:32 +0x110
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x267fd00, 0xc000982180, 0x210a940, 0xc000998000, 0x7fd8eab7dc28, 0x0, 0xc000d019f8, 0x40c4b6)
        /go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.1-0.20190118093823-f849b5445de4/chain.go:34 +0x9c
github.com/argoproj/argo-cd/server.bug21955WorkaroundInterceptor(0x267fd00, 0xc000982180, 0x210a940, 0xc000998000, 0xc0005aaf80, 0xc000a7e7d0, 0xc000982180, 0xc0005aaf40, 0xc000d01a28, 0x40cd28)
        /go/src/github.com/argoproj/argo-cd/server/server.go:1014 +0x15b
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1(0x267fd00, 0xc000982180, 0x210a940, 0xc000998000, 0xc0005aaf80, 0xc0005aafc0, 0xc000b62a98, 0x4f5cb8, 0x207ad20, 0xc000982180)
        /go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.1-0.20190118093823-f849b5445de4/chain.go:39 +0x155
github.com/argoproj/argo-cd/pkg/apiclient/application._ApplicationService_Create_Handler(0x219c2e0, 0xc00049e160, 0x267fd00, 0xc000982180, 0xc000350bd0, 0xc000b16630, 0x267fd00, 0xc000982180, 0x36, 0x1b)
        /go/src/github.com/argoproj/argo-cd/pkg/apiclient/application/application.pb.go:2591 +0x14b
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000703800, 0x269f500, 0xc000cc0f00, 0xc000144500, 0xc000b16a20, 0x3a20dd0, 0x0, 0x0, 0x0)
        /go/pkg/mod/google.golang.org/grpc@v1.15.0/server.go:982 +0x4bd
google.golang.org/grpc.(*Server).handleStream(0xc000703800, 0x269f500, 0xc000cc0f00, 0xc000144500, 0x0)
        /go/pkg/mod/google.golang.org/grpc@v1.15.0/server.go:1208 +0x11f0
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc00111e0f0, 0xc000703800, 0x269f500, 0xc000cc0f00, 0xc000144500)
        /go/pkg/mod/google.golang.org/grpc@v1.15.0/server.go:686 +0xa1
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /go/pkg/mod/google.golang.org/grpc@v1.15.0/server.go:684 +0xa1
runtime: note: your Linux kernel may be buggy
runtime: note: see https://golang.org/wiki/LinuxKernelSignalVectorBug
runtime: note: mlock workaround for kernel bug failed with errno 12
```

Kubernetes cluster: 1.20.0
Linux version: Linux nuc01 5.4.0-58-generic #64-Ubuntu SMP Wed Dec 9 08:16:25 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

ArgoCD helm chart version: 2.11.0

**Comment by kfirfer** [comment]
Found the issue
Its happens when I deploy helm chart with: "logFormat: json"

**Comment by jannfis** [comment]
Probably related to #4911

**Comment by jannfis** [comment]
Which Argo CD version are you experiencing this with?

**Comment by kfirfer** [comment]
@jannfis Version v1.7.6

**Comment by kfirfer** [comment]
@jannfis 
I tested with 1.8.1 and its not reproduce
If its happens again, I will reopen this issue
Closeing

**Comment by seuf** [comment]
Hi, I have the same issue with Argocd v1.8.1 :
```
Failed to obtain reader, failed to marshal fields to JSON, json: error calling MarshalJSON for type *grpc.jsonpbMarshalleble: invalid character '\x03' looking for beginning of value
```
sometimes the character is different (`\a`, `\b`, `\t`, `\x00`, etc..)
