### ISSUE TITLE
Creation of AppProject via API fails due to nil dereference 

### ISSUE THREAD

**Issue by zonnie** [argoproj/argo-cd#5249]
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

Trying to create a project programmatically using ArgoCD's golang structs fails due to nil dereference
The `argocd-server` returns 500

**To Reproduce**

Use the following Go function to create an `AppProject` 
```
func generateProject(name string) *v1alpha1.AppProject{
	logrus.Infof("Generating project '%s'", name)
	finalizers := []string{"resources-finalizer.argocd.argoproj.io"}
	project := &v1alpha1.AppProject{
		TypeMeta:   metav1.TypeMeta{
			Kind:       "AppProject",
			APIVersion: "argoproj.io/v1alpha1",
		},
		ObjectMeta: metav1.ObjectMeta{
			Name:                       "test-project",
			Namespace:                  "argocd",
			Finalizers:                 finalizers,
		},
		Spec:       v1alpha1.AppProjectSpec{
			SourceRepos:                []string{"*"},
			Destinations:               []v1alpha1.ApplicationDestination{{Namespace: "*", Server: "*"}},
			Description:                fmt.Sprintf("Application project for customer '%s'", name),
			ClusterResourceWhitelist:   []metav1.GroupKind{{Group: "*", Kind:  "*"}},
		},
	}

	return project
}
```

Then using `resty` run
```
	resp, err := client.R().
		EnableTrace().
		SetHeader("Authorization", fmt.Sprintf("Bearer %s", token)).
		SetBody(proj).
		Post(fmt.Sprintf("%s/api/v1/projects", c.ServerInfo.ServerURL))
```

- The `token` passed above is OK as it works for other API calls
- `c.ServerInfo.ServerURL` is my ArgoCD server's API address

The server returns `500` error response and `argocd-server` as an error (attached in the logs section)

**Expected behavior**

- Project will be created 
- Server will respond with 200 OK

**Screenshots**

**Version**

```shell
argocd: v1.7.10+bcb05b0.dirty
  BuildDate: 2020-11-21T00:34:29Z
  GitCommit: bcb05b0c2e0f8006aa2d2abaf780e73c9e73c945
  GitTreeState: dirty
  GoVersion: go1.15.5
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.8.1+c2547dc
  BuildDate: 2020-12-10T02:59:21Z
  GitCommit: c2547dca95437fdbb4d1e984b0592e6b9110d37f
  GitTreeState: clean
  GoVersion: go1.14.12
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v3.8.1 2020-07-16T00:58:46Z
  Helm Version: v3.4.1+gc4e7485
  Kubectl Version: v1.17.8
```

**Logs**

Logs from the `argocd-server` on the above request

```
time="2021-01-14T13:03:53Z" level=info msg="Issuing claims: { 0  1610629433 argocd 1610629433 admin}"
time="2021-01-14T13:03:53Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=Create grpc.service=session.SessionService grpc.start_time="2021-01-14T13:03:52Z" grpc.time_ms=643.893 span.kind=server system=grpc
time="2021-01-14T13:03:53Z" level=info msg="received unary call /project.ProjectService/Create" grpc.method=Create grpc.request.claims="{\"iat\":1610629433,\"iss\":\"argocd\",\"nbf\":1610629433,\"sub\":\"admin\"}" grpc.request.content= grpc.service=project.ProjectService grpc.start_time="2021-01-14T13:03:53Z" span.kind=server system=grpc
time="2021-01-14T13:03:53Z" level=error msg="Recovered from panic: runtime error: invalid memory address or nil pointer dereference
goroutine 8339 [running]:
runtime/debug.Stack(0xc000a94e10, 0x2140f80, 0x3e50910)
\t/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
github.com/argoproj/argo-cd/util/grpc.PanicLoggerUnaryServerInterceptor.func1.1(0xc00052b260, 0xc000a95238)
\t/go/src/github.com/argoproj/argo-cd/util/grpc/grpc.go:24 +0x6e
panic(0x2140f80, 0x3e50910)
\t/usr/local/go/src/runtime/panic.go:969 +0x166
github.com/argoproj/argo-cd/server/project.(*Server).Create(0xc000955480, 0x29442a0, 0xc00097a390, 0xc000ca5d40, 0xc000955480, 0x2499395, 0x14)
\t/go/src/github.com/argoproj/argo-cd/server/project/project.go:182 +0x86
github.com/argoproj/argo-cd/pkg/apiclient/project._ProjectService_Create_Handler.func1(0x29442a0, 0xc00097a390, 0x23509c0, 0xc000ca5d40, 0x0, 0x0, 0x0, 0x0)
\t/go/src/github.com/argoproj/argo-cd/pkg/apiclient/project/project.pb.go:888 +0x86
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x29442a0, 0xc00097a390, 0x23509c0, 0xc000ca5d40, 0x0, 0x0, 0x0, 0x0)
\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.1-0.20190118093823-f849b5445de4/chain.go:31 +0x114
github.com/argoproj/argo-cd/util/grpc.PanicLoggerUnaryServerInterceptor.func1(0x29442a0, 0xc00097a390, 0x23509c0, 0xc000ca5d40, 0xc000d69900, 0xc0000948c0, 0x0, 0x0, 0x0, 0x0)
\t/go/src/github.com/argoproj/argo-cd/util/grpc/grpc.go:28 +0xa7
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x29442a0, 0xc00097a390, 0x23509c0, 0xc000ca5d40, 0x0, 0x0, 0x207cfa0, 0xc000b87940)
\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.1-0.20190118093823-f849b5445de4/chain.go:34 +0x9c
github.com/argoproj/argo-cd/util/grpc.ErrorCodeUnaryServerInterceptor.func1(0x29442a0, 0xc00097a390, 0x23509c0, 0xc000ca5d40, 0xc000d69900, 0xc0000948c0, 0x0, 0x0, 0x0, 0x0)
\t/go/src/github.com/argoproj/argo-cd/util/grpc/errors.go:64 +0x55
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x29442a0, 0xc00097a390, 0x23509c0, 0xc000ca5d40, 0xc000ca5d40, 0x29442a0, 0xc00097a390, 0x1)
\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.1-0.20190118093823-f849b5445de4/chain.go:34 +0x9c
github.com/argoproj/argo-cd/util/grpc.PayloadUnaryServerInterceptor.func1(0x29442a0, 0xc00097a390, 0x23509c0, 0xc000ca5d40, 0xc000d69900, 0xc0000948c0, 0x248ae18, 0xc0008cc6c0, 0xc0008cc6c0, 0x207cfa0)
\t/go/src/github.com/argoproj/argo-cd/util/grpc/logging.go:76 +0x1d3
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x29442a0, 0xc00097a390, 0x23509c0, 0xc000ca5d40, 0x222bdc0, 0xc00000f158, 0x29442a0, 0xc00097a390)
\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.1-0.20190118093823-f849b5445de4/chain.go:34 +0x9c
github.com/argoproj/argo-cd/util/grpc.UserAgentUnaryServerInterceptor.func1(0x29442a0, 0xc00097a390, 0x23509c0, 0xc000ca5d40, 0xc000d69900, 0xc0000948c0, 0xc000ca5e30, 0x29442a0, 0xc00097a390, 0x0)
\t/go/src/github.com/argoproj/argo-cd/util/grpc/useragent.go:22 +0xa2
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x29442a0, 0xc00097a390, 0x23509c0, 0xc000ca5d40, 0x0, 0x0, 0x28fde20, 0xc0007beea0)
\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.1-0.20190118093823-f849b5445de4/chain.go:34 +0x9c
github.com/grpc-ecosystem/go-grpc-middleware/auth.UnaryServerInterceptor.func1(0x29442a0, 0xc000ca5e30, 0x23509c0, 0xc000ca5d40, 0xc000d69900, 0xc0000948c0, 0xc000ca5e90, 0x3, 0x3, 0x7f6b290c5310)
\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.1-0.20190118093823-f849b5445de4/auth/auth.go:46 +0x108
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x29442a0, 0xc000ca5e30, 0x23509c0, 0xc000ca5d40, 0x1e, 0xc0000949b0, 0x0, 0x0)
\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.1-0.20190118093823-f849b5445de4/chain.go:34 +0x9c
github.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).UnaryServerInterceptor.func1(0x29442a0, 0xc000ca5e30, 0x23509c0, 0xc000ca5d40, 0xc000d69900, 0xc0000948c0, 0x0, 0x0, 0x0, 0x0)
\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-prometheus@v1.2.0/server_metrics.go:107 +0xad
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x29442a0, 0xc000ca5e30, 0x23509c0, 0xc000ca5d40, 0x1e, 0xbff82e2e6e1df08c, 0xa4a6f789bcf, 0x3e89500)
\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.1-0.20190118093823-f849b5445de4/chain.go:34 +0x9c
github.com/grpc-ecosystem/go-grpc-middleware/logging/logrus.UnaryServerInterceptor.func1(0x29442a0, 0xc000ca5d10, 0x23509c0, 0xc000ca5d40, 0xc000d69900, 0xc0000948c0, 0x50, 0x48, 0x22ffb00, 0x0)
\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.1-0.20190118093823-f849b5445de4/logging/logrus/server_interceptors.go:32 +0x110
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x29442a0, 0xc000ca5d10, 0x23509c0, 0xc000ca5d40, 0x7f6b4fd827d0, 0x0, 0xc000b079f8, 0x40c546)
\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.1-0.20190118093823-f849b5445de4/chain.go:34 +0x9c
github.com/argoproj/argo-cd/server.bug21955WorkaroundInterceptor(0x29442a0, 0xc000ca5d10, 0x23509c0, 0xc000ca5d40, 0xc000d69900, 0xc0000948c0, 0xc000ca5d10, 0xc000d698e0, 0xc000b07a28, 0x40cdb8)
\t/go/src/github.com/argoproj/argo-cd/server/server.go:1022 +0x15b
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1(0x29442a0, 0xc000ca5d10, 0x23509c0, 0xc000ca5d40, 0xc000d69900, 0xc000d69920, 0xc000b07a98, 0x495778, 0x22c7d20, 0xc000ca5d10)
\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.1-0.20190118093823-f849b5445de4/chain.go:39 +0x155
github.com/argoproj/argo-cd/pkg/apiclient/project._ProjectService_Create_Handler(0x2305c80, 0xc000955480, 0x29442a0, 0xc000ca5d10, 0xc000510cb0, 0xc0006cfcb0, 0x29442a0, 0xc000ca5d10, 0xc00111e928, 0xc000b07b30)
\t/go/src/github.com/argoproj/argo-cd/pkg/apiclient/project/project.pb.go:890 +0x14b
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000c4ef00, 0x2965fc0, 0xc000bf6a80, 0xc0018eb300, 0xc0005f8d20, 0x3e65710, 0x0, 0x0, 0x0)
\t/go/pkg/mod/google.golang.org/grpc@v1.15.0/server.go:982 +0x4bd
google.golang.org/grpc.(*Server).handleStream(0xc000c4ef00, 0x2965fc0, 0xc000bf6a80, 0xc0018eb300, 0x0)
\t/go/pkg/mod/google.golang.org/grpc@v1.15.0/server.go:1208 +0x11f3
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000ddb7b0, 0xc000c4ef00, 0x2965fc0, 0xc000bf6a80, 0xc0018eb300)
\t/go/pkg/mod/google.golang.org/grpc@v1.15.0/server.go:686 +0xa1
created by google.golang.org/grpc.(*Server).serveStreams.func1
\t/go/pkg/mod/google.golang.org/grpc@v1.15.0/server.go:684 +0xa1
time="2021-01-14T13:03:53Z" level=error msg="finished unary call with code Internal" error="rpc error: code = Internal desc = runtime error: invalid memory address or nil pointer dereference" grpc.code=Internal grpc.method=Create grpc.service=project.ProjectService grpc.start_time="2021-01-14T13:03:53Z" grpc.time_ms=2.38 span.kind=server system=grpc
```

**Comment by zonnie** [comment]
@jessesuen - You labeled this as a `workaround` - am I missing it ? what's the workaround ?
Also, the dup issue was an issue with GitHub, the initial issue was stuck on creation so I somehow created 2 - sorry about that. 😄

**Comment by alexmt** [comment]
Hello @zonnie , 

AppProject API expects project in `project` field. So payload should look like 👍 

```
{
  "project": {
     "metadata": {
       "name": "my-project"
     },
     "spec": {
    ...
     }
   }
}
```

The nil dereference error is a bug of course. API server should return a meaningful error.

Also API is inconsistent with other APIs. We should check if we can make it consistent without breaking backward compatibility.

**Comment by zonnie** [comment]
@alexmt How does it translate to Go code? What am I missing in my structs ?

**Comment by alexmt** [comment]
I think you can change your code as follows:

```golang
	resp, err := client.R().
		EnableTrace().
		SetHeader("Authorization", fmt.Sprintf("Bearer %s", token)).
		SetBody(map[string]interface{} {
			"project": proj,
		}).
		Post(fmt.Sprintf("%s/api/v1/projects", c.ServerInfo.ServerURL))
```

**Comment by zonnie** [comment]
@alexmt - Thanks !
Expanding on your answer if anyone else wants something cleaner
```
// This is required due to https://github.com/argoproj/argo-cd/issues/5249
type ArgoCDProject struct {
	Project v1alpha1.AppProject `json:"project"`
}
```
Workaround confirmed to work - thanks guys !
