### ISSUE TITLE
TypeError: Cannot read property 'Version' of null after reinstalling ArgoCD

### ISSUE THREAD

**Issue by aisrael** [argoproj/argo-cd#5652]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

After completely uninstalling and reinstalling ArgoCD, attempting to open the dashboard gives the following error:

```
TypeError: Cannot read property 'Version' of null
    at Object.children (https://argocd.ops.ada-dev2.support/main.d714f4605e74ef974014.js:33:565916)
    at t.render (https://argocd.ops.ada-dev2.support/main.d714f4605e74ef974014.js:33:189374)
    at Mi (https://argocd.ops.ada-dev2.support/main.d714f4605e74ef974014.js:354:63114)
    at ki (https://argocd.ops.ada-dev2.support/main.d714f4605e74ef974014.js:354:62909)
    at Li (https://argocd.ops.ada-dev2.support/main.d714f4605e74ef974014.js:354:66744)
    at Ha (https://argocd.ops.ada-dev2.support/main.d714f4605e74ef974014.js:354:90569)
    at Ba (https://argocd.ops.ada-dev2.support/main.d714f4605e74ef974014.js:354:90953)
    at Ms (https://argocd.ops.ada-dev2.support/main.d714f4605e74ef974014.js:354:97976)
    at Ss (https://argocd.ops.ada-dev2.support/main.d714f4605e74ef974014.js:354:97356)
    at vs (https://argocd.ops.ada-dev2.support/main.d714f4605e74ef974014.js:354:96377)
```

**To Reproduce**

1. Install ArgoCD using the Helm chart (2.14.7), log in to dashboard and using `argocd` CLI
2. Uninstall ArgoCD using helm, and manually deleted all leftover Kubernetes resources
3. Install ArgoCD using the same Helm chart and `values.yaml`
4. Verify that you can login and change password using `argocd` CLI
5. Visit the dashboard, get error

I even attempted to clear all cookies for the site, then any site LocalStorage I could find.

I also tried closing and reopening Chrome.

Surprisingly enough, opening the site in incognito mode showed me the login page.

**Expected behavior**

Should show login/landing page

**Screenshots**

<img width="1792" alt="Screen Shot 2021-03-02 at 6 00 52 PM" src="https://user-images.githubusercontent.com/89215/109631790-472c1100-7b81-11eb-8fd2-e5f206607291.png">

**Version**

- Chrome Version 88.0.4324.192 (Official Build) (x86_64)

```shell
argocd: v1.8.4+28aea3d
  BuildDate: 2021-02-05T17:57:16Z
  GitCommit: 28aea3dfdede00443b52cc584814d80e8f896200
  GitTreeState: clean
  GoVersion: go1.14.12
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.8.4+28aea3d
  BuildDate: 2021-02-05T17:56:06Z
  GitCommit: 28aea3dfdede00443b52cc584814d80e8f896200
  GitTreeState: clean
  GoVersion: go1.14.12
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v3.8.1 2020-07-16T00:58:46Z
  Helm Version: v3.4.1+gc4e7485
  Kubectl Version: v1.17.8
  Jsonnet Version: v0.17.0
```

**Logs**

```
app.tsx:121 Uncaught (in promise) TypeError: Cannot read property 'googleAnalytics' of null
    at t.<anonymous> (app.tsx:121)
    at main.d714f4605e74ef974014.js:33
    at Object.next (main.d714f4605e74ef974014.js:33)
    at a (main.d714f4605e74ef974014.js:33)
(anonymous) @ app.tsx:121
(anonymous) @ main.d714f4605e74ef974014.js:33
(anonymous) @ main.d714f4605e74ef974014.js:33
a @ main.d714f4605e74ef974014.js:33
Promise.then (async)
c @ main.d714f4605e74ef974014.js:33
(anonymous) @ main.d714f4605e74ef974014.js:33
$l @ main.d714f4605e74ef974014.js:33
t.componentDidMount @ main.d714f4605e74ef974014.js:33
Pa @ react-dom.production.min.js:216
Ia @ react-dom.production.min.js:220
(anonymous) @ react-dom.production.min.js:250
t.unstable_runWithPriority @ scheduler.production.min.js:18
Ts @ react-dom.production.min.js:250
Ms @ react-dom.production.min.js:249
Ss @ react-dom.production.min.js:248
vs @ react-dom.production.min.js:245
Ga @ react-dom.production.min.js:243
Os @ react-dom.production.min.js:253
Ns @ react-dom.production.min.js:253
Is.render @ react-dom.production.min.js:261
(anonymous) @ react-dom.production.min.js:264
Ls @ react-dom.production.min.js:251
Hs @ react-dom.production.min.js:264
render @ react-dom.production.min.js:266
(anonymous) @ index.tsx:5
(anonymous) @ main.d714f4605e74ef974014.js:338
o @ bootstrap:63
(anonymous) @ bootstrap:198
(anonymous) @ main.d714f4605e74ef974014.js:1
clusters-service.ts:9 Uncaught (in promise) TypeError: Cannot read property 'items' of null
    at clusters-service.ts:9
(anonymous) @ clusters-service.ts:9
Promise.then (async)
e.list @ clusters-service.ts:9
(anonymous) @ applications-list.tsx:164
useMemo @ react-dom.production.min.js:159
useMemo @ react.production.min.js:23
gc @ applications-list.tsx:164
Go @ react-dom.production.min.js:150
Li @ react-dom.production.min.js:178
Ha @ react-dom.production.min.js:232
Ba @ react-dom.production.min.js:233
Ms @ react-dom.production.min.js:249
Ss @ react-dom.production.min.js:248
vs @ react-dom.production.min.js:245
Ga @ react-dom.production.min.js:243
Os @ react-dom.production.min.js:253
Ns @ react-dom.production.min.js:253
Is.render @ react-dom.production.min.js:261
(anonymous) @ react-dom.production.min.js:264
Ls @ react-dom.production.min.js:251
Hs @ react-dom.production.min.js:264
render @ react-dom.production.min.js:266
(anonymous) @ index.tsx:5
(anonymous) @ main.d714f4605e74ef974014.js:338
o @ bootstrap:63
(anonymous) @ bootstrap:198
(anonymous) @ main.d714f4605e74ef974014.js:1
page.tsx:11 Uncaught (in promise) TypeError: Cannot read property 'loggedIn' of null
    at page.tsx:11
(anonymous) @ page.tsx:11
Promise.then (async)
load @ page.tsx:11
(anonymous) @ data-loader.tsx:82
(anonymous) @ main.d714f4605e74ef974014.js:33
(anonymous) @ main.d714f4605e74ef974014.js:33
(anonymous) @ main.d714f4605e74ef974014.js:33
Dt @ main.d714f4605e74ef974014.js:33
t.loadData @ main.d714f4605e74ef974014.js:33
t.componentDidMount @ data-loader.tsx:47
Pa @ react-dom.production.min.js:216
Ia @ react-dom.production.min.js:220
(anonymous) @ react-dom.production.min.js:250
t.unstable_runWithPriority @ scheduler.production.min.js:18
Ts @ react-dom.production.min.js:250
Ms @ react-dom.production.min.js:249
Ss @ react-dom.production.min.js:248
vs @ react-dom.production.min.js:245
Ga @ react-dom.production.min.js:243
Os @ react-dom.production.min.js:253
Ns @ react-dom.production.min.js:253
Is.render @ react-dom.production.min.js:261
(anonymous) @ react-dom.production.min.js:264
Ls @ react-dom.production.min.js:251
Hs @ react-dom.production.min.js:264
render @ react-dom.production.min.js:266
(anonymous) @ index.tsx:5
(anonymous) @ main.d714f4605e74ef974014.js:338
o @ bootstrap:63
(anonymous) @ bootstrap:198
(anonymous) @ main.d714f4605e74ef974014.js:1
DevTools failed to load SourceMap: Could not load content for https://argocd.ops.ada-dev2.support/ReactToastify.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

**Comment by aisrael** [comment]
After attempting to close and reopen Chrome again, Chrome complained that it could not restore windows.

I then also instructed Chrome to Clear browsing data for the last hour.

I was then able to visit the site and use the dashboard without any issues.
