### ISSUE TITLE
SIGSEGV in kube.GetResourcesWithLabel

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#587]
Noticed that an application controller had exited with the following error:
```
time="2018-08-21T20:02:20Z" level=info msg="cache miss: apires|https://CLUSTER-URL-REDACTED"
time="2018-08-21T20:02:20Z" level=warning msg="Failed to watch app resources on https://CLUSTER-URL-REDACTED: Get https://CLUSTER-URL-REDACTED/api: dial tcp: lookup CLUSTER-URL-REDACTED on 100.64.0.10:53: no such host, retrying in 10s"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x45676c]

goroutine 7342065 [running]:
github.com/argoproj/argo-cd/util/kube.GetResourcesWithLabel.func1(0xc4213abe80, 0x1a57840, 0xc42106fcb0, 0x1572e47, 0x21, 0xc420dcb670, 0xe, 0xc4211174d0, 0xc420c53700)
        /root/go/src/github.com/argoproj/argo-cd/util/kube/kube.go:331 +0x3a3
created by github.com/argoproj/argo-cd/util/kube.GetResourcesWithLabel
        /root/go/src/github.com/argoproj/argo-cd/util/kube/kube.go:316 +0x695
```

**Comment by jessesuen** [comment]
This was on v0.7.1. The issue is with concurrent appends to a list:

```
	var result []*unstructured.Unstructured

	var wg sync.WaitGroup
	wg.Add(len(resourceInterfaces))
	for i := range resourceInterfaces {
		client := resourceInterfaces[i]
		go func() {
			defer wg.Done()
			list, err := client.List(metav1.ListOptions{
				LabelSelector: fmt.Sprintf("%s=%s", labelName, labelValue),
			})
			if err != nil {
				asyncErr = err
				return
			}
			// apply client side filtering since not every kubernetes API supports label filtering
			for i := range list.(*unstructured.UnstructuredList).Items {
				item := list.(*unstructured.UnstructuredList).Items[i]
				labels := item.GetLabels()
				if labels != nil {
					if value, ok := labels[labelName]; ok && value == labelValue {
						result = append(result, &item)            <<<<< this append is not thread safe
					}
				}
			}
		}()
	}
```
