### ISSUE TITLE
TypeError: Cannot read property 'kind' of null

### ISSUE THREAD

**Issue by jsoref** [argoproj/argo-cd#5923]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

While a right sidepanel is open if the reason it's open goes away, the page refreshes to a static dead stack trace

**To Reproduce**

1. Open the tab=events for a CertificateRequest that's about to be deleted
2. Wait for it to be deleted

**Expected behavior**

If necessary, just dismiss the panel.
Preferably, don't dismiss the panel, just tell me the object is gone and let me dismiss it myself.

**Screenshots**

![image](https://user-images.githubusercontent.com/2119212/113049798-133d0f00-9172-11eb-8e52-5a92b7e55cb5.png)

**Version**

```shell
{
    "Version": "v1.9.0+1b7441d",
    "BuildDate": "2021-03-11T20:01:21Z",
    "GitCommit": "1b7441d62bd9752fa07b2a22515a90bc7109267b",
    "GitTreeState": "clean",
    "GoVersion": "go1.16",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KsonnetVersion": "v0.13.1",
    "KustomizeVersion": "v3.9.4 2021-02-09T19:22:10Z",
    "HelmVersion": "v3.5.1+g32c2223",
    "KubectlVersion": "v0.20.1",
    "JsonnetVersion": "v0.17.0"
}
```

**Logs**

```
Something went wrong!

Consider submitting an issue here.


Stacktrace:

TypeError: Cannot read property 'kind' of null
    at t.getResourceTabs (https://argocd.example.com/main.dbdefe7ed06b557ffc32.js:33:414351)
    at Object.children (https://argocd.example.com/main.dbdefe7ed06b557ffc32.js:33:402418)
    at t.render (https://argocd.example.com/main.dbdefe7ed06b557ffc32.js:33:181715)
    at Ha (https://argocd.example.com/main.dbdefe7ed06b557ffc32.js:354:70056)
    at Ra (https://argocd.example.com/main.dbdefe7ed06b557ffc32.js:354:69851)
    at gs (https://argocd.example.com/main.dbdefe7ed06b557ffc32.js:354:105644)
    at fc (https://argocd.example.com/main.dbdefe7ed06b557ffc32.js:354:96894)
    at lc (https://argocd.example.com/main.dbdefe7ed06b557ffc32.js:354:96819)
    at tc (https://argocd.example.com/main.dbdefe7ed06b557ffc32.js:354:93852)
    at https://argocd.example.com/main.dbdefe7ed06b557ffc32.js:354:45525
```

**Comment by rbreeze** [comment]
Are you able to check if this still happens on 2.0?

**Comment by jsoref** [comment]
We're not terribly behind 2.0, I suspect we can update this week or next. We do periodically.
