### ISSUE TITLE
Custom resource actions cannot add new elements to arrays

### ISSUE THREAD

**Issue by msessa** [argoproj/argo-cd#6248]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When defining a custom LUA resource action that alters the object by adding an item to an array, the action fails with the following error:
```
Unable to execute resource action: runtime error: index out of range [2] with length 2
```

**To Reproduce**

Define a resource action such as:
```yaml
  resource.customizations: |
    apps/Deployment:
      actions: |
        discovery.lua: |
          actions = {}
          actions["test"] = {["disabled"] = false}
          return actions
        definitions:
          - name: test
            action.lua: |
              table.insert(obj.spec.template.spec.containers[1].env, {["name"] = "ENVNAME", ["value"] = "ENVVALUE" })
              return obj
```

**Expected behavior**

Deployment should me modified with the additional environment variable

**Version**

```shell
argocd: v2.0.1+33eaf11.dirty
  BuildDate: 2021-04-21T18:44:28Z
  GitCommit: 33eaf11e3abd8c761c726e815cbb4b6af7dcb030
  GitTreeState: dirty
  GoVersion: go1.16.3
  Compiler: gc
  Platform: darwin/amd64
time="2021-05-17T09:05:48Z" level=info msg="received unary call /version.VersionService/Version" grpc.method=Version grpc.request.claims="{\"exp\":1621318998,\"iat\":1621232598,\"iss\":\"argocd\",\"jti\":\"b95b3d6c-56cc-4c5d-8cae-36201d8289f0\",\"nbf\":1621232598,\"sub\":\"admin\"}" grpc.request.content= grpc.service=version.VersionService grpc.start_time="2021-05-17T09:05:48Z" span.kind=server system=grpc
time="2021-05-17T09:05:48Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=Version grpc.service=version.VersionService grpc.start_time="2021-05-17T09:05:48Z" grpc.time_ms=0.26 span.kind=server system=grpc
argocd-server: v2.0.1+33eaf11
  BuildDate: 2021-04-15T22:31:51Z
  GitCommit: 33eaf11e3abd8c761c726e815cbb4b6af7dcb030
  GitTreeState: clean
  GoVersion: go1.16
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v3.9.4 2021-02-09T19:22:10Z
  Helm Version: v3.5.1+g32c2223
  Kubectl Version: v0.20.4
  Jsonnet Version: v0.17.0
```

**Logs**

```
time="2021-05-17T09:01:31Z" level=error msg="Recovered from panic: runtime error: index out of range [2] with length 2\ngoroutine 4782 [running]:\nruntime/debug.Stack(0xc0016206f8, 0x27299c0, 0xc001230510)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x9f\ngithub.com/argoproj/argo-cd/v2/util/grpc.PanicLoggerUnaryServerInterceptor.func1.1(0xc00049dab0, 0xc001621250)\n\t/go/src/github.com/argoproj/argo-cd/util/grpc/grpc.go:24 +0x76\npanic(0x27299c0, 0xc001230510)\n\t/usr/local/go/src/runtime/panic.go:965 +0x1b9\ngithub.com/argoproj/argo-cd/v2/util/lua.cleanReturnedArray(0xc000e5f240, 0x3, 0x4, 0xc000be1e60, 0x2, 0x2, 0x700000000000001, 0xffffffffffffffff, 0x0)\n\t/go/src/github.com/argoproj/argo-cd/util/lua/lua.go:201 +0x2c8\ngithub.com/argoproj/argo-cd/v2/util/lua.cleanReturnedObj(0xc000a43500, 0xc000710150, 0xc000f5304c)\n\t/go/src/github.com/argoproj/argo-cd/util/lua/lua.go:185 +0x34a\ngithub.com/argoproj/argo-cd/v2/util/lua.cleanReturnedObj(0xc000a43470, 0xc000e17440, 0xc000f52fc0)\n\t/go/src/github.com/argoproj/argo-cd/util/lua/lua.go:174 +0x19c\ngithub.com/argoproj/argo-cd/v2/util/lua.cleanReturnedObj(0xc000a432f0, 0xc000e160f0, 0xc000f535f0)\n\t/go/src/github.com/argoproj/argo-cd/util/lua/lua.go:174 +0x19c\ngithub.com/argoproj/argo-cd/v2/util/lua.cleanReturnedObj(0xc00132fe60, 0xc0017a3590, 0xc00011a2f8)\n\t/go/src/github.com/argoproj/argo-cd/util/lua/lua.go:174 +0x19c\ngithub.com/argoproj/argo-cd/v2/util/lua.VM.ExecuteResourceAction(0xc00110e540, 0xc00110e500, 0xc00011a270, 0xc001334e70, 0xa9, 0xc002527728, 0x14, 0xc001334e70)\n\t/go/src/github.com/argoproj/argo-cd/util/lua/lua.go:153 +0x1dd\ngithub.com/argoproj/argo-cd/v2/server/application.(*Server).RunResourceAction(0xc0006e3d40, 0x2d703b8, 0xc001970300, 0xc000d58b40, 0xc0006e3d40, 0x290dcc8, 0x14)\n\t/go/src/github.com/argoproj/argo-cd/server/application/application.go:1603 +0x49c\ngithub.com/argoproj/argo-cd/v2/pkg/apiclient/application._ApplicationService_RunResourceAction_Handler.func1(0x2d703b8, 0xc001970300, 0x2808b00, 0xc000d58b40, 0x0, 0x0, 0x0, 0x0)\n\t/go/src/github.com/argoproj/argo-cd/pkg/apiclient/application/application.pb.go:3131 +0x8b\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x2d703b8, 0xc001970300, 0x2808b00, 0xc000d58b40, 0x0, 0x0, 0x0, 0x0)\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.1-0.20190118093823-f849b5445de4/chain.go:31 +0x114\ngithub.com/argoproj/argo-cd/v2/util/grpc.PanicLoggerUnaryServerInterceptor.func1(0x2d703b8, 0xc001970300, 0x2808b00, 0xc000d58b40, 0xc000fcca80, 0xc000f4af00, 0x0, 0x0, 0x0, 0x0)\n\t/go/src/github.com/argoproj/argo-cd/util/grpc/grpc.go:28 +0xa7\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x2d703b8, 0xc001970300, 0x2808b00, 0xc000d58b40, 0x0, 0x0, 0x24b74a0, 0xc00170cdd0)\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.1-0.20190118093823-f849b5445de4/chain.go:34 +0x9c\ngithub.com/argoproj/argo-cd/v2/util/grpc.ErrorCodeUnaryServerInterceptor.func1(0x2d703b8, 0xc001970300, 0x2808b00, 0xc000d58b40, 0xc000fcca80, 0xc000f4af00, 0x0, 0x0, 0x0, 0x0)\n\t/go/src/github.com/argoproj/argo-cd/util/grpc/errors.go:64 +0x55\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x2d703b8, 0xc001970300, 0x2808b00, 0xc000d58b40, 0xc000d58b40, 0x2d703b8, 0xc001970300, 0x1)\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.1-0.20190118093823-f849b5445de4/chain.go:34 +0x9c\ngithub.com/argoproj/argo-cd/v2/util/grpc.PayloadUnaryServerInterceptor.func1(0x2d703b8, 0xc001970300, 0x2808b00, 0xc000d58b40, 0xc000fcca80, 0xc000f4af00, 0x28fd74c, 0xc000fccc20, 0xc000fccc00, 0xc000acb401)\n\t/go/src/github.com/argoproj/argo-cd/util/grpc/logging.go:80 +0x1e2\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x2d703b8, 0xc001970300, 0x2808b00, 0xc000d58b40, 0x2164fbe5131d1225, 0x748d5319d5154038, 0x40a4bf, 0xc00003a000)\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.1-0.20190118093823-f849b5445de4/chain.go:34 +0x9c\ngithub.com/argoproj/argo-cd/v2/util/grpc.UserAgentUnaryServerInterceptor.func1(0x2d703b8, 0xc001970300, 0x2808b00, 0xc000d58b40, 0xc000fcca80, 0xc000f4af00, 0xc0019afc50, 0x2d703b8, 0xc001970300, 0x0)\n\t/go/src/github.com/argoproj/argo-cd/util/grpc/useragent.go:22 +0xa5\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x2d703b8, 0xc001970300, 0x2808b00, 0xc000d58b40, 0x0, 0x0, 0xc000ebb7a0, 0x7f841d4e4598)\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.1-0.20190118093823-f849b5445de4/chain.go:34 +0x9c\ngithub.com/grpc-ecosystem/go-grpc-middleware/auth.UnaryServerInterceptor.func1(0x2d703b8, 0xc0019afc50, 0x2808b00, 0xc000d58b40, 0xc000fcca80, 0xc000f4af00, 0xc0019afcb0, 0x3, 0x3, 0x7f841d4e4598)\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.1-0.20190118093823-f849b5445de4/auth/auth.go:46 +0x10e\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x2d703b8, 0xc0019afc50, 0x2808b00, 0xc000d58b40, 0x31, 0xc000f4af50, 0x0, 0x0)\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.1-0.20190118093823-f849b5445de4/chain.go:34 +0x9c\ngithub.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).UnaryServerInterceptor.func1(0x2d703b8, 0xc0019afc50, 0x2808b00, 0xc000d58b40, 0xc000fcca80, 0xc000f4af00, 0x0, 0x0, 0x0, 0x0)\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-prometheus@v1.2.0/server_metrics.go:107 +0xb0\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x2d703b8, 0xc0019afc50, 0x2808b00, 0xc000d58b40, 0x31, 0xc020aa1adfe51745, 0x234b39582a4, 0x42ec540)\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.1-0.20190118093823-f849b5445de4/chain.go:34 +0x9c\ngithub.com/grpc-ecosystem/go-grpc-middleware/logging/logrus.UnaryServerInterceptor.func1(0x2d703b8, 0xc0019afaa0, 0x2808b00, 0xc000d58b40, 0xc000fcca80, 0xc000f4af00, 0xc000acb9a0, 0x40da3b, 0xc000f4af00, 0x50)\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.1-0.20190118093823-f849b5445de4/logging/logrus/server_interceptors.go:32 +0x10f\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x2d703b8, 0xc0019afaa0, 0x2808b00, 0xc000d58b40, 0x7f84443495b8, 0x50, 0xc000f4af00, 0x0)\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.1-0.20190118093823-f849b5445de4/chain.go:34 +0x9c\ngithub.com/argoproj/argo-cd/v2/server.bug21955WorkaroundInterceptor(0x2d703b8, 0xc0019afaa0, 0x2808b00, 0xc000d58b40, 0xc000fcca80, 0xc000f4af00, 0xc000500800, 0x0, 0xc000acba50, 0x40e198)\n\t/go/src/github.com/argoproj/argo-cd/server/server.go:1073 +0x177\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1(0x2d703b8, 0xc0019afaa0, 0x2808b00, 0xc000d58b40, 0xc000fcca80, 0xc000efb5c0, 0xc000acbac0, 0x5290c6, 0x27117e0, 0xc0019afaa0)\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.1-0.20190118093823-f849b5445de4/chain.go:39 +0x15b\ngithub.com/argoproj/argo-cd/v2/pkg/apiclient/application._ApplicationService_RunResourceAction_Handler(0x2869ce0, 0xc0006e3d40, 0x2d703b8, 0xc0019afaa0, 0xc0007bbd50, 0xc000bd4390, 0x2d703b8, 0xc0019afaa0, 0xc0012ff180, 0x2d8df10)\n\t/go/src/github.com/argoproj/argo-cd/pkg/apiclient/application/application.pb.go:3133 +0x150\ngoogle.golang.org/grpc.(*Server).processUnaryRPC(0xc000503980, 0x2d93458, 0xc001126000, 0xc0019c1b00, 0xc000bd47e0, 0x42bc308, 0x0, 0x0, 0x0)\n\t/go/pkg/mod/google.golang.org/grpc@v1.15.0/server.go:982 +0x4eb\ngoogle.golang.org/grpc.(*Server).handleStream(0xc000503980, 0x2d93458, 0xc001126000, 0xc0019c1b00, 0x0)\n\t/go/pkg/mod/google.golang.org/grpc@v1.15.0/server.go:1208 +0x122c\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.1(0xc00108fe50, 0xc000503980, 0x2d93458, 0xc001126000, 0xc0019c1b00)\n\t/go/pkg/mod/google.golang.org/grpc@v1.15.0/server.go:686 +0xab\ncreated by google.golang.org/grpc.(*Server).serveStreams.func1\n\t/go/pkg/mod/google.golang.org/grpc@v1.15.0/server.go:684 +0xa5\n"
time="2021-05-17T09:01:31Z" level=error msg="finished unary call with code Internal" error="rpc error: code = Internal desc = runtime error: index out of range [2] with length 2" grpc.code=Internal grpc.method=RunResourceAction grpc.service=application.ApplicationService grpc.start_time="2021-05-17T09:01:31Z" grpc.time_ms=17.277 span.kind=server system=grpc
```

**Comment by jannfis** [comment]
This might be a problem with your Lua script. The following does work:

```
action.lua: |
  env = obj.spec.template.spec.containers[1].env
  if env == nil then
    env = {}
  end
  env[#env+1] = {["name"] = "FOO", ["value"] = "bar"}
  obj.spec.template.spec.containers[1].env = env
  return obj
```

**Comment by msessa** [comment]
@jannfis unfortunately your snippet returned the same index out of bound error

**Comment by PoliM** [comment]
I also have that problem. My custom action adds a snyc window to an AppProject in `obj.spec.syncWindows`.

- when obj.spec.syncWindows is nil --> it works
- when it is an empty array --> does not work: "index out of range [0] with length 0"
- when there is already one sync window --> does not work: "index out of range [1] with length 1"

The problem is in https://github.com/argoproj/argo-cd/blob/d5a961c7f648bd752a32ee67a7c11a8706633ab9/util/lua/lua.go#L207 
It goes through the new array which contains one more element than the old. From the stack trace the index violation happens on line 212.

I was using v2.5.7 but the code for cleanReturnedArray in the master branch is the same.

**Comment by ab-gaikwad** [comment]
I am facing the same error, we cannot use table.insert in Lua
