### ISSUE TITLE
ArgoCD UI crashes 1.7.6+

### ISSUE THREAD

**Issue by SabySen** [argoproj/argo-cd#6257]
**Describe the bug**

Stacktrace:
ArgoCD UI all of a sudden started to fail with the following ...

TypeError: Cannot read property 'split' of undefined
    at m.match (https://argocd-np.digital-services.cvshealth.com/main.2e65a524d04617fac156.js:33:480154)
    at h (https://argocd-np.digital-services.cvshealth.com/main.2e65a524d04617fac156.js:33:474962)
    at https://argocd-np.digital-services.cvshealth.com/main.2e65a524d04617fac156.js:33:313777
    at Array.some (<anonymous>)
    at https://argocd-np.digital-services.cvshealth.com/main.2e65a524d04617fac156.js:33:313752
    at Array.filter (<anonymous>)
    at ec (https://argocd-np.digital-services.cvshealth.com/main.2e65a524d04617fac156.js:33:313337)
    at Object.children (https://argocd-np.digital-services.cvshealth.com/main.2e65a524d04617fac156.js:33:319077)
    at t.render (https://argocd-np.digital-services.cvshealth.com/main.2e65a524d04617fac156.js:33:86283)
    at Oi (https://argocd-np.digital-services.cvshealth.com/main.2e65a524d04617fac156.js:354:63228)

**To Reproduce**
No Idea how to reproduce this.

**Expected behavior**

ArgoCD UI has been working well but it stopped working all of a sudden

**Screenshots**

**Version**
1.7.6+

```shell
argocd version
argocd: v1.7.2+c342d3f
  BuildDate: 2020-08-27T23:33:37Z
  GitCommit: c342d3fc9c9c9f0d1c18254b6ffa1e106984a76c
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by SabySen** [comment]
Closing this issue. Duplicate of https://github.com/argoproj/argo-cd/issues/4134
