### ISSUE TITLE
Something went wrong!

### ISSUE THREAD

**Issue by AlestanAlves** [argoproj/argo-cd#6381]
This is error:

TypeError: Cannot read property 'status' of undefined
    at https://192.168.2.115:32536/main.609177d542c0f7568c20.js:33:335298
    at Array.forEach (<anonymous>)
    at t.processTree (https://192.168.2.115:32536/main.609177d542c0f7568c20.js:33:335159)
    at Object.children (https://192.168.2.115:32536/main.609177d542c0f7568c20.js:33:327892)
    at t.render (https://192.168.2.115:32536/main.609177d542c0f7568c20.js:33:181715)
    at Ha (https://192.168.2.115:32536/main.609177d542c0f7568c20.js:354:70056)
    at Ra (https://192.168.2.115:32536/main.609177d542c0f7568c20.js:354:69851)
    at gs (https://192.168.2.115:32536/main.609177d542c0f7568c20.js:354:105644)
    at fc (https://192.168.2.115:32536/main.609177d542c0f7568c20.js:354:96894)
    at lc (https://192.168.2.115:32536/main.609177d542c0f7568c20.js:354:96819)

![Screenshot from 2021-06-02 15-57-52](https://user-images.githubusercontent.com/48387196/120537170-5bb7b980-c3bb-11eb-886f-ce4f5c4f7434.png)

**Comment by rbreeze** [comment]
Which page are you seeing this on?

**Comment by AlestanAlves** [comment]
when I click inside my created app so I can see it
