### ISSUE TITLE
TypeError: Cannot read property 'kind' of null

### ISSUE THREAD

**Issue by arnitolog** [argoproj/argo-cd#6631]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

After the application upgrade (Kafka cluster) I can't view Kafka Resource details anymore.

**To Reproduce**

A list of the steps required to reproduce the issue. Best of all, give us the URL to a repository that exhibits this issue.

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/34036079/124352906-fea66200-dc0b-11eb-9035-49ba0f7f1634.png)

**Version**

```shell
{
    "Version": "v2.0.4+0842d44",
    "BuildDate": "2021-06-23T01:27:53Z",
    "GitCommit": "0842d448107eb1397b251e63ec4d4bc1b4efdd6e",
    "GitTreeState": "clean",
    "GoVersion": "go1.16",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KsonnetVersion": "v0.13.1",
    "KustomizeVersion": "v3.9.4 2021-02-09T19:22:10Z",
    "HelmVersion": "v3.5.1+g32c2223",
    "KubectlVersion": "v0.20.4",
    "JsonnetVersion": "v0.17.0"
}
```

**Logs**

```
Stacktrace:

TypeError: Cannot read property 'kind' of null
    at t.getResourceTabs (https://argocd-dev.us.dev.kube.test.com/main.782fadfd9a299d06c15e.js:33:417380)
    at Object.children (https://argocd-dev.us.dev.kube.test.com/main.782fadfd9a299d06c15e.js:33:405431)
    at t.render (https://argocd-dev.us.dev.kube.test.com/main.782fadfd9a299d06c15e.js:33:181715)
    at Ha (https://argocd-dev.us.dev.kube.test.com/main.782fadfd9a299d06c15e.js:354:70056)
    at Ra (https://argocd-dev.us.dev.kube.test.com/main.782fadfd9a299d06c15e.js:354:69851)
    at gs (https://argocd-dev.us.dev.kube.test.com/main.782fadfd9a299d06c15e.js:354:105644)
    at fc (https://argocd-dev.us.dev.kube.test.com/main.782fadfd9a299d06c15e.js:354:96894)
    at lc (https://argocd-dev.us.dev.kube.test.com/main.782fadfd9a299d06c15e.js:354:96819)
    at tc (https://argocd-dev.us.dev.kube.test.com/main.782fadfd9a299d06c15e.js:354:93852)
    at https://argocd-dev.us.dev.kube.test.com/main.782fadfd9a299d06c15e.js:354:45525
```

**Comment by arnitolog** [comment]
it looks like it was an issue on my side. closing this
