### ISSUE TITLE
TypeError: Cannot read property 'group' of undefined

### ISSUE THREAD

**Issue by wobo-mattmencel** [argoproj/argo-cd#6736]
**Describe the bug**

> Something went wrong!

**To Reproduce**

I had drilled in to an application and was selecting some of the filter parameters when I got the "Something went wrong" screen.

Possibly related to having the "Show Orphaned" box checked?

**Expected behavior**

UI works as expected.

**Version**

```shell
argocd: v2.0.4+0842d44.dirty
  BuildDate: 2021-06-23T06:31:09Z
  GitCommit: 0842d448107eb1397b251e63ec4d4bc1b4efdd6e
  GitTreeState: dirty
  GoVersion: go1.16.5
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v2.0.0+30d2ba1
  BuildDate: 2021-07-15T04:12:53Z
  GitCommit: 30d2ba1f1c282b46d6bfc0e813937a760b13cfef
  GitTreeState: clean
  GoVersion: go1.16.5
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v4.1.2 2021-04-15T20:38:06Z
  Helm Version: v3.6.0+g7f2df64
  Kubectl Version: v0.21.0
  Jsonnet Version: v0.17.0
  ```

**Logs**

```
Stacktrace:

TypeError: Cannot read property 'group' of undefined
    at hs (https://argo.foo.com/main.b314c5eaf6dac0644394.js:54:260247)
    at https://argo.foo.com/main.b314c5eaf6dac0644394.js:54:384846
    at Array.map (<anonymous>)
    at Jc (https://argo.foo.com/main.b314c5eaf6dac0644394.js:54:384795)
    at Xa (https://argo.foo.com/main.b314c5eaf6dac0644394.js:375:58117)
    at Ii (https://argo.foo.com/main.b314c5eaf6dac0644394.js:375:66978)
    at gs (https://argo.foo.com/main.b314c5eaf6dac0644394.js:375:105562)
    at fl (https://argo.foo.com/main.b314c5eaf6dac0644394.js:375:96894)
    at cl (https://argo.foo.com/main.b314c5eaf6dac0644394.js:375:96819)
    at tl (https://argo.foo.com/main.b314c5eaf6dac0644394.js:375:93852)
```

**Comment by alexmt** [comment]
Thank you @wobo-mattmencel ! The bug was introduced by  https://github.com/argoproj/argo-cd/pull/6171. Created fix here: https://github.com/alexmt/argo-cd/pull/new/6736-js-crash
