### ISSUE TITLE
 Access to settings/repos it disappeared

### ISSUE THREAD

**Issue by alicepaixao** [argoproj/argo-cd#6832]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [ X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ X] I've included steps to reproduce the bug.
* [ X] I've pasted the output of `argocd version`.

**Describe the bug**

Stacktrace:

Error: Invalid url.
    at e.exports (https://my-url/main.fcd351b8cd5b32100cef.js:392:1221)
    at e.exports (https://my-url/main.fcd351b8cd5b32100cef.js:392:349)
    at o (https://my-url/main.fcd351b8cd5b32100cef.js:382:172161)
    at https://my-url/main.fcd351b8cd5b32100cef.js:33:276392
    at Si (https://my-url/main.fcd351b8cd5b32100cef.js:33:276471)
    at Xi (https://my-url/main.fcd351b8cd5b32100cef.js:354:58117)
    at gs (https://my-url/main.fcd351b8cd5b32100cef.js:354:104346)
    at fc (https://my-url/main.fcd351b8cd5b32100cef.js:354:96894)
    at lc (https://my-url/main.fcd351b8cd5b32100cef.js:354:96819)
    at tc (https://my-url/main.fcd351b8cd5b32100cef.js:354:93852)

**Version**

v2.0.5+4c94d88

**Comment by alexmt** [comment]
Hello @alicepaixao ,

The error is reproducible if the settings have a repository with an empty URL. The UI should gracefully handle it. Created PR to fix it: https://github.com/argoproj/argo-cd/pull/6833

To unblock you I recommend checking `repositories` key in `argocd-cm`  and see if you have an entry with empty URL.
