### ISSUE TITLE
panic: send on closed channel in kube.copyEventsChannel

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#699]
```
time="2018-10-18T00:51:36Z" level=info msg="Stop retrying watch app resources on https://kubernetes.default.svc"
panic: send on closed channel

goroutine 404 [running]:
github.com/argoproj/argo-cd/util/kube.copyEventsChannel.func1(0xc42064f4a0, 0xc42004447b, 0xc42068c360, 0xc42064f500)
        /go/src/github.com/argoproj/argo-cd/util/kube/kube.go:296 +0x5c
created by github.com/argoproj/argo-cd/util/kube.copyEventsChannel
        /go/src/github.com/argoproj/argo-cd/util/kube/kube.go:291 +0xad
```

**Comment by jessesuen** [comment]
2498f60c57b705cfe27105b832bba8ea210e03c3 fixes some things in this area where we were not doing things in a thread-safe manner. Closing this unless reproduced.
