### ISSUE TITLE
Server crash of argocd-server deployed in HA mode

### ISSUE THREAD

**Issue by yuxintong-github** [argoproj/argo-cd#7576]
- [x]  I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
- [x] I've included steps to reproduce the bug.
The argocd-server will crashed one time in 1-2 days.
- [x] I've pasted the output of argocd version.
Argocd-server Verion is: "quay.io/argoproj/argocd:v2.1.5"

**Describe the bug**

The argocd-server will crashed one time in 1-2 days. Here is the error logs:

```
redis: 2021/10/27 09:56:33 pubsub.go:168: redis: discarding bad PubSub connection: redis: ping timeout
redis: 2021/10/27 09:56:35 pubsub.go:168: redis: discarding bad PubSub connection: redis: ping timeout
redis: 2021/10/27 09:56:37 pubsub.go:168: redis: discarding bad PubSub connection: redis: ping timeout
redis: 2021/10/27 09:56:39 pubsub.go:168: redis: discarding bad PubSub connection: redis: ping timeout
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x574482]

goroutine 104654 [running]:
bufio.(*Writer).Flush(0xc00069e340, 0x1, 0x7f84eee99818)
/usr/local/go/src/bufio/bufio.go:607 +0x62
net/http.(*response).Flush(0xc0004fe620)
/usr/local/go/src/net/http/server.go:1681 +0x35
github.com/argoproj/pkg/grpc/http.writeKeepalive(0x3c47a80, 0xc0004fe620, 0xc001368120)
/go/pkg/mod/github.com/argoproj/pkg@v0.9.1/grpc/http/forwarders.go:151 +0x182
github.com/argoproj/pkg/grpc/http.keepalive(0x3c4fd50, 0xc000853b40, 0x3c47a80, 0xc0004fe620, 0xc001368120)
/go/pkg/mod/github.com/argoproj/pkg@v0.9.1/grpc/http/forwarders.go:166 +0x9f
created by github.com/argoproj/pkg/grpc/http.withKeepalive
/go/pkg/mod/github.com/argoproj/pkg@v0.9.1/grpc/http/forwarders.go:174 +0x9a
```

It can also crashed with these logs:

```
time="2021-10-27T16:55:37Z" level=info msg="Alloc=122344 TotalAlloc=222979156 Sys=211447 NumGC=6918 Goroutines=304"
time="2021-10-27T17:02:06Z" level=info msg="finished streaming call with code OK" grpc.code=OK grpc.method=Watch grpc.service=application.ApplicationService grpc.start_time="2021-10-27T14:35:37Z" grpc.time_ms=8.789139e+06 span.kind=server system=grpc
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x574482]

goroutine 4980 [running]:
bufio.(*Writer).Flush(0xc000141100, 0x1, 0x7f553e7a9fa0)
/usr/local/go/src/bufio/bufio.go:607 +0x62
net/http.(*response).Flush(0xc0000f8d20)
/usr/local/go/src/net/http/server.go:1681 +0x35
github.com/argoproj/pkg/grpc/http.writeKeepalive(0x3c493c0, 0xc0000f8d20, 0xc001d3e000)
/go/pkg/mod/github.com/argoproj/pkg@v0.9.1/grpc/http/forwarders.go:151 +0x182
github.com/argoproj/pkg/grpc/http.keepalive(0x3c51690, 0xc000140700, 0x3c493c0, 0xc0000f8d20, 0xc001d3e000)
/go/pkg/mod/github.com/argoproj/pkg@v0.9.1/grpc/http/forwarders.go:166 +0x9f
created by github.com/argoproj/pkg/grpc/http.withKeepalive
/go/pkg/mod/github.com/argoproj/pkg@v0.9.1/grpc/http/forwarders.go:174 +0x9a
```

**Comment by yuxintong-github** [comment]
Anyone can help? 😶

**Comment by yuxintong-github** [comment]
Anyone can help? 😶

**Comment by yuxintong-github** [comment]
Pls help on this, thank you

**Comment by zczc0128** [comment]
Met same issue in ArgoCD v2.1.5 , any one can help on this? Thanks!


panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x574482]

goroutine 8034 [running]:
bufio.(*Writer).Flush(0xc0028c22c0, 0x1, 0x7f5ecc56fe18)
/usr/local/go/src/bufio/bufio.go:607 +0x62
net/http.(*response).Flush(0xc002dfe460)
/usr/local/go/src/net/http/server.go:1681 +0x35
github.com/argoproj/pkg/grpc/http.writeKeepalive(0x3c493c0, 0xc002dfe460, 0xc001f29378)
/go/pkg/mod/github.com/argoproj/pkg@v0.9.1/grpc/http/forwarders.go:151 +0x182
github.com/argoproj/pkg/grpc/http.keepalive(0x3c51690, 0xc000d87d40, 0x3c493c0, 0xc002dfe460, 0xc001f29378)
/go/pkg/mod/github.com/argoproj/pkg@v0.9.1/grpc/http/forwarders.go:166 +0x9f
created by github.com/argoproj/pkg/grpc/http.withKeepalive
/go/pkg/mod/github.com/argoproj/pkg@v0.9.1/grpc/http/forwarders.go:174 +0x9a
