### ISSUE TITLE
SyncOperationRequest fails when there are SyncOperationResources defined

### ISSUE THREAD

**Issue by paragones92** [argoproj/argo-cd#7601]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

While using the `github.com/argoproj/argo-cd/v2` library to automate some stuff in ArgoCD, we are having a problem for a slice of [SyncOperationResource](https://pkg.go.dev/github.com/argoproj/argo-cd/v2@v2.1.6/pkg/apis/application/v1alpha1#SyncOperationResource) in the [SyncOperation](https://pkg.go.dev/github.com/argoproj/argo-cd/v2@v2.1.6/pkg/apis/application/v1alpha1#SyncOperation) struct.

```
panic: reflect: Elem of invalid type v1alpha1.SyncOperationResource

goroutine 1 [running]:
reflect.(*rtype).Elem(0x43543c4)
        /usr/local/go/src/reflect/type.go:954 +0x134
google.golang.org/protobuf/internal/impl.isInitMessageSlice({0x5eb3ae0}, {0x5f4a260, 0x5a8d400})
        /Users/pauaragones/go/pkg/mod/google.golang.org/protobuf@v1.27.1/internal/impl/codec_field.go:574 +0x70
google.golang.org/protobuf/internal/impl.makeMessageSliceFieldCoder.func4({0x5b73ee0}, 0x43cba11)
        /Users/pauaragones/go/pkg/mod/google.golang.org/protobuf@v1.27.1/internal/impl/codec_field.go:463 +0x25
google.golang.org/protobuf/internal/impl.(*MessageInfo).checkInitializedPointer(0xc00034a420, {0x5f3bdd0})
        /Users/pauaragones/go/pkg/mod/google.golang.org/protobuf@v1.27.1/internal/impl/checkinit.go:58 +0x22b
google.golang.org/protobuf/internal/impl.(*MessageInfo).checkInitialized(0x0, {{}, {0x5f3bdd0, 0xc0005b21a0}})
        /Users/pauaragones/go/pkg/mod/google.golang.org/protobuf@v1.27.1/internal/impl/checkinit.go:22 +0x50
google.golang.org/protobuf/proto.checkInitialized({0x5f3bdd0, 0xc0005b21a0})
        /Users/pauaragones/go/pkg/mod/google.golang.org/protobuf@v1.27.1/proto/checkinit.go:27 +0x44
google.golang.org/protobuf/proto.CheckInitialized({0x5eb3ae0, 0xc0005b21a0})
        /Users/pauaragones/go/pkg/mod/google.golang.org/protobuf@v1.27.1/proto/checkinit.go:21 +0x33
github.com/golang/protobuf/proto.checkRequiredNotSet(...)
        /Users/pauaragones/go/pkg/mod/github.com/golang/protobuf@v1.5.2/proto/proto.go:122
github.com/golang/protobuf/proto.marshalAppend({0x0, 0x0, 0x0}, {0xffbb358, 0xc000a9bb80}, 0x0)
        /Users/pauaragones/go/pkg/mod/github.com/golang/protobuf@v1.5.2/proto/wire.go:49 +0xfa
github.com/golang/protobuf/proto.Marshal(...)
        /Users/pauaragones/go/pkg/mod/github.com/golang/protobuf@v1.5.2/proto/wire.go:23
google.golang.org/grpc/encoding/proto.codec.Marshal({}, {0x5b73ee0, 0xc000a9bb80})
        /Users/pauaragones/go/pkg/mod/google.golang.org/grpc@v1.40.0/encoding/proto/proto.go:45 +0x4e
google.golang.org/grpc.encode({0x1023b558, 0x7305a70}, {0x5b73ee0, 0xc000a9bb80})
        /Users/pauaragones/go/pkg/mod/google.golang.org/grpc@v1.40.0/rpc_util.go:594 +0x44
google.golang.org/grpc.prepareMsg({0x5b73ee0, 0xc000a9bb80}, {0x1023b558, 0x7305a70}, {0x0, 0x0}, {0x0, 0x0})
        /Users/pauaragones/go/pkg/mod/google.golang.org/grpc@v1.40.0/stream.go:1603 +0xd2
google.golang.org/grpc.(*clientStream).SendMsg(0xc0003c1560, {0x5b73ee0, 0xc000a9bb80})
        /Users/pauaragones/go/pkg/mod/google.golang.org/grpc@v1.40.0/stream.go:784 +0x176
google.golang.org/grpc.invoke({0x5ef3d90, 0xc000052058}, {0x5c24726, 0x8}, {0x5b73ee0, 0xc000a9bb80}, {0x5be0de0, 0xc00063ec00}, 0xc00063ec00, {0xc0004216a0, ...})
        /Users/pauaragones/go/pkg/mod/google.golang.org/grpc@v1.40.0/call.go:70 +0xa8
github.com/grpc-ecosystem/go-grpc-middleware/retry.UnaryClientInterceptor.func1({0x5ef3d90, 0xc000052058}, {0x5c24726, 0x24}, {0x5b73ee0, 0xc000a9bb80}, {0x5be0de0, 0xc00063ec00}, 0x0, 0x5cedee8, ...)
        /Users/pauaragones/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.1-0.20190118093823-f849b5445de4/retry/retry.go:43 +0x23d
google.golang.org/grpc.(*ClientConn).Invoke(0x7d66f18, {0x5ef3d90, 0xc000052058}, {0x5c24726, 0x0}, {0x5b73ee0, 0xc000a9bb80}, {0x5be0de0, 0xc00063ec00}, {0x0, ...})
        /Users/pauaragones/go/pkg/mod/google.golang.org/grpc@v1.40.0/call.go:35 +0x21f
github.com/argoproj/argo-cd/v2/pkg/apiclient/application.(*applicationServiceClient).Sync(0xc000010048, {0x5ef3d90, 0xc000052058}, 0x5, {0x0, 0x0, 0x0})
        /Users/pauaragones/go/pkg/mod/github.com/argoproj/argo-cd/v2@v2.1.6/pkg/apiclient/application/application.pb.go:2449 +0xc9
```

**To Reproduce**

A list of the steps required to reproduce the issue. Best of all, give us the URL to a repository that exhibits this issue. 

The code is the following:

go.mod
```go
go 1.17

require (
	github.com/argoproj/argo-cd/v2 v2.1.5
)
```

argo.go
```go
package argo

import (
	"context"
	"fmt"

	"github.com/argoproj/argo-cd/v2/pkg/apiclient"
	"github.com/argoproj/argo-cd/v2/pkg/apiclient/application"
	"github.com/argoproj/argo-cd/v2/pkg/apiclient/session"
	argoapp "github.com/argoproj/argo-cd/v2/pkg/apis/application/v1alpha1"
	argoio "github.com/argoproj/argo-cd/v2/util/io"
)

// Synchronizes a single cluster secret for all applications
func SyncClusterSecret(ns string, app string, secret string) error {
        appSyncReq := application.ApplicationSyncRequest{
			Name:     &app,
			Revision: "HEAD",
			DryRun:   false,
			Prune:    false,
			Strategy: &argoapp.SyncStrategy{},
			Resources: []argoapp.SyncOperationResource{
				{
					Kind:      "Secret",
					Name:      secret,
					Namespace: ns,
				},
			},
			RetryStrategy: &argoapp.RetryStrategy{Limit: 5},
	}
}
```

**Expected behavior**

The error not to happen. Strangely enough, this issue does not occur when the `Resources` field is empty.

**Screenshots**

**Version**

```shell
argocd: v2.1.5+a8a6fc8
  BuildDate: 2021-10-20T15:18:52Z
  GitCommit: a8a6fc8dda0e26bb1e0b893e270c1128038f5b0f
  GitTreeState: clean
  GoVersion: go1.16.5
  Compiler: gc
  Platform: darwin/amd64
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by paragones92** [comment]
Not a bug from argocd, it eas related to cobra version used alongside it, which we downgraded to version `1.1.3` from `1.2.1`, for anybody interested in this issue. Thanks!

**Comment by RuiGuo34** [comment]
@paragones92 I doubt it. I am using cobra `1.1.3` and argo-cd/v2 `v2.2.3` and yet I still encounter this problem.

**Comment by RuiGuo34** [comment]
It turned out be a bug in old version of argo-cd/v2. I am not able to reproduce this for argo-cd/v2 `v2.4.11`
