### ISSUE TITLE
argocd cli intermittent panic during  app sync

### ISSUE THREAD

**Issue by fivesheep** [argoproj/argo-cd#7752]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

argocd cli panic when doing `argocd app sync` 

**To Reproduce**

I had run command `argocd app sync myapp  --insecure  --grpc-web --force` to sync with an argocd server exposed with kubectl port forwarding, the command line tool crashed after print out part of the sync information.

**Expected behavior**

no crash

**Screenshots**

**Version**

```shell
argocd: v2.1.7+a408e29
  BuildDate: 2021-11-17T22:12:41Z
  GitCommit: a408e299ffa743213df3aa9135bf7945644ec936
  GitTreeState: clean
  GoVersion: go1.16.5
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v2.1.7+a408e29
  BuildDate: 2021-11-17T22:10:27Z
  GitCommit: a408e299ffa743213df3aa9135bf7945644ec936
  GitTreeState: clean
  GoVersion: go1.16.5
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v4.2.0 2021-06-30T22:49:26Z
  Helm Version: v3.6.0+g7f2df64
  Kubectl Version: v0.21.0
  Jsonnet Version: v0.17.0
```

**Logs**

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x32f94db]

goroutine 1 [running]:
github.com/argoproj/argo-cd/v2/cmd/argocd/commands.NewApplicationSyncCommand.func1(0xc000214a00, 0xc000523500, 0x1, 0x4)
	/go/src/github.com/argoproj/argo-cd/cmd/argocd/commands/app.go:1420 +0x73b
github.com/spf13/cobra.(*Command).execute(0xc000214a00, 0xc000522840, 0x4, 0x4, 0xc000214a00, 0xc000522840)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:856 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0xc000629900, 0x12, 0x0, 0x0)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
main.main()
	/go/src/github.com/argoproj/argo-cd/cmd/main.go:43 +0xd8
```

**Comment by pasha-codefresh** [comment]
Can`t reproduce this issue. Could you please add argocd version that you use. @fivesheep

**Comment by rkatti** [comment]
I am seeing this on Argo CD v2.1.8+unknown
Build Date
2021-12-14T23:25:40Z
Go Version
go1.16.6
Go Compiler
gc
Platform
linux/amd64
ksonnet
unable to determine ksonnet version: exec: "ks": executable file not found in $PATH
jsonnet
v0.17.0
kustomize
v4.2.0 1970-01-01T00:00:00Z

**Comment by conman2305** [comment]
Just started seeing this with the 2.2.3 version of argocd:

```
[03/01/2022 10:17:39 PM] [DEBUG]: Run ArgoCD Command: argocd --insecure --grpc-web --server <serverName> app sync <appName>
[03/01/2022 10:17:43 PM] [ERROR]: panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x27dddec]
goroutine 1 [running]:
github.com/argoproj/argo-cd/v2/cmd/argocd/commands.NewApplicationSyncCommand.func1(0xc00054d680, 0xc0001b0050, 0x1, 0x5)
	/go/src/github.com/argoproj/argo-cd/cmd/argocd/commands/app.go:1449 +0x7cc
github.com/spf13/cobra.(*Command).execute(0xc00054d680, 0xc0003ecf00, 0x5, 0x8, 0xc00054d680, 0xc0003ecf00)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:856 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0xc0000fef00, 0x12, 0x0, 0x0)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
main.main()
	/go/src/github.com/argoproj/argo-cd/cmd/main.go:46 +0xe5
```

```
argocd: v2.2.3+987f665
  BuildDate: 2022-01-18T17:53:49Z
  GitCommit: 987f6659b88e656a8f6f8feef87f4dd467d53c44
  GitTreeState: clean
  GoVersion: go1.16.11
  Compiler: gc
  Platform: linux/amd64
 ```

**Comment by robax** [comment]
We are hitting this in the docker image `quay.io/argoproj/argocd:v2.0.4`

Command we run: `argocd --server argocd-server.argocd --plaintext app sync --force <application-name>`

`19:33:03  panic: runtime error: invalid memory address or nil pointer dereference
19:33:03  [signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x231b3db]
19:33:03  
19:33:03  goroutine 1 [running]:
19:33:03  github.com/argoproj/argo-cd/v2/cmd/argocd/commands.NewApplicationSyncCommand.func1(0xc0001a58c0, 0xc000c99450, 0x1, 0x5)
19:33:03  	/go/src/github.com/argoproj/argo-cd/cmd/argocd/commands/app.go:1418 +0x73b
19:33:03  github.com/spf13/cobra.(*Command).execute(0xc0001a58c0, 0xc000c8ec00, 0x5, 0x6, 0xc0001a58c0, 0xc000c8ec00)
19:33:03  	/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:854 +0x2c2
19:33:03  github.com/spf13/cobra.(*Command).ExecuteC(0xc0001e0580, 0x12, 0x0, 0x0)
19:33:03  	/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x375
19:33:03  github.com/spf13/cobra.(*Command).Execute(...)
19:33:03  	/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
19:33:03  main.main()
19:33:03  	/go/src/github.com/argoproj/argo-cd/cmd/main.go:60 +0x1d6`

**Comment by caseyscarborough** [comment]
Also seeing the same issue here. Running Argo CD 2.2.8 and ArgoCD CLI version 2.2.5.

Command used:

```bash
argocd app sync <app-name> \
  --grpc-web \
  --timeout=300 \
  --server=<server-address> \
  --auth-token=<auth-token>
```

Error:

```bash  
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x27de7ac]

goroutine 1 [running]:
github.com/argoproj/argo-cd/v2/cmd/argocd/commands.NewApplicationSyncCommand.func1(0xc000ba1400, 0xc000119c20, 0x1, 0x5)
	/go/src/github.com/argoproj/argo-cd/cmd/argocd/commands/app.go:1449 +0x7cc
github.com/spf13/cobra.(*Command).execute(0xc000ba1400, 0xc000119bd0, 0x5, 0x5, 0xc000ba1400, 0xc000119bd0)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:856 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0xc000c0a000, 0x12, 0x0, 0x0)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
main.main()
	/go/src/github.com/argoproj/argo-cd/cmd/main.go:46 +0xe5
```

**Comment by dtelaroli** [comment]
I get the same error with docker image `argoproj/argocd:v2.3.4`
The error does not happen in local v2.3.4 installation with brew in macOS.

### Command:

```
argocd app sync my-env --server argocd.pismo.services:443 --auth-token $token --grpc-web --resource argoproj.io:Application:my-app
```

### Error:

```
panic: runtime error: invalid memory address or nil pointer dereference                                                                                          
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x25b05f1]                                                                                         
                                                                                                                                                                 
goroutine 1 [running]:                                                                                                                                           
github.com/argoproj/argo-cd/v2/cmd/argocd/commands.NewApplicationSyncCommand.func1(0xc000a6f680, {0xc000296880, 0x1, 0x8})                                       
        /go/src/github.com/argoproj/argo-cd/cmd/argocd/commands/app.go:1467 +0x13d1                                                                              
github.com/spf13/cobra.(*Command).execute(0xc000a6f680, {0xc000296800, 0x8, 0x8})                                                                                
        /go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:860 +0x5f8                                                                                          
github.com/spf13/cobra.(*Command).ExecuteC(0xc000a26a00)                                                                                                         
        /go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x3bc                                                                                          
github.com/spf13/cobra.(*Command).Execute(...)                                                                                                                   
        /go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902                                                                                                 
main.main()                                                                                                                                                      
        /go/src/github.com/argoproj/argo-cd/cmd/main.go:52 +0x245
```

**Comment by hontarenko** [comment]
Version argo server - `quay.io/argoproj/argocd:v2.4.11`
Command:
`argocd app wait ${{ env.APP }} --operation --plaintext && argocd app sync ${{ env.APP }} --plaintext && argocd app wait ${{ env.APP }} --health --plaintext`
Error:
`panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x29baa06]

goroutine 1 [running]:
github.com/argoproj/argo-cd/v2/cmd/argocd/commands.NewApplicationSyncCommand.func1(0xc000e30c80?, {0xc000dd9200, 0x1, 0x2})
	/home/runner/work/argo-cd/argo-cd/cmd/argocd/commands/app.go:1537 +0x1966
github.com/spf13/cobra.(*Command).execute(0xc000e30c80, {0xc000dd91e0, 0x2, 0x2})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:860 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0xc000df0000)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:902
main.main()
	/home/runner/work/argo-cd/argo-cd/cmd/main.go:57 +0x2c5
Error: Process completed with exit code 2.`
