### ISSUE TITLE
Cannot read properties of undefined on page load

### ISSUE THREAD

**Issue by subhashchy** [argoproj/argo-cd#8502]
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

After upgrading, The page stopped opening - seeing this error 
 
`Stacktrace:

TypeError: Cannot read properties of undefined (reading 'includes')
    at https://cd.mydukaan.io/main.9e5f142f83ba5c1c033a.js:54:358905
    at Array.map (<anonymous>)
    at https://cd.mydukaan.io/main.9e5f142f83ba5c1c033a.js:54:358455
    at bm (https://cd.mydukaan.io/main.9e5f142f83ba5c1c033a.js:54:359368)
    at Object.children (https://cd.mydukaan.io/main.9e5f142f83ba5c1c033a.js:54:363870)
    at Gt.render (https://cd.mydukaan.io/main.9e5f142f83ba5c1c033a.js:356:104805)
    at Ii (https://cd.mydukaan.io/main.9e5f142f83ba5c1c033a.js:397:69869)
    at Yi (https://cd.mydukaan.io/main.9e5f142f83ba5c1c033a.js:397:69664)
    at gs (https://cd.mydukaan.io/main.9e5f142f83ba5c1c033a.js:397:105463)
    at cl (https://cd.mydukaan.io/main.9e5f142f83ba5c1c033a.js:397:96710)`

**To Reproduce**

**Expected behavior**

**Screenshots**

![Screenshot 2022-02-15 at 11 22 28 AM](https://user-images.githubusercontent.com/29503067/154000794-60c5f435-94b7-43b8-ab9a-5ce33171679f.png)

**Version**
[v2.3.0-rc2]

**Comment by subhashchy** [comment]
This is fixed in [v2.3.0-rc5]
can be closed.
