### ISSUE TITLE
Fix application controller panic

### ISSUE THREAD

**Issue by kshamajain99** [argoproj/argo-cd#8711]
**Describe the bug**

Got an alert for application controller panic

**Logs**

```
msg=\"Recovered from panic: runtime error: invalid memory address or nil pointer dereference\
goroutine 805 [running]:\
runtime/debug.Stack()\
\\t/usr/local/go/src/runtime/debug/stack.go:24 +0x65\
github.com/argoproj/argo-cd/v2/controller.(*ApplicationController).processAppRefreshQueueItem.func1()\
\\t/go/src/github.com/argoproj/argo-cd/controller/appcontroller.go:1233 +0x65\
panic({0x2907ca0, 0x57b9a60})\
\\t/usr/local/go/src/runtime/panic.go:1047 +0x266\
github.com/argoproj/argo-cd/v2/pkg/apis/application/v1alpha1.(*ApplicationTree).GetSummary(0xc07ad68280)\
\\t/go/src/github.com/argoproj/argo-cd/pkg/apis/application/v1alpha1/types.go:1108 +0x60a\
github.com/argoproj/argo-cd/v2/controller.(*ApplicationController).processAppRefreshQueueItem(0xc000c95200)\
\\t/go/src/github.com/argoproj/argo-cd/controller/appcontroller.go:1281 +0x816\
github.com/argoproj/argo-cd/v2/controller.(*ApplicationController).Run.func3()\
\\t/go/src/github.com/argoproj/argo-cd/controller/appcontroller.go:673 +0x29\
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x7f8282221dd8)\
\\t/go/pkg/mod/k8s.io/apimachinery@v0.23.1/pkg/util/wait/wait.go:155 +0x67\
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x0, {0x3dcc8a0, 0xc0009a35c0}, 0x1, 0xc0008ac8a0)\
\\t/go/pkg/mod/k8s.io/apimachinery@v0.23.1/pkg/util/wait/wait.go:156 +0xb6\
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x4f46566b557a6758, 0x3b9aca00, 0x0, 0x60, 0xc0011c2818)\
\\t/go/pkg/mod/k8s.io/apimachinery@v0.23.1/pkg/util/wait/wait.go:133 +0x89\
k8s.io/apimachinery/pkg/util/wait.Until(0x66693054506e4e45, 0x616e222c223d3058, 0xc0011f2798)\
\\t/go/pkg/mod/k8s.io/apimachinery@v0.23.1/pkg/util/wait/wait.go:90 +0x25\
created by github.com/argoproj/argo-cd/v2/controller.(*ApplicationController).Run\
\\t/go/src/github.com/argoproj/argo-cd/controller/appcontroller.go:672 +0x71d\
\"",
```

**Version**

```shell
Paste the output from `argocd version` here.
```

**Comment by kshamajain99** [comment]
It appears error is in following piece of code. For some reason node is nil. 
https://github.com/argoproj/argo-cd/blob/dab15e99ec0e6d7e84255c23e9d0def4ebc44b08/pkg/apis/application/v1alpha1/types.go#L1103-L1110

**Comment by kshamajain99** [comment]
Testing the [PR](https://github.com/argoproj/gitops-engine/pull/377/files) caused the application controller to panic. Issue will be fixed by the PR. There is no action item on our side.
