### ISSUE TITLE
ppc64le: make dep-ui fails to build node-sass

### ISSUE THREAD

**Issue by krishvoor** [argoproj/argo-cd#8745]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**
Upon further investigation it was found that, node-sass could not be built, as g++ was missing.

**To Reproduce**
`make dep-ui` on ppc64le architecture

**Expected behavior**
`make dep-ui`

**Screenshots**

**Version**

```shell
root@p006vm81:/home/argo-cd/dist# ./argocd version
argocd: v2.3.0+f905145.dirty
  BuildDate: 2022-03-10T18:27:53Z
  GitCommit: f90514587bafcce51e0e2cd6044195fed2266707
  GitTreeState: dirty
  GoVersion: go1.17.6
  Compiler: gc
  Platform: linux/ppc64le
FATA[0000] Argo CD server address unspecified           
root@p006vm81:/home/argo-cd/dist# arch
ppc64le
root@p006vm81:/home/argo-cd/dist# 
```

**Logs**

```
-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-D__STDC_FORMAT_MACROS' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DLIBSASS_VERSION="3.5.5"' -I/home/user/.cache/node-gyp/12.18.4/include/node -I/home/user/.cache/node-gyp/12.18.4/src -I/home/user/.cache/node-gyp/12.18.4/deps/openssl/config -I/home/user/.cache/node-gyp/12.18.4/deps/openssl/openssl/include -I/home/user/.cache/node-gyp/12.18.4/deps/uv/include -I/home/user/.cache/node-gyp/12.18.4/deps/zlib -I/home/user/.cache/node-gyp/12.18.4/deps/v8/include -I../src/libsass/include -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -mminimal-toc -O3 -fno-omit-frame-pointer -std=gnu++1y -std=c++0x -fexceptions -frtti -MMD -MF ./Release/.deps/Release/obj.target/libsass/src/libsass/src/ast.o.d.raw -c
make[1]: g++: No such file or directory
make[1]: * [src/[libsass.target.mk:159](https://www.google.com/url?q=http://libsass.target.mk:159&sa=D&source=docs&ust=1646663810750581&usg=AOvVaw3EmQDVtJoT121TPl19fv2l): Release/obj.target/libsass/src/libsass/src/ast.o] Error 127
make[1]: Leaving directory '/go/src/[github.com/argoproj/argo-cd/ui/node_modules/node-sass/build](https://www.google.com/url?q=http://github.com/argoproj/argo-cd/ui/node_modules/node-sass/build&sa=D&source=docs&ust=1646663810750796&usg=AOvVaw2yCTu95iJRqO0fE_5yju-z)'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack at ChildProcess.onExit (/go/src/[github.com/argoproj/argo-cd/ui/node_modules/node-gyp/lib/build.js:194:23](https://www.google.com/url?q=http://github.com/argoproj/argo-cd/ui/node_modules/node-gyp/lib/build.js:194:23&sa=D&source=docs&ust=1646663810750924&usg=AOvVaw0n7ekSTJ3UrL2xSL_QaDgQ))
gyp ERR! stack at ChildProcess.emit (events.js:315:20)
gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 5.4.0-92-generic
gyp ERR! command "/usr/local/bin/node" "/go/src/[github.com/argoproj/argo-cd/ui/node_modules/node-gyp/bin/node-gyp.js](https://www.google.com/url?q=http://github.com/argoproj/argo-cd/ui/node_modules/node-gyp/bin/node-gyp.js&sa=D&source=docs&ust=1646663810751051&usg=AOvVaw0SUIWZ0_9UsYCziFpJBRB5)" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /go/src/[github.com/argoproj/argo-cd/ui/node_modules/node-sass](https://www.google.com/url?q=http://github.com/argoproj/argo-cd/ui/node_modules/node-sass&sa=D&source=docs&ust=1646663810751152&usg=AOvVaw0yb-8RRtEVf3eqWM67iS1Z)
gyp ERR! node -v v12.18.4
```

**Comment by military19** [comment]
Hi @krishvoor .. Is this this bug still relevant ? Is it particularly for a specific argocd version (v2.3.0) that need to be built ?

**Comment by krishvoor** [comment]
Hi @military19 I will defer this @asanjar for more information.

**Comment by kabhiibm** [comment]
Hi @krishvoor , thanks for your response. We tried to reproduce this defect but don't find it reproducible with the same error posted by you. We aren't able to close it. So, can you kindly close this defect.

**Comment by krishvoor** [comment]
@kabhiibm - thanks for confirming!
