### ISSUE TITLE
Can't disconnect a repository

### ISSUE THREAD

**Issue by marcio-pessoa** [argoproj/argo-cd#8774]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Using the web user interface, I am unable to disconnect a repository with incorrect SSH private key data previously configured.

**To Reproduce**

Creating a repository connection:

- On "Settings / Repositories" screen, click on "CONNECT REPO USING SSH";
- Fill "Name";
- Fill "Project";
- Fill "Repository URL";
- Fill "SSH private key data" with an incorrect certificate;
- Check "Skip server verification"
- Click on "Connect"

Disconnecting:

- Find the repository;
- Click on three dots icon;
- Click on "Disconnect" option;
- Click on "OK" button.

Nothing happens, just an error on browser console.

**Expected behavior**

The repository connection must be removed from the "Repositories" list.

**Version**

```shell
argocd: v2.3.1+b65c169
  BuildDate: 2022-03-10T22:51:09Z
  GitCommit: b65c1699fa2a2daa031483a3890e6911eac69068
  GitTreeState: clean
  GoVersion: go1.17.6
  Compiler: gc
  Platform: linux/amd64
```

**Logs**

When I click on "Disconnect" and confirm I got the following errors on Google Chrome console:

```
main.c7ea22e999b3805bc676.js:388          DELETE https://intellimon.paytvlabs.com.br/argo-cd/api/v1/repositories/git%40git.paytvlabs.com.br%3Amarcio.pessoa%2Fportal.git 404
b._end @ main.c7ea22e999b3805bc676.js:388
b.end @ main.c7ea22e999b3805bc676.js:388
(anonymous) @ main.c7ea22e999b3805bc676.js:420
n.then @ main.c7ea22e999b3805bc676.js:420
delete @ main.c7ea22e999b3805bc676.js:54
(anonymous) @ main.c7ea22e999b3805bc676.js:54
o @ main.c7ea22e999b3805bc676.js:54
Promise.then (async)
a @ main.c7ea22e999b3805bc676.js:54
(anonymous) @ main.c7ea22e999b3805bc676.js:54
Im @ main.c7ea22e999b3805bc676.js:54
disconnectRepo @ main.c7ea22e999b3805bc676.js:54
action @ main.c7ea22e999b3805bc676.js:54
onItemClick @ main.c7ea22e999b3805bc676.js:363
onClick @ main.c7ea22e999b3805bc676.js:363
a @ main.c7ea22e999b3805bc676.js:404
p @ main.c7ea22e999b3805bc676.js:404
(anonymous) @ main.c7ea22e999b3805bc676.js:404
b @ main.c7ea22e999b3805bc676.js:404
st @ main.c7ea22e999b3805bc676.js:404
rt @ main.c7ea22e999b3805bc676.js:404
at @ main.c7ea22e999b3805bc676.js:404
pt @ main.c7ea22e999b3805bc676.js:404
F @ main.c7ea22e999b3805bc676.js:404
W @ main.c7ea22e999b3805bc676.js:404
Zt @ main.c7ea22e999b3805bc676.js:404
Xt @ main.c7ea22e999b3805bc676.js:404
t.unstable_runWithPriority @ main.c7ea22e999b3805bc676.js:412
zr @ main.c7ea22e999b3805bc676.js:404
P @ main.c7ea22e999b3805bc676.js:404
$t @ main.c7ea22e999b3805bc676.js:404
main.c7ea22e999b3805bc676.js:388 Uncaught (in promise) Error: Unsuccessful HTTP response
    at n.<anonymous> (main.c7ea22e999b3805bc676.js:388:51395)
    at n.i.emit (main.c7ea22e999b3805bc676.js:420:47964)
    at XMLHttpRequest.t.onreadystatechange (main.c7ea22e999b3805bc676.js:388:54810)
(anonymous) @ main.c7ea22e999b3805bc676.js:388
i.emit @ main.c7ea22e999b3805bc676.js:420
t.onreadystatechange @ main.c7ea22e999b3805bc676.js:388
Promise.then (async)
a @ main.c7ea22e999b3805bc676.js:54
o @ main.c7ea22e999b3805bc676.js:54
Promise.then (async)
a @ main.c7ea22e999b3805bc676.js:54
(anonymous) @ main.c7ea22e999b3805bc676.js:54
Im @ main.c7ea22e999b3805bc676.js:54
disconnectRepo @ main.c7ea22e999b3805bc676.js:54
action @ main.c7ea22e999b3805bc676.js:54
onItemClick @ main.c7ea22e999b3805bc676.js:363
onClick @ main.c7ea22e999b3805bc676.js:363
a @ main.c7ea22e999b3805bc676.js:404
p @ main.c7ea22e999b3805bc676.js:404
(anonymous) @ main.c7ea22e999b3805bc676.js:404
b @ main.c7ea22e999b3805bc676.js:404
st @ main.c7ea22e999b3805bc676.js:404
rt @ main.c7ea22e999b3805bc676.js:404
at @ main.c7ea22e999b3805bc676.js:404
pt @ main.c7ea22e999b3805bc676.js:404
F @ main.c7ea22e999b3805bc676.js:404
W @ main.c7ea22e999b3805bc676.js:404
Zt @ main.c7ea22e999b3805bc676.js:404
Xt @ main.c7ea22e999b3805bc676.js:404
t.unstable_runWithPriority @ main.c7ea22e999b3805bc676.js:412
zr @ main.c7ea22e999b3805bc676.js:404
P @ main.c7ea22e999b3805bc676.js:404
$t @ main.c7ea22e999b3805bc676.js:404
```

**Comment by rishabh625** [comment]
on clicking disconnect it removes connection, can u please share more details?

**Comment by marcio-pessoa** [comment]
Hi @rishabh625,

Yes, normally it removes the connection, but it fails to remove only connections created with incorrect SSH key.

I recorded a video with the failure:

https://youtu.be/2KrRjcNHS10

**Comment by rishabh625** [comment]
Looks like browser compatibility issues, can you please share browser used and it's version

**Comment by kreeuwijk** [comment]
I have the same issue, for me it is an incorrectly formatted repo URL that causes the behavior. The server logs show
```
level=info msg="finished unary call with code NotFound" error="rpc error: code = NotFound desc = repo 'ssh://git@gitlab.dreamworx.nl:argo/apps.git' not found"
```

A correctly formatted repo URL (`git@gitlab.dreamworx.nl:argo/apps.git`) can be deleted normally.

**Comment by marcio-pessoa** [comment]
I found a workaround on discussions:

https://github.com/argoproj/argo-cd/discussions/8547

**Comment by mbrozzo** [comment]
Hello, I am using the ArgoCD operator for OpenShift in OKD and I am having a similar problem. When I click "Disconnect" on a repository I get this error:
`Unable to disconnect repository: repo 'git clone git@[ADDRESS].git' not found`

I had wrongfully left "git clone" in the repository URL.

**Comment by alkakumari016** [comment]
This issue has been resolved as part of https://github.com/argoproj/argo-cd/issues/20921 . I don't see any similar issue in v2.14 or above. Feel free to create a fresh issue if the issue still persists. Thankyou.
