### ISSUE TITLE
Argo CD build fails on M1 Pro Mac (arm) 

### ISSUE THREAD

**Issue by evgeny-goldin** [argoproj/argo-cd#8880]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Make fails to build an Argo CD image on M1 Pro MacBook

**To Reproduce**

* `make image` fails with

```
> [argocd-ui 4/6] RUN yarn install --network-timeout 200000:
...
#44 32.84 gyp verb find Python Python is not set from command line or npm configuration
...
#44 32.84 gyp ERR! configure error
#44 32.84 gyp ERR! stack Error: Could not find any Python installation to use
#44 32.84 gyp ERR! stack     at PythonFinder.fail (/src/node_modules/node-gyp/lib/find-python.js:330:47)
#44 32.84 gyp ERR! stack     at PythonFinder.runChecks (/src/node_modules/node-gyp/lib/find-python.js:159:21)
#44 32.84 gyp ERR! stack     at PythonFinder.<anonymous> (/src/node_modules/node-gyp/lib/find-python.js:266:16)
#44 32.84 gyp ERR! stack     at PythonFinder.execFileCallback (/src/node_modules/node-gyp/lib/find-python.js:297:7)
#44 32.84 gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:7)
#44 32.84 gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
#44 32.84 gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
#44 32.84 gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
#44 32.84 gyp ERR! System Linux 5.10.104-linuxkit
#44 32.84 gyp ERR! command "/usr/local/bin/node" "/src/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
#44 32.84 gyp ERR! cwd /src/node_modules/node-sass
#44 32.84 gyp ERR! node -v v12.18.4
#44 32.84 gyp ERR! node-gyp -v v8.4.1
#44 32.84 gyp ERR! not ok
#44 32.84 Build failed with error code: 1
```

**Expected behavior**

* Build passes

**Screenshots**

**Version**

```shell
$ argocd version
argocd: v2.3.2+ecc2af9.dirty
  BuildDate: 2022-03-23T05:13:28Z
  GitCommit: ecc2af9dcaa12975e654cde8cbbeaffbb315f75c
  GitTreeState: dirty
  GoVersion: go1.18
  Compiler: gc
  Platform: darwin/arm64
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by evgeny-goldin** [comment]
A PR is on its way to address the issue - https://github.com/evgeny-goldin/argo-cd/commits/master
