### ISSUE TITLE
UI crashes in "Pods" view when grouping by "Parent Resource" if a Pod without parent exists

### ISSUE THREAD

**Issue by rodrigorato** [argoproj/argo-cd#9529]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**
In the "Pods" view of an Application, when grouping by "Parent Resource" if there exists a pod in said Application that does not have a parent, the UI crashes.

**To Reproduce**
1. Create an Application in ArgoCD
2. Add a Pod to the Application created in 1. without a controller (i.e. ReplicaSet/Job/Deployment/etc.)
3. Login to ArgoCD UI
4. Navigate to the Application created in 1.
5. Open the "Pods" view
6. Group by "Parent Resource"
7. It crashes with the following stacktrace 😢

```
Something went wrong!

Consider submitting an issue here.


Stacktrace:

TypeError: Cannot read properties of undefined (reading 'status')
    at https://my.argocd.instance.com/main.cab489a5e3dc68a2b715.js:33:335298
    at Array.forEach (<anonymous>)
    at t.processTree (https://my.argocd.instance.com/main.cab489a5e3dc68a2b715.js:33:335159)
    at Object.children (https://my.argocd.instance.com/main.cab489a5e3dc68a2b715.js:33:327892)
    at t.render (https://my.argocd.instance.com/main.cab489a5e3dc68a2b715.js:33:181715)
    at Ha (https://my.argocd.instance.com/main.cab489a5e3dc68a2b715.js:354:70056)
    at Ra (https://my.argocd.instance.com/main.cab489a5e3dc68a2b715.js:354:69851)
    at gs (https://my.argocd.instance.com/main.cab489a5e3dc68a2b715.js:354:105644)
    at fc (https://my.argocd.instance.com/main.cab489a5e3dc68a2b715.js:354:96894)
    at lc (https://my.argocd.instance.com/main.cab489a5e3dc68a2b715.js:354:96819)
``` 

**Expected behavior**
Instead of the UI crashing, the view should show up and maybe list the Pod as the "Parent Resource" for itself. 

**Screenshots**
N/A

**Version**

```shell
argocd-server: v2.0.0+f5119c0
  BuildDate: 2021-04-07T06:00:33Z
  GitCommit: f5119c06686399134b3f296d44445bcdbc778d42
  GitTreeState: clean
  GoVersion: go1.16
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v3.9.4 2021-02-09T19:22:10Z
  Helm Version: v3.5.1+g32c2223
  Kubectl Version: v0.20.4
  Jsonnet Version: v0.17.0
```

**Logs**
N/A

**Comment by crenshaw-dev** [comment]
@rodrigorato is upgrading a possibility?

**Comment by keithchong** [comment]
Closing
